In [1]:
# Nostradamus One: NTS Framework for all pairs.
import pandas as pd
import numpy as np

In [2]:
# TP WIN/LOSS RATE 0:00 -> 09:00 (Noxtradamus V2)
# Include HIGH AND LOW FOR 10:00 AND 11:00 | H10 L10 & H11 L11
H1FullUsdChf_pd = pd.read_csv('datasets/2018-06-12-UsdChfH1_raw.csv')

H1FullUsdChf_pd.columns = ['Date', 'Time', 'Open','High','Low','Close', 'Vol']
H1FullUsdChf_pd = H1FullUsdChf_pd.set_index('Date')
H1FullUsdChf_pd = H1FullUsdChf_pd.drop(['Vol'], axis=1)
H1FullUsdChf_pd

             Time     Open     High      Low    Close
Date
2015.05.19  11:00  0.93110  0.93270  0.93010  0.93170
2015.05.19  12:00  0.93160  0.93200  0.93000  0.93040
2015.05.19  13:00  0.93040  0.93110  0.92960  0.92990
2015.05.19  14:00  0.92990  0.93190  0.92970  0.92970
2015.05.19  15:00  0.92970  0.93760  0.92960  0.93710
2015.05.19  16:00  0.93710  0.93720  0.93360  0.93480
2015.05.19  17:00  0.93470  0.93790  0.93430  0.93770
2015.05.19  18:00  0.93780  0.93810  0.93590  0.93660
2015.05.19  19:00  0.93650  0.93720  0.93580  0.93590
2015.05.19  20:00  0.93590  0.93800  0.93580  0.93720
2015.05.19  21:00  0.93720  0.93740  0.93640  0.93700
2015.05.19  22:00  0.93700  0.93740  0.93600  0.93740
2015.05.19  23:00  0.93740  0.93750  0.93600  0.93600
2015.05.20  00:00  0.93670  0.93690  0.93640  0.93660
2015.05.20  01:00  0.93670  0.93710  0.93650  0.93690
2015.05.20  02:00  0.93680  0.93710  0.93660  0.93690
2015.05.20  03:00  0.93700  0.93820  0.93680  0.93710
2015.05.20  04:00  0.93700  0.93750  0.93640  0.93680
2015.05.20  05:00  0.93680  0.93690  0.93560  0.93610
2015.05.20  06:00  0.93610  0.93640  0.93580  0.93620
2015.05.20  07:00  0.93620  0.93680  0.93580  0.93680
2015.05.20  08:00  0.93680  0.93780  0.93530  0.93780
2015.05.20  09:00  0.93780  0.93960  0.93710  0.93890
2015.05.20  10:00  0.93890  0.94030  0.93770  0.93870
2015.05.20  11:00  0.93870  0.93870  0.93570  0.93750
2015.05.20  12:00  0.93750  0.93830  0.93630  0.93740
2015.05.20  13:00  0.93740  0.94020  0.93690  0.93970
2015.05.20  14:00  0.93980  0.93990  0.93760  0.93800
2015.05.20  15:00  0.93800  0.93840  0.93490  0.93500
2015.05.20  16:00  0.93490  0.93820  0.93490  0.93710
...           ...      ...      ...      ...      ...
2018.06.08  12:00  0.98213  0.98338  0.98203  0.98274
2018.06.08  13:00  0.98273  0.98408  0.98235  0.98406
2018.06.08  14:00  0.98405  0.98492  0.98395  0.98410
2018.06.08  15:00  0.98411  0.98871  0.98408  0.98867
2018.06.08  16:00  0.98868  0.98871  0.98607  0.98734
2018.06.08  17:00  0.98733  0.98737  0.98500  0.98535
2018.06.08  18:00  0.98534  0.98652  0.98503  0.98594
2018.06.08  19:00  0.98595  0.98683  0.98550  0.98570
2018.06.08  20:00  0.98569  0.98609  0.98505  0.98509
2018.06.08  21:00  0.98510  0.98523  0.98461  0.98503
2018.06.08  22:00  0.98505  0.98583  0.98504  0.98521
2018.06.08  23:00  0.98519  0.98528  0.98425  0.98429
2018.06.11  00:00  0.98433  0.98477  0.98419  0.98442
2018.06.11  01:00  0.98440  0.98497  0.98439  0.98479
2018.06.11  02:00  0.98479  0.98501  0.98458  0.98481
2018.06.11  03:00  0.98481  0.98543  0.98450  0.98461
2018.06.11  04:00  0.98462  0.98475  0.98387  0.98427
2018.06.11  05:00  0.98428  0.98606  0.98421  0.98566
2018.06.11  06:00  0.98566  0.98580  0.98527  0.98535
2018.06.11  07:00  0.98536  0.98557  0.98512  0.98525
2018.06.11  08:00  0.98524  0.98581  0.98512  0.98569
2018.06.11  09:00  0.98570  0.98716  0.98543  0.98627
2018.06.11  10:00  0.98628  0.98649  0.98422  0.98598
2018.06.11  11:00  0.98600  0.98647  0.98444  0.98614
2018.06.11  12:00  0.98615  0.98668  0.98578  0.98635
2018.06.11  13:00  0.98637  0.98734  0.98594  0.98697
2018.06.11  14:00  0.98696  0.98729  0.98623  0.98667
2018.06.11  15:00  0.98665  0.98672  0.98480  0.98503
2018.06.11  16:00  0.98500  0.98544  0.98457  0.98493
2018.06.11  17:00  0.98495  0.98531  0.98407  0.98432

[19072 rows x 5 columns]

In [3]:
T0000UsdChf_pd = H1FullUsdChf_pd [(H1FullUsdChf_pd ['Time'] == '00:00')]

T0900UsdChf_pd = H1FullUsdChf_pd [(H1FullUsdChf_pd ['Time'] == '09:00')]
T0100UsdChf_pd = H1FullUsdChf_pd [(H1FullUsdChf_pd ['Time'] == '10:00')]
T0110UsdChf_pd = H1FullUsdChf_pd [(H1FullUsdChf_pd ['Time'] == '11:00')]

T0000UsdChf_pd.columns = ['T00', 'O00','H00','L00','C00']


T0900UsdChf_pd.columns = ['T09', 'O09','H09','L09','C09']
T0100UsdChf_pd.columns = ['T10', 'O10','H10','L10','C10']
T0110UsdChf_pd.columns = ['T11', 'O11','H11','L11','C11']


SummaryTable01 = pd.concat([T0000UsdChf_pd, T0900UsdChf_pd, T0100UsdChf_pd, T0110UsdChf_pd], axis=1)
SummaryTable01

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:15: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  from ipykernel import kernelapp as app

,T00,O00,H00,L00,C00,T09,O09,H09,L09,C09,T10,O10,H10,L10,C10,T11,O11,H11,L11,C11
2015.05.19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11:00,0.93110,0.93270,0.93010,0.93170
2015.05.20,00:00,0.93670,0.93690,0.93640,0.93660,09:00,0.93780,0.93960,0.93710,0.93890,10:00,0.93890,0.94030,0.93770,0.93870,11:00,0.93870,0.93870,0.93570,0.93750
2015.05.21,00:00,0.93680,0.93700,0.93610,0.93660,09:00,0.93450,0.93790,0.93450,0.93650,10:00,0.93660,0.93660,0.93290,0.93460,11:00,0.93460,0.93470,0.93120,0.93210
2015.05.22,00:00,0.93650,0.93680,0.93590,0.93670,09:00,0.93450,0.93450,0.93260,0.93360,10:00,0.93370,0.93450,0.93290,0.93320,11:00,0.93320,0.93340,0.93170,0.93180
2015.05.25,00:00,0.94310,0.94480,0.94260,0.94350,09:00,0.94150,0.94160,0.94020,0.94050,10:00,0.94050,0.94300,0.94020,0.94290,11:00,0.94290,0.94380,0.94280,0.94290
2015.05.26,00:00,0.94460,0.94530,0.94460,0.94500,09:00,0.94730,0.95110,0.94680,0.95060,10:00,0.95060,0.95120,0.94860,0.94920,11:00,0.94920,0.95170,0.94860,0.95040
2015.05.27,00:00,0.95320,0.95350,0.95250,0.95300,09:00,0.94960,0.95020,0.94670,0.94700,10:00,0.94700,0.94910,0.94690,0.94740,11:00,0.94740,0.94820,0.94690,0.94750
2015.05.28,00:00,0.94910,0.95010,0.94890,0.94990,09:00,0.94750,0.94900,0.94510,0.94580,10:00,0.94580,0.94780,0.94500,0.94500,11:00,0.94500,0.94740,0.94470,0.94580
2015.05.29,00:00,0.94300,0.94500,0.94150,0.94300,09:00,0.94300,0.94730,0.94230,0.94710,10:00,0.94710,0.94760,0.94350,0.94390,11:00,0.94390,0.94420,0.94210,0.94420
2015.06.01,00:00,0.94020,0.94020,0.93850,0.93920,09:00,0.94280,0.94530,0.94250,0.94470,10:00,0.94470,0.94740,0.94390,0.94620,11:00,0.94630,0.94690,0.94540,0.94660
2015.06.02,00:00,0.94550,0.94660,0.94450,0.94560,09:00,0.94460,0.94550,0.94110,0.94150,10:00,0.94160,0.94390,0.94030,0.94390,11:00,0.94380,0.94400,0.94090,0.94090
2015.06.03,00:00,0.93260,0.93300,0.93260,0.93280,09:00,0.93200,0.93300,0.92990,0.93230,10:00,0.93230,0.93540,0.93230,0.93380,11:00,0.93380,0.93520,0.93240,0.93500
2015.06.04,00:00,0.93350,0.93420,0.93350,0.93380,09:00,0.93360,0.93580,0.93320,0.93540,10:00,0.93540,0.93680,0.93480,0.93530,11:00,0.93540,0.93570,0.92750,0.92960
2015.06.05,00:00,0.93320,0.93380,0.93310,0.93370,09:00,0.93320,0.93390,0.93180,0.93210,10:00,0.93210,0.93290,0.92960,0.93080,11:00,0.93080,0.93240,0.93020,0.93220
2015.06.08,00:00,0.94220,0.94220,0.93950,0.94050,09:00,0.94040,0.94270,0.93730,0.93950,10:00,0.93950,0.93950,0.93640,0.93720,11:00,0.93720,0.94030,0.93710,0.93970
2015.06.09,00:00,0.92750,0.92760,0.92700,0.92740,09:00,0.92510,0.92770,0.92510,0.92690,10:00,0.92690,0.92940,0.92570,0.92640,11:00,0.92630,0.92760,0.92430,0.92690
2015.06.10,00:00,0.93030,0.93080,0.93030,0.93080,09:00,0.92880,0.93020,0.92700,0.92760,10:00,0.92760,0.92800,0.92300,0.92430,11:00,0.92430,0.92700,0.92300,0.92660
2015.06.11,00:00,0.93060,0.93200,0.92980,0.93170,09:00,0.93120,0.93250,0.92950,0.93140,10:00,0.93130,0.93410,0.93130,0.93300,11:00,0.93300,0.93730,0.93300,0.93520
2015.06.12,00:00,0.93240,0.93370,0.93220,0.93350,09:00,0.93330,0.93420,0.93300,0.93380,10:00,0.93380,0.93430,0.93210,0.93410,11:00,0.93410,0.93880,0.93310,0.93690
2015.06.15,00:00,0.92980,0.93000,0.92870,0.92930,09:00,0.93280,0.93310,0.92990,0.93020,10:00,0.93030,0.93200,0.92940,0.93090,11:00,0.93090,0.93150,0.92860,0.93040
2015.06.16,00:00,0.92900,0.92990,0.92890,0.92970,09:00,0.92930,0.93070,0.92730,0.92740,10:00,0.92740,0.93000,0.92690,0.92970,11:00,0.92960,0.93120,0.92810,0.93110
2015.06.17,00:00,0.93190,0.93220,0.93180,0.93200,09:00,0.93090,0.93120,0.92880,0.92950,10:00,0.92950,0.92970,0.92310,0.92550,11:00,0.92540,0.92600,0.92390,0.92580
2015.06.18,00:00,0.92120,0.92200,0.92120,0.92180,09:00,0.92020,0.92180,0.91980,0.92100,10:00,0.92110,0.92190,0.91850,0.91890,11:00,0.91880,0.91920,0.91520,0.91760
2015.06.19,00:00,0.92090,0.92120,0.92050,0.92120,09:00,0.92160,0.92310,0.92130,0.92240,10:00,0.92240,0.92410,0.92210,0.92320,11:00,0.92320,0.92380,0.92210,0.92250
2015.06.22,00:00,0.91690,0.91770,0.91610,0.91740,09:00,0.91720,0.91820,0.91610,0.91720,10:00,0.91720,0.92100,0.91630,0.91990,11:00,0.91970,0.92180,0.91960,0.91970
2015.06.23,00:00,0.92140,0.92180,0.92070,0.92120,09:00,0.92610,0.92870,0.92610,0.92640,10:00,0.92620,0.92770,0.92520,0.92710,11:00,0.92710,0.92940,0.92680,0.92850
2015.06.24,00:00,0.93370,0.93420,0.93370,0.93400,09:00,0.93250,0.93280,0.93060,0.93110,10:00,0.93120,0.93260,0.92870,0.92890,11:00,0.92890,0.93090,0.92780,0.93020
2015.06.25,00:00,0.93350,0.93350,0.93320,0.93330,09:00,0.93320,0.93550,0.93220,0.93490,10:00,0.93490,0.93550,0.93220,0.93460,11:00,0.93460,0.93670,0.93390,0.93650
2015.06.26,00:00,0.93610,0.93640,0.93540,0.93600,09:00,0.93680,0.93710,0.93520,0.93590,10:00,0.93580,0.93640,0.93320,0.93320,11:00,0.93330,0.93340,0.93160,0.93250
2015.06.29,00:00,0.93800,0.94130,0.93740,0.94020,09:00,0.93730,0.93900,0.93340,0.93490,10:00,0.93490,0.94260,0.93450,0.93840,11:00,0.93840,0.93890,0.93600,0.93670
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018.05.01,00:00,0.99049,0.99083,0.98988,0.99050,09:00,0.99162,0.99215,0.99144,0.99189,10:00,0.99192,0.99244,0.99164,0.99240,11:00,0.99239,0.99401,0.99221,0.99388
2018.05.02,00:00,0.99632,0.99692,0.99565,0.99640,09:00,0.99627,0.99644,0.99470,0.99523,10:00,0.99524,0.99571,0.99373,0.99451,11:00,0.99452,0.99571,0.99373,0.99536
2018.05.03,00:00,0.99830,0.99956,0.99830,0.99835,09:00,0.99723,0.99794,0.99613,0.99698,10:00,0.99701,0.99814,0.99565,0.99590,11:00,0.99589,0.99756,0.99586,0.99740
2018.05.04,00:00,0.99735,0.99789,0.99678,0.99759,09:00,0.99826,0.99945,0.99824,0.99934,10:00,0.99932,1.00001,0.99832,0.99905,11:00,0.99904,0.99932,0.99830,0.99905
2018.05.07,00:00,1.00001,1.00061,0.99967,1.00016,09:00,1.00017,1.00153,1.00017,1.00131,10:00,1.00132,1.00247,1.00090,1.00223,11:00,1.00222,1.00355,1.00220,1.00352
2018.05.08,00:00,1.00243,1.00307,1.00180,1.00288,09:00,1.00290,1.00318,1.00168,1.00313,10:00,1.00310,1.00340,1.00206,1.00229,11:00,1.00230,1.00460,1.00220,1.00396
2018.05.09,00:00,1.00158,1.00203,1.00094,1.00157,09:00,1.00318,1.00397,1.00270,1.00343,10:00,1.00342,1.00435,1.00297,1.00380,11:00,1.00379,1.00428,1.00266,1.00270
2018.05.10,00:00,1.00482,1.00544,1.00440,1.00487,09:00,1.00415,1.00463,1.00369,1.00449,10:00,1.00450,1.00535,1.00391,1.00484,11:00,1.00485,1.00497,1.00399,1.00401
2018.05.11,00:00,1.00267,1.00347,1.00215,1.00265,09:00,1.00320,1.00397,1.00270,1.00383,10:00,1.00384,1.00406,1.00293,1.00314,11:00,1.00313,1.00320,1.00178,1.00179
2018.05.14,00:00,1.00004,1.00077,0.99939,0.99957,09:00,0.99950,1.00040,0.99905,1.00011,10:00,1.00013,1.00021,0.99800,0.99827,11:00,0.99826,0.99957,0.99821,0.99904
2018.05.15,00:00,1.00056,1.00124,0.99997,1.00021,09:00,1.00108,1.00171,1.00060,1.00063,10:00,1.00064,1.00091,0.99928,1.00042,11:00,1.00043,1.00119,1.00012,1.00060
2018.05.16,00:00,1.00116,1.00153,1.00081,1.00103,09:00,0.99963,1.00028,0.99867,0.99886,10:00,0.99889,0.99957,0.99844,0.99936,11:00,0.99935,1.00027,0.99886,0.99888
2018.05.17,00:00,1.00110,1.00115,0.99984,1.00057,09:00,0.99930,1.00163,0.99930,1.00046,10:00,1.00048,1.00182,0.99999,1.00002,11:00,1.00000,1.00168,0.99973,1.00143
2018.05.18,00:00,1.00115,1.00163,1.00063,1.00118,09:00,1.00010,1.00063,0.99951,0.99951,10:00,0.99952,1.00025,0.99897,0.99983,11:00,0.99984,1.00027,0.99872,0.99919
2018.05.21,00:00,0.99673,0.99765,0.99669,0.99745,09:00,0.99903,0.99968,0.99870,0.99963,10:00,0.99962,1.00015,0.99899,0.99934,11:00,0.99932,0.99986,0.99856,0.99926
2018.05.22,00:00,0.99704,0.99743,0.99659,0.99680,09:00,0.99663,0.99852,0.99644,0.99850,10:00,0.99852,0.99905,0.99489,0.99489,11:00,0.99479,0.99672,0.99446,0.99640
2018.05.23,00:00,0.99257,0.99286,0.99198,0.99246,09:00,0.99277,0.99298,0.99042,0.99082,10:00,0.99089,0.99269,0.98941,0.99226,11:00,0.99227,0.99268,0.99085,0.99152
2018.05.24,00:00,0.99544,0.99565,0.99420,0.99475,09:00,0.99322,0.99430,0.99297,0.99402,10:00,0.99400,0.99408,0.99248,0.99298,11:00,0.99297,0.99311,0.99164,0.99191
2018.05.25,00:00,0.99119,0.99149,0.99026,0.99067,09:00,0.99252,0.99266,0.99155,0.99199,10:00,0.99197,0.99241,0.99166,0.99201,11:00,0.99202,0.99311,0.99182,0.99270
2018.05.28,00:00,0.99140,0.99281,0.99080,0.99218,09:00,0.99157,0.99202,0.99124,0.99189,10:00,0.99191,0.99258,0.99172,0.99190,11:00,0.99189,0.99286,0.99184,0.99198
2018.05.29,00:00,0.99305,0.99376,0.99276,0.99347,09:00,0.99319,0.99410,0.99243,0.99386,10:00,0.99388,0.99390,0.99297,0.99351,11:00,0.99349,0.99371,0.99210,0.99326
2018.05.30,00:00,0.99129,0.99131,0.98983,0.99072,09:00,0.99283,0.99336,0.99243,0.99304,10:00,0.99275,0.99352,0.99064,0.99131,11:00,0.99128,0.99139,0.98991,0.98992
2018.05.31,00:00,0.98884,0.98923,0.98843,0.98901,09:00,0.98844,0.98879,0.98785,0.98846,10:00,0.98842,0.98910,0.98691,0.98731,11:00,0.98729,0.98760,0.98683,0.98702
2018.06.01,00:00,0.98532,0.98600,0.98521,0.98527,09:00,0.98764,0.98917,0.98752,0.98903,10:00,0.98904,0.98909,0.98637,0.98735,11:00,0.98734,0.98751,0.98629,0.98639
2018.06.04,00:00,0.98842,0.98855,0.98778,0.98840,09:00,0.98760,0.98818,0.98725,0.98767,10:00,0.98766,0.98800,0.98565,0.98719,11:00,0.98722,0.98724,0.98482,0.98497
2018.06.05,00:00,0.98740,0.98838,0.98719,0.98783,09:00,0.98834,0.98864,0.98720,0.98734,10:00,0.98740,0.98823,0.98688,0.98710,11:00,0.98711,0.98761,0.98585,0.98594
2018.06.06,00:00,0.98401,0.98529,0.98367,0.98435,09:00,0.98462,0.98529,0.98363,0.98518,10:00,0.98520,0.98558,0.98391,0.98463,11:00,0.98461,0.98594,0.98428,0.98566
2018.06.07,00:00,0.98596,0.98660,0.98523,0.98593,09:00,0.98398,0.98446,0.98393,0.98432,10:00,0.98434,0.98468,0.98187,0.98257,11:00,0.98259,0.98264,0.98169,0.98217
2018.06.08,00:00,0.98022,0.98058,0.97916,0.97984,09:00,0.98086,0.98187,0.98039,0.98087,10:00,0.98086,0.98174,0.98016,0.98152,11:00,0.98151,0.98251,0.98064,0.98212
2018.06.11,00:00,0.98433,0.98477,0.98419,0.98442,09:00,0.98570,0.98716,0.98543,0.98627,10:00,0.98628,0.98649,0.98422,0.98598,11:00,0.98600,0.98647,0.98444,0.98614

In [4]:
# Selecting Columns for max value between H08 and H09
tableH10to11 = SummaryTable01[['H10','H11']]
tableH10to11['High 10To11'] = tableH10to11.max(axis=1)
tableH10to11

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

                H10      H11  High 10To11
2015.05.19      NaN  0.93270      0.93270
2015.05.20  0.94030  0.93870      0.94030
2015.05.21  0.93660  0.93470      0.93660
2015.05.22  0.93450  0.93340      0.93450
2015.05.25  0.94300  0.94380      0.94380
2015.05.26  0.95120  0.95170      0.95170
2015.05.27  0.94910  0.94820      0.94910
2015.05.28  0.94780  0.94740      0.94780
2015.05.29  0.94760  0.94420      0.94760
2015.06.01  0.94740  0.94690      0.94740
2015.06.02  0.94390  0.94400      0.94400
2015.06.03  0.93540  0.93520      0.93540
2015.06.04  0.93680  0.93570      0.93680
2015.06.05  0.93290  0.93240      0.93290
2015.06.08  0.93950  0.94030      0.94030
2015.06.09  0.92940  0.92760      0.92940
2015.06.10  0.92800  0.92700      0.92800
2015.06.11  0.93410  0.93730      0.93730
2015.06.12  0.93430  0.93880      0.93880
2015.06.15  0.93200  0.93150      0.93200
2015.06.16  0.93000  0.93120      0.93120
2015.06.17  0.92970  0.92600      0.92970
2015.06.18  0.92190  0.91920      0.92190
2015.06.19  0.92410  0.92380      0.92410
2015.06.22  0.92100  0.92180      0.92180
2015.06.23  0.92770  0.92940      0.92940
2015.06.24  0.93260  0.93090      0.93260
2015.06.25  0.93550  0.93670      0.93670
2015.06.26  0.93640  0.93340      0.93640
2015.06.29  0.94260  0.93890      0.94260
...             ...      ...          ...
2018.05.01  0.99244  0.99401      0.99401
2018.05.02  0.99571  0.99571      0.99571
2018.05.03  0.99814  0.99756      0.99814
2018.05.04  1.00001  0.99932      1.00001
2018.05.07  1.00247  1.00355      1.00355
2018.05.08  1.00340  1.00460      1.00460
2018.05.09  1.00435  1.00428      1.00435
2018.05.10  1.00535  1.00497      1.00535
2018.05.11  1.00406  1.00320      1.00406
2018.05.14  1.00021  0.99957      1.00021
2018.05.15  1.00091  1.00119      1.00119
2018.05.16  0.99957  1.00027      1.00027
2018.05.17  1.00182  1.00168      1.00182
2018.05.18  1.00025  1.00027      1.00027
2018.05.21  1.00015  0.99986      1.00015
2018.05.22  0.99905  0.99672      0.99905
2018.05.23  0.99269  0.99268      0.99269
2018.05.24  0.99408  0.99311      0.99408
2018.05.25  0.99241  0.99311      0.99311
2018.05.28  0.99258  0.99286      0.99286
2018.05.29  0.99390  0.99371      0.99390
2018.05.30  0.99352  0.99139      0.99352
2018.05.31  0.98910  0.98760      0.98910
2018.06.01  0.98909  0.98751      0.98909
2018.06.04  0.98800  0.98724      0.98800
2018.06.05  0.98823  0.98761      0.98823
2018.06.06  0.98558  0.98594      0.98594
2018.06.07  0.98468  0.98264      0.98468
2018.06.08  0.98174  0.98251      0.98251
2018.06.11  0.98649  0.98647      0.98649

[796 rows x 3 columns]

In [5]:
tableL10to11 = SummaryTable01[['L10','L11']]
tableL10to11['Low 10To11'] = tableL10to11.min(axis=1)
tableL10to11

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

                L10      L11  Low 10To11
2015.05.19      NaN  0.93010     0.93010
2015.05.20  0.93770  0.93570     0.93570
2015.05.21  0.93290  0.93120     0.93120
2015.05.22  0.93290  0.93170     0.93170
2015.05.25  0.94020  0.94280     0.94020
2015.05.26  0.94860  0.94860     0.94860
2015.05.27  0.94690  0.94690     0.94690
2015.05.28  0.94500  0.94470     0.94470
2015.05.29  0.94350  0.94210     0.94210
2015.06.01  0.94390  0.94540     0.94390
2015.06.02  0.94030  0.94090     0.94030
2015.06.03  0.93230  0.93240     0.93230
2015.06.04  0.93480  0.92750     0.92750
2015.06.05  0.92960  0.93020     0.92960
2015.06.08  0.93640  0.93710     0.93640
2015.06.09  0.92570  0.92430     0.92430
2015.06.10  0.92300  0.92300     0.92300
2015.06.11  0.93130  0.93300     0.93130
2015.06.12  0.93210  0.93310     0.93210
2015.06.15  0.92940  0.92860     0.92860
2015.06.16  0.92690  0.92810     0.92690
2015.06.17  0.92310  0.92390     0.92310
2015.06.18  0.91850  0.91520     0.91520
2015.06.19  0.92210  0.92210     0.92210
2015.06.22  0.91630  0.91960     0.91630
2015.06.23  0.92520  0.92680     0.92520
2015.06.24  0.92870  0.92780     0.92780
2015.06.25  0.93220  0.93390     0.93220
2015.06.26  0.93320  0.93160     0.93160
2015.06.29  0.93450  0.93600     0.93450
...             ...      ...         ...
2018.05.01  0.99164  0.99221     0.99164
2018.05.02  0.99373  0.99373     0.99373
2018.05.03  0.99565  0.99586     0.99565
2018.05.04  0.99832  0.99830     0.99830
2018.05.07  1.00090  1.00220     1.00090
2018.05.08  1.00206  1.00220     1.00206
2018.05.09  1.00297  1.00266     1.00266
2018.05.10  1.00391  1.00399     1.00391
2018.05.11  1.00293  1.00178     1.00178
2018.05.14  0.99800  0.99821     0.99800
2018.05.15  0.99928  1.00012     0.99928
2018.05.16  0.99844  0.99886     0.99844
2018.05.17  0.99999  0.99973     0.99973
2018.05.18  0.99897  0.99872     0.99872
2018.05.21  0.99899  0.99856     0.99856
2018.05.22  0.99489  0.99446     0.99446
2018.05.23  0.98941  0.99085     0.98941
2018.05.24  0.99248  0.99164     0.99164
2018.05.25  0.99166  0.99182     0.99166
2018.05.28  0.99172  0.99184     0.99172
2018.05.29  0.99297  0.99210     0.99210
2018.05.30  0.99064  0.98991     0.98991
2018.05.31  0.98691  0.98683     0.98683
2018.06.01  0.98637  0.98629     0.98629
2018.06.04  0.98565  0.98482     0.98482
2018.06.05  0.98688  0.98585     0.98585
2018.06.06  0.98391  0.98428     0.98391
2018.06.07  0.98187  0.98169     0.98169
2018.06.08  0.98016  0.98064     0.98016
2018.06.11  0.98422  0.98444     0.98422

[796 rows x 3 columns]

In [6]:
# Creating columns for Close 09
tableC09 = SummaryTable01[['C09']]
tableC09

                C09
2015.05.19      NaN
2015.05.20  0.93890
2015.05.21  0.93650
2015.05.22  0.93360
2015.05.25  0.94050
2015.05.26  0.95060
2015.05.27  0.94700
2015.05.28  0.94580
2015.05.29  0.94710
2015.06.01  0.94470
2015.06.02  0.94150
2015.06.03  0.93230
2015.06.04  0.93540
2015.06.05  0.93210
2015.06.08  0.93950
2015.06.09  0.92690
2015.06.10  0.92760
2015.06.11  0.93140
2015.06.12  0.93380
2015.06.15  0.93020
2015.06.16  0.92740
2015.06.17  0.92950
2015.06.18  0.92100
2015.06.19  0.92240
2015.06.22  0.91720
2015.06.23  0.92640
2015.06.24  0.93110
2015.06.25  0.93490
2015.06.26  0.93590
2015.06.29  0.93490
...             ...
2018.05.01  0.99189
2018.05.02  0.99523
2018.05.03  0.99698
2018.05.04  0.99934
2018.05.07  1.00131
2018.05.08  1.00313
2018.05.09  1.00343
2018.05.10  1.00449
2018.05.11  1.00383
2018.05.14  1.00011
2018.05.15  1.00063
2018.05.16  0.99886
2018.05.17  1.00046
2018.05.18  0.99951
2018.05.21  0.99963
2018.05.22  0.99850
2018.05.23  0.99082
2018.05.24  0.99402
2018.05.25  0.99199
2018.05.28  0.99189
2018.05.29  0.99386
2018.05.30  0.99304
2018.05.31  0.98846
2018.06.01  0.98903
2018.06.04  0.98767
2018.06.05  0.98734
2018.06.06  0.98518
2018.06.07  0.98432
2018.06.08  0.98087
2018.06.11  0.98627

[796 rows x 1 columns]

In [7]:
# ENTRY CALCULATION

EntryCalc = SummaryTable01['C09'] - SummaryTable01['C00']
EntryCalc = pd.DataFrame (EntryCalc, columns = ['Entry Calc'])
EntryCalc = EntryCalc.reset_index()

BullOrBear = np.where (EntryCalc ['Entry Calc'] > 0, 'bull', 'bear')
BullOrBear = pd.DataFrame (BullOrBear, columns = ['Bull / Bear'])

SummaryTable02 = pd.concat([EntryCalc, BullOrBear], axis=1)

SummaryTable02.columns = ['Date', 'Entry Calc','Bull/Bear']
SummaryTable02 = SummaryTable02.set_index('Date')

tableBlBr = SummaryTable02[['Bull/Bear']]
tableBlBr

           Bull/Bear
Date
2015.05.19      bear
2015.05.20      bull
2015.05.21      bear
2015.05.22      bear
2015.05.25      bear
2015.05.26      bull
2015.05.27      bear
2015.05.28      bear
2015.05.29      bull
2015.06.01      bull
2015.06.02      bear
2015.06.03      bear
2015.06.04      bull
2015.06.05      bear
2015.06.08      bear
2015.06.09      bear
2015.06.10      bear
2015.06.11      bear
2015.06.12      bull
2015.06.15      bull
2015.06.16      bear
2015.06.17      bear
2015.06.18      bear
2015.06.19      bull
2015.06.22      bear
2015.06.23      bull
2015.06.24      bear
2015.06.25      bull
2015.06.26      bear
2015.06.29      bear
...              ...
2018.05.01      bull
2018.05.02      bear
2018.05.03      bear
2018.05.04      bull
2018.05.07      bull
2018.05.08      bull
2018.05.09      bull
2018.05.10      bear
2018.05.11      bull
2018.05.14      bull
2018.05.15      bull
2018.05.16      bear
2018.05.17      bear
2018.05.18      bear
2018.05.21      bull
2018.05.22      bull
2018.05.23      bear
2018.05.24      bear
2018.05.25      bull
2018.05.28      bear
2018.05.29      bull
2018.05.30      bull
2018.05.31      bear
2018.06.01      bull
2018.06.04      bear
2018.06.05      bear
2018.06.06      bull
2018.06.07      bear
2018.06.08      bull
2018.06.11      bull

[796 rows x 1 columns]

In [8]:
summaryTable03 = pd.concat([tableC09, tableH10to11, tableL10to11, tableBlBr], axis=1)
summaryTable03

,C09,H10,H11,High 10To11,L10,L11,Low 10To11,Bull/Bear
Date,,,,,,,,
2015.05.19,NaN,NaN,0.93270,0.93270,NaN,0.93010,0.93010,bear
2015.05.20,0.93890,0.94030,0.93870,0.94030,0.93770,0.93570,0.93570,bull
2015.05.21,0.93650,0.93660,0.93470,0.93660,0.93290,0.93120,0.93120,bear
2015.05.22,0.93360,0.93450,0.93340,0.93450,0.93290,0.93170,0.93170,bear
2015.05.25,0.94050,0.94300,0.94380,0.94380,0.94020,0.94280,0.94020,bear
2015.05.26,0.95060,0.95120,0.95170,0.95170,0.94860,0.94860,0.94860,bull
2015.05.27,0.94700,0.94910,0.94820,0.94910,0.94690,0.94690,0.94690,bear
2015.05.28,0.94580,0.94780,0.94740,0.94780,0.94500,0.94470,0.94470,bear
2015.05.29,0.94710,0.94760,0.94420,0.94760,0.94350,0.94210,0.94210,bull
2015.06.01,0.94470,0.94740,0.94690,0.94740,0.94390,0.94540,0.94390,bull
2015.06.02,0.94150,0.94390,0.94400,0.94400,0.94030,0.94090,0.94030,bear
2015.06.03,0.93230,0.93540,0.93520,0.93540,0.93230,0.93240,0.93230,bear
2015.06.04,0.93540,0.93680,0.93570,0.93680,0.93480,0.92750,0.92750,bull
2015.06.05,0.93210,0.93290,0.93240,0.93290,0.92960,0.93020,0.92960,bear
2015.06.08,0.93950,0.93950,0.94030,0.94030,0.93640,0.93710,0.93640,bear
2015.06.09,0.92690,0.92940,0.92760,0.92940,0.92570,0.92430,0.92430,bear
2015.06.10,0.92760,0.92800,0.92700,0.92800,0.92300,0.92300,0.92300,bear
2015.06.11,0.93140,0.93410,0.93730,0.93730,0.93130,0.93300,0.93130,bear
2015.06.12,0.93380,0.93430,0.93880,0.93880,0.93210,0.93310,0.93210,bull
2015.06.15,0.93020,0.93200,0.93150,0.93200,0.92940,0.92860,0.92860,bull
2015.06.16,0.92740,0.93000,0.93120,0.93120,0.92690,0.92810,0.92690,bear
2015.06.17,0.92950,0.92970,0.92600,0.92970,0.92310,0.92390,0.92310,bear
2015.06.18,0.92100,0.92190,0.91920,0.92190,0.91850,0.91520,0.91520,bear
2015.06.19,0.92240,0.92410,0.92380,0.92410,0.92210,0.92210,0.92210,bull
2015.06.22,0.91720,0.92100,0.92180,0.92180,0.91630,0.91960,0.91630,bear
2015.06.23,0.92640,0.92770,0.92940,0.92940,0.92520,0.92680,0.92520,bull
2015.06.24,0.93110,0.93260,0.93090,0.93260,0.92870,0.92780,0.92780,bear
2015.06.25,0.93490,0.93550,0.93670,0.93670,0.93220,0.93390,0.93220,bull
2015.06.26,0.93590,0.93640,0.93340,0.93640,0.93320,0.93160,0.93160,bear
2015.06.29,0.93490,0.94260,0.93890,0.94260,0.93450,0.93600,0.93450,bear
...,...,...,...,...,...,...,...,...
2018.05.01,0.99189,0.99244,0.99401,0.99401,0.99164,0.99221,0.99164,bull
2018.05.02,0.99523,0.99571,0.99571,0.99571,0.99373,0.99373,0.99373,bear
2018.05.03,0.99698,0.99814,0.99756,0.99814,0.99565,0.99586,0.99565,bear
2018.05.04,0.99934,1.00001,0.99932,1.00001,0.99832,0.99830,0.99830,bull
2018.05.07,1.00131,1.00247,1.00355,1.00355,1.00090,1.00220,1.00090,bull
2018.05.08,1.00313,1.00340,1.00460,1.00460,1.00206,1.00220,1.00206,bull
2018.05.09,1.00343,1.00435,1.00428,1.00435,1.00297,1.00266,1.00266,bull
2018.05.10,1.00449,1.00535,1.00497,1.00535,1.00391,1.00399,1.00391,bear
2018.05.11,1.00383,1.00406,1.00320,1.00406,1.00293,1.00178,1.00178,bull
2018.05.14,1.00011,1.00021,0.99957,1.00021,0.99800,0.99821,0.99800,bull
2018.05.15,1.00063,1.00091,1.00119,1.00119,0.99928,1.00012,0.99928,bull
2018.05.16,0.99886,0.99957,1.00027,1.00027,0.99844,0.99886,0.99844,bear
2018.05.17,1.00046,1.00182,1.00168,1.00182,0.99999,0.99973,0.99973,bear
2018.05.18,0.99951,1.00025,1.00027,1.00027,0.99897,0.99872,0.99872,bear
2018.05.21,0.99963,1.00015,0.99986,1.00015,0.99899,0.99856,0.99856,bull
2018.05.22,0.99850,0.99905,0.99672,0.99905,0.99489,0.99446,0.99446,bull
2018.05.23,0.99082,0.99269,0.99268,0.99269,0.98941,0.99085,0.98941,bear
2018.05.24,0.99402,0.99408,0.99311,0.99408,0.99248,0.99164,0.99164,bear
2018.05.25,0.99199,0.99241,0.99311,0.99311,0.99166,0.99182,0.99166,bull
2018.05.28,0.99189,0.99258,0.99286,0.99286,0.99172,0.99184,0.99172,bear
2018.05.29,0.99386,0.99390,0.99371,0.99390,0.99297,0.99210,0.99210,bull
2018.05.30,0.99304,0.99352,0.99139,0.99352,0.99064,0.98991,0.98991,bull
2018.05.31,0.98846,0.98910,0.98760,0.98910,0.98691,0.98683,0.98683,bear
2018.06.01,0.98903,0.98909,0.98751,0.98909,0.98637,0.98629,0.98629,bull
2018.06.04,0.98767,0.98800,0.98724,0.98800,0.98565,0.98482,0.98482,bear
2018.06.05,0.98734,0.98823,0.98761,0.98823,0.98688,0.98585,0.98585,bear
2018.06.06,0.98518,0.98558,0.98594,0.98594,0.98391,0.98428,0.98391,bull
2018.06.07,0.98432,0.98468,0.98264,0.98468,0.98187,0.98169,0.98169,bear
2018.06.08,0.98087,0.98174,0.98251,0.98251,0.98016,0.98064,0.98016,bull
2018.06.11,0.98627,0.98649,0.98647,0.98649,0.98422,0.98444,0.98422,bull

In [12]:
# If Buy or If Sell 
PositionBuy_TP1011 = summaryTable03 ['High 10To11'] - summaryTable03 ['C09']
PositionBuy_TP1011_pd = pd.DataFrame (PositionBuy_TP1011, columns = ['If Buy Pos'])

PositionSell_TP1011 = summaryTable03 ['C09'] - summaryTable03 ['Low 10To11']
PositionSell_TP1011_pd = pd.DataFrame (PositionSell_TP1011, columns = ['If Sell Pos'])

summaryTable04 = pd.concat([PositionBuy_TP1011_pd, PositionSell_TP1011_pd, tableBlBr], axis=1)
summaryTable04

            If Buy Pos  If Sell Pos Bull/Bear
Date
2015.05.19         NaN          NaN      bear
2015.05.20     0.00140      0.00320      bull
2015.05.21     0.00010      0.00530      bear
2015.05.22     0.00090      0.00190      bear
2015.05.25     0.00330      0.00030      bear
2015.05.26     0.00110      0.00200      bull
2015.05.27     0.00210      0.00010      bear
2015.05.28     0.00200      0.00110      bear
2015.05.29     0.00050      0.00500      bull
2015.06.01     0.00270      0.00080      bull
2015.06.02     0.00250      0.00120      bear
2015.06.03     0.00310      0.00000      bear
2015.06.04     0.00140      0.00790      bull
2015.06.05     0.00080      0.00250      bear
2015.06.08     0.00080      0.00310      bear
2015.06.09     0.00250      0.00260      bear
2015.06.10     0.00040      0.00460      bear
2015.06.11     0.00590      0.00010      bear
2015.06.12     0.00500      0.00170      bull
2015.06.15     0.00180      0.00160      bull
2015.06.16     0.00380      0.00050      bear
2015.06.17     0.00020      0.00640      bear
2015.06.18     0.00090      0.00580      bear
2015.06.19     0.00170      0.00030      bull
2015.06.22     0.00460      0.00090      bear
2015.06.23     0.00300      0.00120      bull
2015.06.24     0.00150      0.00330      bear
2015.06.25     0.00180      0.00270      bull
2015.06.26     0.00050      0.00430      bear
2015.06.29     0.00770      0.00040      bear
...                ...          ...       ...
2018.05.01     0.00212      0.00025      bull
2018.05.02     0.00048      0.00150      bear
2018.05.03     0.00116      0.00133      bear
2018.05.04     0.00067      0.00104      bull
2018.05.07     0.00224      0.00041      bull
2018.05.08     0.00147      0.00107      bull
2018.05.09     0.00092      0.00077      bull
2018.05.10     0.00086      0.00058      bear
2018.05.11     0.00023      0.00205      bull
2018.05.14     0.00010      0.00211      bull
2018.05.15     0.00056      0.00135      bull
2018.05.16     0.00141      0.00042      bear
2018.05.17     0.00136      0.00073      bear
2018.05.18     0.00076      0.00079      bear
2018.05.21     0.00052      0.00107      bull
2018.05.22     0.00055      0.00404      bull
2018.05.23     0.00187      0.00141      bear
2018.05.24     0.00006      0.00238      bear
2018.05.25     0.00112      0.00033      bull
2018.05.28     0.00097      0.00017      bear
2018.05.29     0.00004      0.00176      bull
2018.05.30     0.00048      0.00313      bull
2018.05.31     0.00064      0.00163      bear
2018.06.01     0.00006      0.00274      bull
2018.06.04     0.00033      0.00285      bear
2018.06.05     0.00089      0.00149      bear
2018.06.06     0.00076      0.00127      bull
2018.06.07     0.00036      0.00263      bear
2018.06.08     0.00164      0.00071      bull
2018.06.11     0.00022      0.00205      bull

[796 rows x 3 columns]

In [14]:
tableForBuyEntry_1011_pd = summaryTable04[(summaryTable04['Bull/Bear'] == 'bull')]
tableForSellEntry_1011_pd = summaryTable04[(summaryTable04['Bull/Bear'] == 'bear')]
tableForSellEntry_1011_pd

            If Buy Pos  If Sell Pos Bull/Bear
Date
2015.05.19         NaN          NaN      bear
2015.05.21     0.00010      0.00530      bear
2015.05.22     0.00090      0.00190      bear
2015.05.25     0.00330      0.00030      bear
2015.05.27     0.00210      0.00010      bear
2015.05.28     0.00200      0.00110      bear
2015.06.02     0.00250      0.00120      bear
2015.06.03     0.00310      0.00000      bear
2015.06.05     0.00080      0.00250      bear
2015.06.08     0.00080      0.00310      bear
2015.06.09     0.00250      0.00260      bear
2015.06.10     0.00040      0.00460      bear
2015.06.11     0.00590      0.00010      bear
2015.06.16     0.00380      0.00050      bear
2015.06.17     0.00020      0.00640      bear
2015.06.18     0.00090      0.00580      bear
2015.06.22     0.00460      0.00090      bear
2015.06.24     0.00150      0.00330      bear
2015.06.26     0.00050      0.00430      bear
2015.06.29     0.00770      0.00040      bear
2015.07.02     0.00410      0.00020      bear
2015.07.03     0.00060      0.00130      bear
2015.07.06     0.00100      0.00160      bear
2015.07.08     0.00080      0.00260      bear
2015.07.09     0.00610      0.00000      bear
2015.07.10     0.00120      0.00830      bear
2015.07.13     0.01170      0.00010      bear
2015.07.17     0.00110      0.00100      bear
2015.07.21     0.00080      0.00250      bear
2015.07.22     0.00260     -0.00010      bear
...                ...          ...       ...
2018.03.02     0.00069      0.00300      bear
2018.03.08     0.00262      0.00001      bear
2018.03.12     0.00043      0.00101      bear
2018.03.16     0.00064      0.00114      bear
2018.03.20     0.00125      0.00063      bear
2018.03.21     0.00034      0.00295      bear
2018.03.22     0.00180      0.00052      bear
2018.03.23     0.00057      0.00108      bear
2018.03.27     0.00263      0.00075      bear
2018.03.30     0.00104      0.00029      bear
2018.04.03     0.00118      0.00059      bear
2018.04.06     0.00113      0.00030      bear
2018.04.11     0.00311      0.00073      bear
2018.04.17     0.00228      0.00098      bear
2018.04.19     0.00110      0.00120      bear
2018.04.26     0.00177      0.00105      bear
2018.04.30     0.00210      0.00020      bear
2018.05.02     0.00048      0.00150      bear
2018.05.03     0.00116      0.00133      bear
2018.05.10     0.00086      0.00058      bear
2018.05.16     0.00141      0.00042      bear
2018.05.17     0.00136      0.00073      bear
2018.05.18     0.00076      0.00079      bear
2018.05.23     0.00187      0.00141      bear
2018.05.24     0.00006      0.00238      bear
2018.05.28     0.00097      0.00017      bear
2018.05.31     0.00064      0.00163      bear
2018.06.04     0.00033      0.00285      bear
2018.06.05     0.00089      0.00149      bear
2018.06.07     0.00036      0.00263      bear

[377 rows x 3 columns]

In [36]:
# For buy position result
BuyPosSubResult_1011 = np.where (tableForBuyEntry_1011_pd ['If Buy Pos'] > 0.0006, 'Success', 'Fail')
BuyPosSubResult_1011_pd = pd.DataFrame (BuyPosSubResult_1011, columns = ['Buy Result'])
BuyPosSubResult_1011_pd  

# Convert To Numpy 
BuyPosSubResult_1011_np = BuyPosSubResult_1011_pd.values
BuyPosSubResult_1011_pd

# Count Contents
countTotalResultForBuy_1011 = len(BuyPosSubResult_1011_np)
countSuccessResultBuy_1011 = (BuyPosSubResult_1011_np == 'Success').sum() 

WinRateForBuyPos_1011 = countSuccessResultBuy_1011 / countTotalResultForBuy_1011
WinRateForBuyPos_1011

0.6587112171837709

In [37]:
# FOR SELL POSITION RESULT
SellPosSubResult_1011 = np.where (tableForBuyEntry_1011_pd ['If Sell Pos'] > 0.00060, 'Success', 'Fail')
SellPosSubResult_1011_pd = pd.DataFrame (SellPosSubResult_1011, columns = ['Sell Result'])
SellPosSubResult_1011_pd  

# Convert To Numpy 
SellPosSubResult_1011_np = SellPosSubResult_1011_pd.values
SellPosSubResult_1011_pd

# Count Contents
countTotalResultForSell_1011 = len(SellPosSubResult_1011_np)
countSuccessResultSell_1011 = (SellPosSubResult_1011_np == 'Success').sum() 

WinRateForSellPos_1011 = countSuccessResultSell_1011 / countTotalResultForSell_1011
WinRateForSellPos_1011

0.7350835322195705