In [1]:
# This is a price analysis for USD/CHF whether there is a correlation of prize movement in days. 
# Conclusion: There's none. The highest is on Monday where it is up by 57%. The rest shows almost random correlation.
import pandas as pd
import numpy as np

In [2]:
mDataFullUsdChf_pd = pd.read_csv('UsdChfD1Clean101.csv')

In [3]:
mDataFullUsdChf_pd

            Date     na     Open     High      Low    Close  Volume
0     2014.11.16  00:00  0.95859  0.95991  0.95788  0.95923    2152
1     2014.11.17  00:00  0.95924  0.96539  0.95517  0.96481   47761
2     2014.11.18  00:00  0.96475  0.96489  0.95740  0.95850   29295
3     2014.11.19  00:00  0.95849  0.96003  0.95295  0.95790   46385
4     2014.11.20  00:00  0.95789  0.96053  0.95524  0.95838   66955
5     2014.11.21  00:00  0.95841  0.97085  0.95624  0.96952   66246
6     2014.11.23  00:00  0.97218  0.97295  0.97139  0.97164    2892
7     2014.11.24  00:00  0.97159  0.97201  0.96621  0.96705   50602
8     2014.11.25  00:00  0.96704  0.96971  0.96341  0.96353   30614
9     2014.11.26  00:00  0.96349  0.96652  0.95942  0.96122   35890
10    2014.11.27  00:00  0.96122  0.96488  0.95980  0.96460   42169
11    2014.11.28  00:00  0.96459  0.96699  0.96208  0.96463   46873
12    2014.11.30  00:00  0.96501  0.96815  0.96479  0.96774    3097
13    2014.12.01  00:00  0.96774  0.96871  0.96145  0.96456   59811
14    2014.12.02  00:00  0.96457  0.97292  0.96409  0.97188   47414
15    2014.12.03  00:00  0.97189  0.97824  0.97140  0.97721   53788
16    2014.12.04  00:00  0.97721  0.97939  0.96485  0.97070   66228
17    2014.12.05  00:00  0.97069  0.97991  0.97015  0.97863   54722
18    2014.12.07  00:00  0.97883  0.97927  0.97747  0.97837    2208
19    2014.12.08  00:00  0.97840  0.98172  0.97375  0.97624   52422
20    2014.12.09  00:00  0.97624  0.97772  0.96531  0.97043   68448
21    2014.12.10  00:00  0.97044  0.97217  0.96375  0.96398   64670
22    2014.12.11  00:00  0.96397  0.97101  0.96269  0.96918   68541
23    2014.12.12  00:00  0.96919  0.96987  0.96181  0.96371   64298
24    2014.12.14  00:00  0.96304  0.96414  0.96175  0.96373    3817
25    2014.12.15  00:00  0.96374  0.96734  0.96236  0.96540   65906
26    2014.12.16  00:00  0.96541  0.96562  0.95527  0.95979   81888
27    2014.12.17  00:00  0.95979  0.97443  0.95940  0.97334   79252
28    2014.12.18  00:00  0.97335  0.98471  0.97211  0.97983   74550
29    2014.12.19  00:00  0.97984  0.98455  0.97838  0.98348   51902
...          ...    ...      ...      ...      ...      ...     ...
1005  2018.01.31  00:00  0.93459  0.93583  0.92887  0.93126   53039
1006  2018.02.01  00:00  0.93125  0.93410  0.92554  0.92596   50556
1007  2018.02.02  00:00  0.92597  0.93357  0.92575  0.93087   51698
1008  2018.02.04  00:00  0.93201  0.93268  0.93075  0.93120    3470
1009  2018.02.05  00:00  0.93121  0.93756  0.92866  0.93130   53018
1010  2018.02.06  00:00  0.93129  0.93971  0.93059  0.93611   69602
1011  2018.02.07  00:00  0.93611  0.94536  0.93393  0.94247   51687
1012  2018.02.08  00:00  0.94247  0.94691  0.93476  0.93507   59909
1013  2018.02.09  00:00  0.93507  0.94080  0.93507  0.93934   55884
1014  2018.02.11  00:00  0.93955  0.94033  0.93910  0.93963    2122
1015  2018.02.12  00:00  0.93963  0.94008  0.93629  0.93873   37930
1016  2018.02.13  00:00  0.93874  0.93978  0.93218  0.93524   38584
1017  2018.02.14  00:00  0.93524  0.93734  0.92720  0.92747   48461
1018  2018.02.15  00:00  0.92748  0.92905  0.92095  0.92220   45563
1019  2018.02.16  00:00  0.92219  0.92868  0.91870  0.92732   42314
1020  2018.02.18  00:00  0.92724  0.92784  0.92633  0.92721    1462
1021  2018.02.19  00:00  0.92720  0.93191  0.92622  0.92930   32211
1022  2018.02.20  00:00  0.92931  0.93685  0.92889  0.93621   37329
1023  2018.02.21  00:00  0.93624  0.93959  0.93423  0.93866   42810
1024  2018.02.22  00:00  0.93868  0.94083  0.93215  0.93313   38470
1025  2018.02.23  00:00  0.93312  0.93733  0.93271  0.93595   33139
1026  2018.02.25  00:00  0.93620  0.93732  0.93548  0.93712    2199
1027  2018.02.26  00:00  0.93713  0.93904  0.93249  0.93861   34404
1028  2018.02.27  00:00  0.93862  0.94165  0.93576  0.93943   40839
1029  2018.02.28  00:00  0.93944  0.94576  0.93870  0.94443   40254
1030  2018.03.01  00:00  0.94444  0.94897  0.94095  0.94144   60266
1031  2018.03.02  00:00  0.94142  0.94238  0.93378  0.93708   69123
1032  2018.03.04  00:00  0.93463  0.93787  0.93452  0.93706    4385
1033  2018.03.05  00:00  0.93706  0.94075  0.93525  0.93975   67828
1034  2018.03.06  00:00  0.93976  0.94182  0.93591  0.93796   44379

[1035 rows x 7 columns]

In [4]:
# Gets the column data dates and assign weekdays representing 1-5 as mon - fri respectively
mDataPrice_pd = mDataFullUsdChf_pd.loc [0:]
mDataPrice_pd

            Date     na     Open     High      Low    Close  Volume
0     2014.11.16  00:00  0.95859  0.95991  0.95788  0.95923    2152
1     2014.11.17  00:00  0.95924  0.96539  0.95517  0.96481   47761
2     2014.11.18  00:00  0.96475  0.96489  0.95740  0.95850   29295
3     2014.11.19  00:00  0.95849  0.96003  0.95295  0.95790   46385
4     2014.11.20  00:00  0.95789  0.96053  0.95524  0.95838   66955
5     2014.11.21  00:00  0.95841  0.97085  0.95624  0.96952   66246
6     2014.11.23  00:00  0.97218  0.97295  0.97139  0.97164    2892
7     2014.11.24  00:00  0.97159  0.97201  0.96621  0.96705   50602
8     2014.11.25  00:00  0.96704  0.96971  0.96341  0.96353   30614
9     2014.11.26  00:00  0.96349  0.96652  0.95942  0.96122   35890
10    2014.11.27  00:00  0.96122  0.96488  0.95980  0.96460   42169
11    2014.11.28  00:00  0.96459  0.96699  0.96208  0.96463   46873
12    2014.11.30  00:00  0.96501  0.96815  0.96479  0.96774    3097
13    2014.12.01  00:00  0.96774  0.96871  0.96145  0.96456   59811
14    2014.12.02  00:00  0.96457  0.97292  0.96409  0.97188   47414
15    2014.12.03  00:00  0.97189  0.97824  0.97140  0.97721   53788
16    2014.12.04  00:00  0.97721  0.97939  0.96485  0.97070   66228
17    2014.12.05  00:00  0.97069  0.97991  0.97015  0.97863   54722
18    2014.12.07  00:00  0.97883  0.97927  0.97747  0.97837    2208
19    2014.12.08  00:00  0.97840  0.98172  0.97375  0.97624   52422
20    2014.12.09  00:00  0.97624  0.97772  0.96531  0.97043   68448
21    2014.12.10  00:00  0.97044  0.97217  0.96375  0.96398   64670
22    2014.12.11  00:00  0.96397  0.97101  0.96269  0.96918   68541
23    2014.12.12  00:00  0.96919  0.96987  0.96181  0.96371   64298
24    2014.12.14  00:00  0.96304  0.96414  0.96175  0.96373    3817
25    2014.12.15  00:00  0.96374  0.96734  0.96236  0.96540   65906
26    2014.12.16  00:00  0.96541  0.96562  0.95527  0.95979   81888
27    2014.12.17  00:00  0.95979  0.97443  0.95940  0.97334   79252
28    2014.12.18  00:00  0.97335  0.98471  0.97211  0.97983   74550
29    2014.12.19  00:00  0.97984  0.98455  0.97838  0.98348   51902
...          ...    ...      ...      ...      ...      ...     ...
1005  2018.01.31  00:00  0.93459  0.93583  0.92887  0.93126   53039
1006  2018.02.01  00:00  0.93125  0.93410  0.92554  0.92596   50556
1007  2018.02.02  00:00  0.92597  0.93357  0.92575  0.93087   51698
1008  2018.02.04  00:00  0.93201  0.93268  0.93075  0.93120    3470
1009  2018.02.05  00:00  0.93121  0.93756  0.92866  0.93130   53018
1010  2018.02.06  00:00  0.93129  0.93971  0.93059  0.93611   69602
1011  2018.02.07  00:00  0.93611  0.94536  0.93393  0.94247   51687
1012  2018.02.08  00:00  0.94247  0.94691  0.93476  0.93507   59909
1013  2018.02.09  00:00  0.93507  0.94080  0.93507  0.93934   55884
1014  2018.02.11  00:00  0.93955  0.94033  0.93910  0.93963    2122
1015  2018.02.12  00:00  0.93963  0.94008  0.93629  0.93873   37930
1016  2018.02.13  00:00  0.93874  0.93978  0.93218  0.93524   38584
1017  2018.02.14  00:00  0.93524  0.93734  0.92720  0.92747   48461
1018  2018.02.15  00:00  0.92748  0.92905  0.92095  0.92220   45563
1019  2018.02.16  00:00  0.92219  0.92868  0.91870  0.92732   42314
1020  2018.02.18  00:00  0.92724  0.92784  0.92633  0.92721    1462
1021  2018.02.19  00:00  0.92720  0.93191  0.92622  0.92930   32211
1022  2018.02.20  00:00  0.92931  0.93685  0.92889  0.93621   37329
1023  2018.02.21  00:00  0.93624  0.93959  0.93423  0.93866   42810
1024  2018.02.22  00:00  0.93868  0.94083  0.93215  0.93313   38470
1025  2018.02.23  00:00  0.93312  0.93733  0.93271  0.93595   33139
1026  2018.02.25  00:00  0.93620  0.93732  0.93548  0.93712    2199
1027  2018.02.26  00:00  0.93713  0.93904  0.93249  0.93861   34404
1028  2018.02.27  00:00  0.93862  0.94165  0.93576  0.93943   40839
1029  2018.02.28  00:00  0.93944  0.94576  0.93870  0.94443   40254
1030  2018.03.01  00:00  0.94444  0.94897  0.94095  0.94144   60266
1031  2018.03.02  00:00  0.94142  0.94238  0.93378  0.93708   69123
1032  2018.03.04  00:00  0.93463  0.93787  0.93452  0.93706    4385
1033  2018.03.05  00:00  0.93706  0.94075  0.93525  0.93975   67828
1034  2018.03.06  00:00  0.93976  0.94182  0.93591  0.93796   44379

[1035 rows x 7 columns]

In [6]:
daysAsNum_test5

[1, 2, 3, 4, 5]

In [7]:
1024 / 6

170

In [9]:
daysAsNum = [0, 1, 2, 3, 4, 5]
daysAsNum = daysAsNum * 175
print(daysAsNum)

[0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5]

In [10]:
#Renaming Columns
daysAsNum_pd = pd.DataFrame(daysAsNum, columns = ['Day'])

In [11]:
rShapeData1_pd = mDataPrice_pd.join(daysAsNum_pd)
rShapeData1_pd

            Date     na     Open     High      Low    Close  Volume  Day
0     2014.11.16  00:00  0.95859  0.95991  0.95788  0.95923    2152    0
1     2014.11.17  00:00  0.95924  0.96539  0.95517  0.96481   47761    1
2     2014.11.18  00:00  0.96475  0.96489  0.95740  0.95850   29295    2
3     2014.11.19  00:00  0.95849  0.96003  0.95295  0.95790   46385    3
4     2014.11.20  00:00  0.95789  0.96053  0.95524  0.95838   66955    4
5     2014.11.21  00:00  0.95841  0.97085  0.95624  0.96952   66246    5
6     2014.11.23  00:00  0.97218  0.97295  0.97139  0.97164    2892    0
7     2014.11.24  00:00  0.97159  0.97201  0.96621  0.96705   50602    1
8     2014.11.25  00:00  0.96704  0.96971  0.96341  0.96353   30614    2
9     2014.11.26  00:00  0.96349  0.96652  0.95942  0.96122   35890    3
10    2014.11.27  00:00  0.96122  0.96488  0.95980  0.96460   42169    4
11    2014.11.28  00:00  0.96459  0.96699  0.96208  0.96463   46873    5
12    2014.11.30  00:00  0.96501  0.96815  0.96479  0.96774    3097    0
13    2014.12.01  00:00  0.96774  0.96871  0.96145  0.96456   59811    1
14    2014.12.02  00:00  0.96457  0.97292  0.96409  0.97188   47414    2
15    2014.12.03  00:00  0.97189  0.97824  0.97140  0.97721   53788    3
16    2014.12.04  00:00  0.97721  0.97939  0.96485  0.97070   66228    4
17    2014.12.05  00:00  0.97069  0.97991  0.97015  0.97863   54722    5
18    2014.12.07  00:00  0.97883  0.97927  0.97747  0.97837    2208    0
19    2014.12.08  00:00  0.97840  0.98172  0.97375  0.97624   52422    1
20    2014.12.09  00:00  0.97624  0.97772  0.96531  0.97043   68448    2
21    2014.12.10  00:00  0.97044  0.97217  0.96375  0.96398   64670    3
22    2014.12.11  00:00  0.96397  0.97101  0.96269  0.96918   68541    4
23    2014.12.12  00:00  0.96919  0.96987  0.96181  0.96371   64298    5
24    2014.12.14  00:00  0.96304  0.96414  0.96175  0.96373    3817    0
25    2014.12.15  00:00  0.96374  0.96734  0.96236  0.96540   65906    1
26    2014.12.16  00:00  0.96541  0.96562  0.95527  0.95979   81888    2
27    2014.12.17  00:00  0.95979  0.97443  0.95940  0.97334   79252    3
28    2014.12.18  00:00  0.97335  0.98471  0.97211  0.97983   74550    4
29    2014.12.19  00:00  0.97984  0.98455  0.97838  0.98348   51902    5
...          ...    ...      ...      ...      ...      ...     ...  ...
1005  2018.01.31  00:00  0.93459  0.93583  0.92887  0.93126   53039    3
1006  2018.02.01  00:00  0.93125  0.93410  0.92554  0.92596   50556    4
1007  2018.02.02  00:00  0.92597  0.93357  0.92575  0.93087   51698    5
1008  2018.02.04  00:00  0.93201  0.93268  0.93075  0.93120    3470    0
1009  2018.02.05  00:00  0.93121  0.93756  0.92866  0.93130   53018    1
1010  2018.02.06  00:00  0.93129  0.93971  0.93059  0.93611   69602    2
1011  2018.02.07  00:00  0.93611  0.94536  0.93393  0.94247   51687    3
1012  2018.02.08  00:00  0.94247  0.94691  0.93476  0.93507   59909    4
1013  2018.02.09  00:00  0.93507  0.94080  0.93507  0.93934   55884    5
1014  2018.02.11  00:00  0.93955  0.94033  0.93910  0.93963    2122    0
1015  2018.02.12  00:00  0.93963  0.94008  0.93629  0.93873   37930    1
1016  2018.02.13  00:00  0.93874  0.93978  0.93218  0.93524   38584    2
1017  2018.02.14  00:00  0.93524  0.93734  0.92720  0.92747   48461    3
1018  2018.02.15  00:00  0.92748  0.92905  0.92095  0.92220   45563    4
1019  2018.02.16  00:00  0.92219  0.92868  0.91870  0.92732   42314    5
1020  2018.02.18  00:00  0.92724  0.92784  0.92633  0.92721    1462    0
1021  2018.02.19  00:00  0.92720  0.93191  0.92622  0.92930   32211    1
1022  2018.02.20  00:00  0.92931  0.93685  0.92889  0.93621   37329    2
1023  2018.02.21  00:00  0.93624  0.93959  0.93423  0.93866   42810    3
1024  2018.02.22  00:00  0.93868  0.94083  0.93215  0.93313   38470    4
1025  2018.02.23  00:00  0.93312  0.93733  0.93271  0.93595   33139    5
1026  2018.02.25  00:00  0.93620  0.93732  0.93548  0.93712    2199    0
1027  2018.02.26  00:00  0.93713  0.93904  0.93249  0.93861   34404    1
1028  2018.02.27  00:00  0.93862  0.94165  0.93576  0.93943   40839    2
1029  2018.02.28  00:00  0.93944  0.94576  0.93870  0.94443   40254    3
1030  2018.03.01  00:00  0.94444  0.94897  0.94095  0.94144   60266    4
1031  2018.03.02  00:00  0.94142  0.94238  0.93378  0.93708   69123    5
1032  2018.03.04  00:00  0.93463  0.93787  0.93452  0.93706    4385    0
1033  2018.03.05  00:00  0.93706  0.94075  0.93525  0.93975   67828    1
1034  2018.03.06  00:00  0.93976  0.94182  0.93591  0.93796   44379    2

[1035 rows x 8 columns]

In [12]:
rShapeData1_pd ['UpOrDown'] = rShapeData1_pd ['Close'] - rShapeData1_pd ['Open']

In [13]:
rShapeData1_pd

,Date,na,Open,High,Low,Close,Volume,Day,UpOrDown
0,2014.11.16,00:00,0.95859,0.95991,0.95788,0.95923,2152,0,0.00064
1,2014.11.17,00:00,0.95924,0.96539,0.95517,0.96481,47761,1,0.00557
2,2014.11.18,00:00,0.96475,0.96489,0.95740,0.95850,29295,2,-0.00625
3,2014.11.19,00:00,0.95849,0.96003,0.95295,0.95790,46385,3,-0.00059
4,2014.11.20,00:00,0.95789,0.96053,0.95524,0.95838,66955,4,0.00049
5,2014.11.21,00:00,0.95841,0.97085,0.95624,0.96952,66246,5,0.01111
6,2014.11.23,00:00,0.97218,0.97295,0.97139,0.97164,2892,0,-0.00054
7,2014.11.24,00:00,0.97159,0.97201,0.96621,0.96705,50602,1,-0.00454
8,2014.11.25,00:00,0.96704,0.96971,0.96341,0.96353,30614,2,-0.00351
9,2014.11.26,00:00,0.96349,0.96652,0.95942,0.96122,35890,3,-0.00227
10,2014.11.27,00:00,0.96122,0.96488,0.95980,0.96460,42169,4,0.00338
11,2014.11.28,00:00,0.96459,0.96699,0.96208,0.96463,46873,5,0.00004
12,2014.11.30,00:00,0.96501,0.96815,0.96479,0.96774,3097,0,0.00273
13,2014.12.01,00:00,0.96774,0.96871,0.96145,0.96456,59811,1,-0.00318
14,2014.12.02,00:00,0.96457,0.97292,0.96409,0.97188,47414,2,0.00731
15,2014.12.03,00:00,0.97189,0.97824,0.97140,0.97721,53788,3,0.00532
16,2014.12.04,00:00,0.97721,0.97939,0.96485,0.97070,66228,4,-0.00651
17,2014.12.05,00:00,0.97069,0.97991,0.97015,0.97863,54722,5,0.00794
18,2014.12.07,00:00,0.97883,0.97927,0.97747,0.97837,2208,0,-0.00046
19,2014.12.08,00:00,0.97840,0.98172,0.97375,0.97624,52422,1,-0.00216
20,2014.12.09,00:00,0.97624,0.97772,0.96531,0.97043,68448,2,-0.00581
21,2014.12.10,00:00,0.97044,0.97217,0.96375,0.96398,64670,3,-0.00646
22,2014.12.11,00:00,0.96397,0.97101,0.96269,0.96918,68541,4,0.00521
23,2014.12.12,00:00,0.96919,0.96987,0.96181,0.96371,64298,5,-0.00548
24,2014.12.14,00:00,0.96304,0.96414,0.96175,0.96373,3817,0,0.00069
25,2014.12.15,00:00,0.96374,0.96734,0.96236,0.96540,65906,1,0.00166
26,2014.12.16,00:00,0.96541,0.96562,0.95527,0.95979,81888,2,-0.00562
27,2014.12.17,00:00,0.95979,0.97443,0.95940,0.97334,79252,3,0.01355
28,2014.12.18,00:00,0.97335,0.98471,0.97211,0.97983,74550,4,0.00648
29,2014.12.19,00:00,0.97984,0.98455,0.97838,0.98348,51902,5,0.00364
...,...,...,...,...,...,...,...,...,...
1005,2018.01.31,00:00,0.93459,0.93583,0.92887,0.93126,53039,3,-0.00333
1006,2018.02.01,00:00,0.93125,0.93410,0.92554,0.92596,50556,4,-0.00529
1007,2018.02.02,00:00,0.92597,0.93357,0.92575,0.93087,51698,5,0.00490
1008,2018.02.04,00:00,0.93201,0.93268,0.93075,0.93120,3470,0,-0.00081
1009,2018.02.05,00:00,0.93121,0.93756,0.92866,0.93130,53018,1,0.00009
1010,2018.02.06,00:00,0.93129,0.93971,0.93059,0.93611,69602,2,0.00482
1011,2018.02.07,00:00,0.93611,0.94536,0.93393,0.94247,51687,3,0.00636
1012,2018.02.08,00:00,0.94247,0.94691,0.93476,0.93507,59909,4,-0.00740
1013,2018.02.09,00:00,0.93507,0.94080,0.93507,0.93934,55884,5,0.00427
1014,2018.02.11,00:00,0.93955,0.94033,0.93910,0.93963,2122,0,0.00008
1015,2018.02.12,00:00,0.93963,0.94008,0.93629,0.93873,37930,1,-0.00090
1016,2018.02.13,00:00,0.93874,0.93978,0.93218,0.93524,38584,2,-0.00350
1017,2018.02.14,00:00,0.93524,0.93734,0.92720,0.92747,48461,3,-0.00777
1018,2018.02.15,00:00,0.92748,0.92905,0.92095,0.92220,45563,4,-0.00528
1019,2018.02.16,00:00,0.92219,0.92868,0.91870,0.92732,42314,5,0.00513
1020,2018.02.18,00:00,0.92724,0.92784,0.92633,0.92721,1462,0,-0.00003
1021,2018.02.19,00:00,0.92720,0.93191,0.92622,0.92930,32211,1,0.00210
1022,2018.02.20,00:00,0.92931,0.93685,0.92889,0.93621,37329,2,0.00690
1023,2018.02.21,00:00,0.93624,0.93959,0.93423,0.93866,42810,3,0.00242
1024,2018.02.22,00:00,0.93868,0.94083,0.93215,0.93313,38470,4,-0.00555
1025,2018.02.23,00:00,0.93312,0.93733,0.93271,0.93595,33139,5,0.00283
1026,2018.02.25,00:00,0.93620,0.93732,0.93548,0.93712,2199,0,0.00092
1027,2018.02.26,00:00,0.93713,0.93904,0.93249,0.93861,34404,1,0.00148
1028,2018.02.27,00:00,0.93862,0.94165,0.93576,0.93943,40839,2,0.00081
1029,2018.02.28,00:00,0.93944,0.94576,0.93870,0.94443,40254,3,0.00499
1030,2018.03.01,00:00,0.94444,0.94897,0.94095,0.94144,60266,4,-0.00300
1031,2018.03.02,00:00,0.94142,0.94238,0.93378,0.93708,69123,5,-0.00434
1032,2018.03.04,00:00,0.93463,0.93787,0.93452,0.93706,4385,0,0.00243
1033,2018.03.05,00:00,0.93706,0.94075,0.93525,0.93975,67828,1,0.00269
1034,2018.03.06,00:00,0.93976,0.94182,0.93591,0.93796,44379,2,-0.00180

In [40]:
rShapeData1_pd[(rShapeData1_pd['Day'] == 5) & (rShapeData1_pd['UpOrDown'] > 0)]

,Date,na,Open,High,Low,Close,Volume,Day,UpOrDown
5,2014.11.21,00:00,0.95841,0.97085,0.95624,0.96952,66246,5,0.01111
11,2014.11.28,00:00,0.96459,0.96699,0.96208,0.96463,46873,5,0.00004
17,2014.12.05,00:00,0.97069,0.97991,0.97015,0.97863,54722,5,0.00794
29,2014.12.19,00:00,0.97984,0.98455,0.97838,0.98348,51902,5,0.00364
35,2014.12.26,00:00,0.98500,0.98834,0.98358,0.98712,25282,5,0.00212
41,2015.01.02,00:00,0.99404,1.00164,0.99363,1.00124,49238,5,0.00720
53,2015.01.16,00:00,0.85384,0.88074,0.84512,0.85710,50875,5,0.00326
59,2015.01.23,00:00,0.87143,0.88179,0.86771,0.87961,59137,5,0.00818
71,2015.02.06,00:00,0.92202,0.92870,0.91749,0.92554,44301,5,0.00352
77,2015.02.13,00:00,0.93000,0.93349,0.92683,0.93137,35462,5,0.00137
89,2015.02.27,00:00,0.95266,0.95452,0.94498,0.95375,43044,5,0.00109
95,2015.03.06,00:00,0.97377,0.98641,0.97211,0.98582,31929,5,0.01205
101,2015.03.13,00:00,1.00264,1.01108,1.00256,1.00565,28157,5,0.00301
125,2015.04.10,00:00,0.97700,0.98358,0.97503,0.97898,22324,5,0.00198
149,2015.05.08,00:00,0.92168,0.93227,0.92002,0.93106,35241,5,0.00938
155,2015.05.15,00:00,0.91248,0.92546,0.91141,0.91535,39111,5,0.00287
161,2015.05.22,00:00,0.93757,0.94558,0.92860,0.94247,35840,5,0.00490
173,2015.06.05,00:00,0.93489,0.95012,0.92971,0.93890,70392,5,0.00401
209,2015.07.17,00:00,0.95726,0.96182,0.95566,0.96108,44543,5,0.00382
215,2015.07.24,00:00,0.95938,0.96350,0.95732,0.96199,42872,5,0.00261
227,2015.08.07,00:00,0.98105,0.98833,0.97879,0.98237,48482,5,0.00132
233,2015.08.14,00:00,0.97544,0.97859,0.97269,0.97565,41147,5,0.00021
263,2015.09.18,00:00,0.96197,0.97043,0.95269,0.96790,63978,5,0.00593
269,2015.09.25,00:00,0.97814,0.98427,0.97429,0.97839,60553,5,0.00025
287,2015.10.16,00:00,0.95149,0.95529,0.94962,0.95330,42705,5,0.00181
293,2015.10.23,00:00,0.97364,0.98001,0.97111,0.97812,46844,5,0.00448
305,2015.11.06,00:00,0.99517,1.00757,0.99431,1.00505,63536,5,0.00988
311,2015.11.13,00:00,1.00078,1.00940,0.99982,1.00548,62837,5,0.00470
317,2015.11.20,00:00,1.01354,1.01973,1.01214,1.01766,41253,5,0.00412
323,2015.11.27,00:00,1.02352,1.03276,1.02251,1.02924,55608,5,0.00572
...,...,...,...,...,...,...,...,...,...
629,2016.11.18,00:00,1.00746,1.01221,1.00597,1.00997,72531,5,0.00251
647,2016.12.09,00:00,1.01586,1.02128,1.01527,1.01659,54612,5,0.00073
659,2016.12.23,00:00,1.02564,1.02801,1.02427,1.02610,64533,5,0.00046
665,2016.12.30,00:00,1.01707,1.02304,1.01419,1.01823,100587,5,0.00116
671,2017.01.06,00:00,1.00983,1.01832,1.00958,1.01728,52844,5,0.00745
701,2017.02.10,00:00,1.00146,1.00615,1.00091,1.00216,42167,5,0.00070
707,2017.02.17,00:00,0.99716,1.00329,0.99691,1.00249,46559,5,0.00533
713,2017.02.24,00:00,1.00610,1.00802,1.00248,1.00733,44446,5,0.00123
731,2017.03.17,00:00,0.99607,0.99862,0.99417,0.99825,31560,5,0.00218
743,2017.03.31,00:00,1.00028,1.00291,0.99941,1.00272,44886,5,0.00244
749,2017.04.07,00:00,1.00529,1.00956,1.00222,1.00880,39015,5,0.00351
767,2017.04.28,00:00,0.99438,0.99574,0.98930,0.99474,30536,5,0.00036
773,2017.05.05,00:00,0.98606,0.99020,0.98582,0.98672,39839,5,0.00066
791,2017.05.26,00:00,0.97311,0.97603,0.96958,0.97408,35209,5,0.00097
803,2017.06.09,00:00,0.96899,0.97266,0.96746,0.96900,47069,5,0.00001
821,2017.06.30,00:00,0.95547,0.95975,0.95533,0.95781,35519,5,0.00234
827,2017.07.07,00:00,0.96029,0.96534,0.96019,0.96366,32832,5,0.00337
845,2017.07.28,00:00,0.96370,0.97257,0.96341,0.96847,56767,5,0.00477
851,2017.08.04,00:00,0.96767,0.97631,0.96706,0.97254,44992,5,0.00487
863,2017.08.18,00:00,0.96221,0.96689,0.95856,0.96481,46601,5,0.00260
875,2017.09.01,00:00,0.95952,0.96516,0.95453,0.96424,42405,5,0.00472
917,2017.10.20,00:00,0.97618,0.98517,0.97561,0.98416,43588,5,0.00798
929,2017.11.03,00:00,0.99920,1.00236,0.99449,1.00016,40032,5,0.00096
935,2017.11.10,00:00,0.99385,0.99676,0.99246,0.99572,39826,5,0.00187
965,2017.12.15,00:00,0.98893,0.99336,0.98728,0.99039,47051,5,0.00146
995,2018.01.19,00:00,0.95894,0.96413,0.95351,0.96407,42487,5,0.00513
1007,2018.02.02,00:00,0.92597,0.93357,0.92575,0.93087,51698,5,0.00490
1013,2018.02.09,00:00,0.93507,0.94080,0.93507,0.93934,55884,5,0.00427
1019,2018.02.16,00:00,0.92219,0.92868,0.91870,0.92732,42314,5,0.00513
1025,2018.02.23,00:00,0.93312,0.93733,0.93271,0.93595,33139,5,0.00283