In [32]:
import pandas as pd
H1FullUsdChf_pd = pd.read_csv('datasets/2018-06-12-UsdChfH1_raw.csv')
H1FullUsdChf_pd

# Rename Columns to: Time, Open, High, Low, Close, Volume
H1FullUsdChf_pd.columns = ['Date', 'Time', 'Open','High','Low','Close', 'Volume']
H1FullUsdChf_pd

# H1FullUsdChf_pd[H1FullUsdChf_pd.Date == 2015.05.19]

T2100UsdChf_pd = H1FullUsdChf_pd [(H1FullUsdChf_pd['Time'] == '21:00')]
T2100UsdChf_pd

T0400UsdChf_pd = H1FullUsdChf_pd [(H1FullUsdChf_pd['Time'] == '04:00')]
T0400UsdChf_pd

             Date   Time     Open     High      Low    Close  Volume
17     2015.05.20  04:00  0.93700  0.93750  0.93640  0.93680    1245
41     2015.05.21  04:00  0.93460  0.93530  0.93440  0.93500    1049
65     2015.05.22  04:00  0.93640  0.93650  0.93570  0.93630    1204
89     2015.05.25  04:00  0.94380  0.94420  0.94320  0.94370    1314
113    2015.05.26  04:00  0.94630  0.94710  0.94580  0.94690    1095
137    2015.05.27  04:00  0.95220  0.95330  0.95150  0.95290    1498
161    2015.05.28  04:00  0.94870  0.94930  0.94760  0.94860    1643
185    2015.05.29  04:00  0.94260  0.94300  0.94210  0.94230    1050
209    2015.06.01  04:00  0.94190  0.94280  0.94160  0.94230    1108
233    2015.06.02  04:00  0.94480  0.94510  0.94460  0.94480     553
257    2015.06.03  04:00  0.93360  0.93370  0.93200  0.93280    1251
281    2015.06.04  04:00  0.93400  0.93500  0.93340  0.93440    1277
305    2015.06.05  04:00  0.93490  0.93580  0.93460  0.93480    1374
329    2015.06.08  04:00  0.94160  0.94160  0.94020  0.94080     945
353    2015.06.09  04:00  0.92750  0.92760  0.92490  0.92630    1494
377    2015.06.10  04:00  0.92970  0.93030  0.92930  0.93010    1123
401    2015.06.11  04:00  0.93190  0.93340  0.93140  0.93330    1279
425    2015.06.12  04:00  0.93300  0.93350  0.93250  0.93250    1288
449    2015.06.15  04:00  0.93100  0.93360  0.93090  0.93320    1180
473    2015.06.16  04:00  0.93040  0.93130  0.92990  0.93050     823
497    2015.06.17  04:00  0.93140  0.93140  0.93040  0.93040     369
521    2015.06.18  04:00  0.92000  0.92080  0.91980  0.92060     842
545    2015.06.19  04:00  0.92020  0.92110  0.91990  0.92090     842
569    2015.06.22  04:00  0.91730  0.91740  0.91590  0.91690     997
593    2015.06.23  04:00  0.92190  0.92270  0.92180  0.92260     809
617    2015.06.24  04:00  0.93380  0.93410  0.93290  0.93350    1078
641    2015.06.25  04:00  0.93340  0.93440  0.93320  0.93400     716
665    2015.06.26  04:00  0.93600  0.93620  0.93530  0.93600     865
689    2015.06.29  04:00  0.93740  0.93910  0.93710  0.93890    1268
713    2015.06.30  04:00  0.92600  0.92700  0.92600  0.92700    1097
...           ...    ...      ...      ...      ...      ...     ...
18362  2018.05.01  04:00  0.99105  0.99156  0.99100  0.99146    1886
18386  2018.05.02  04:00  0.99680  0.99701  0.99566  0.99576    2798
18410  2018.05.03  04:00  0.99842  0.99857  0.99711  0.99749    3664
18434  2018.05.04  04:00  0.99790  0.99807  0.99720  0.99734    2315
18458  2018.05.07  04:00  0.99950  0.99970  0.99891  0.99936    2601
18482  2018.05.08  04:00  1.00192  1.00367  1.00188  1.00281    3128
18506  2018.05.09  04:00  1.00304  1.00437  1.00298  1.00355    4613
18530  2018.05.10  04:00  1.00527  1.00544  1.00413  1.00429    3728
18554  2018.05.11  04:00  1.00233  1.00324  1.00226  1.00300    2565
18578  2018.05.14  04:00  0.99890  0.99934  0.99889  0.99908    2452
18602  2018.05.15  04:00  1.00026  1.00057  1.00017  1.00028    1686
18626  2018.05.16  04:00  1.00094  1.00144  1.00091  1.00093    3645
18650  2018.05.17  04:00  1.00067  1.00096  1.00017  1.00049    1929
18674  2018.05.18  04:00  1.00081  1.00106  1.00062  1.00065    2786
18698  2018.05.21  04:00  0.99954  0.99965  0.99846  0.99851    3359
18722  2018.05.22  04:00  0.99668  0.99722  0.99666  0.99669    2161
18746  2018.05.23  04:00  0.99258  0.99356  0.99193  0.99298    5078
18770  2018.05.24  04:00  0.99431  0.99449  0.99381  0.99433    4659
18794  2018.05.25  04:00  0.99214  0.99284  0.99214  0.99264    4802
18818  2018.05.28  04:00  0.99207  0.99213  0.99127  0.99160    4124
18842  2018.05.29  04:00  0.99330  0.99405  0.99303  0.99326    3452
18866  2018.05.30  04:00  0.99183  0.99205  0.99151  0.99187    4961
18890  2018.05.31  04:00  0.98820  0.98867  0.98820  0.98844    2797
18914  2018.06.01  04:00  0.98518  0.98609  0.98487  0.98604    3199
18938  2018.06.04  04:00  0.98910  0.98935  0.98798  0.98834    3646
18962  2018.06.05  04:00  0.98807  0.98839  0.98789  0.98810    3200
18986  2018.06.06  04:00  0.98387  0.98401  0.98344  0.98382    3579
19010  2018.06.07  04:00  0.98565  0.98570  0.98518  0.98551    2197
19034  2018.06.08  04:00  0.98037  0.98092  0.98034  0.98056    2768
19058  2018.06.11  04:00  0.98462  0.98475  0.98387  0.98427    4257

[795 rows x 7 columns]