In [1]:
# Nostradamus One: NTS Framework for all pairs.
import pandas as pd
import numpy as np

In [2]:
H1_UsdChf_pd = pd.read_csv('datasets/2018-05-02-UsdChfH1.csv')
H1_UsdChf_Reshaped01_pd = H1_UsdChf_pd.drop(H1_UsdChf_pd.columns[[-1, -1]], axis=1)

H1_UsdChf_Reshaped01_pd

# Reset the index
# H1_UsdChf_Reshaped01_pd = H1_UsdChf_Reshaped01_pd.reset_index()
# H1_UsdChf_Reshaped01_pd

             Time     Open     High      Low    Close
2017.11.08  01:00  0.99917  0.99928  0.99862  0.99876
2017.11.08  02:00  0.99876  0.99903  0.99849  0.99885
2017.11.08  03:00  0.99883  0.99892  0.99855  0.99877
2017.11.08  04:00  0.99877  0.99881  0.99839  0.99854
2017.11.08  05:00  0.99854  0.99878  0.99839  0.99875
2017.11.08  06:00  0.99875  0.99965  0.99869  0.99910
2017.11.08  07:00  0.99911  0.99941  0.99835  0.99905
2017.11.08  08:00  0.99900  0.99931  0.99829  0.99867
2017.11.08  09:00  0.99867  0.99918  0.99835  0.99907
2017.11.08  10:00  0.99909  0.99910  0.99830  0.99850
2017.11.08  11:00  0.99851  0.99889  0.99814  0.99866
2017.11.08  12:00  0.99867  0.99952  0.99854  0.99914
2017.11.08  13:00  0.99912  1.00019  0.99866  1.00008
2017.11.08  14:00  1.00010  1.00035  0.99937  0.99972
2017.11.08  15:00  0.99972  1.00017  0.99909  0.99998
2017.11.08  16:00  0.99998  1.00056  0.99875  0.99964
2017.11.08  17:00  0.99965  1.00025  0.99929  0.99994
2017.11.08  18:00  0.99994  1.00039  0.99955  1.00010
2017.11.08  19:00  1.00010  1.00050  0.99979  1.00014
2017.11.08  20:00  1.00012  1.00015  0.99980  0.99989
2017.11.08  21:00  0.99990  1.00031  0.99945  0.99996
2017.11.08  22:00  0.99993  1.00005  0.99937  0.99986
2017.11.08  23:00  0.99986  1.00003  0.99950  0.99978
2017.11.09  00:00  0.99978  1.00047  0.99967  1.00019
2017.11.09  01:00  1.00020  1.00050  0.99947  0.99955
2017.11.09  02:00  0.99958  0.99987  0.99930  0.99980
2017.11.09  03:00  0.99977  0.99997  0.99933  0.99993
2017.11.09  04:00  0.99993  0.99998  0.99898  0.99907
2017.11.09  05:00  0.99906  0.99908  0.99803  0.99851
2017.11.09  06:00  0.99853  0.99870  0.99735  0.99774
...           ...      ...      ...      ...      ...
2018.03.09  14:00  0.95030  0.95101  0.94945  0.95051
2018.03.09  15:00  0.95053  0.95104  0.94907  0.94997
2018.03.09  16:00  0.95000  0.95033  0.94871  0.94920
2018.03.09  17:00  0.94920  0.95016  0.94884  0.94992
2018.03.09  18:00  0.94991  0.95094  0.94964  0.95088
2018.03.09  19:00  0.95088  0.95115  0.95056  0.95076
2018.03.09  20:00  0.95077  0.95143  0.95060  0.95104
2018.03.09  21:00  0.95104  0.95143  0.95103  0.95116
2018.03.11  21:00  0.95033  0.95120  0.94968  0.95102
2018.03.11  22:00  0.95101  0.95133  0.95088  0.95108
2018.03.11  23:00  0.95107  0.95121  0.95073  0.95084
2018.03.12  00:00  0.95085  0.95107  0.95026  0.95055
2018.03.12  01:00  0.95055  0.95102  0.94987  0.95004
2018.03.12  02:00  0.95007  0.95024  0.94976  0.94983
2018.03.12  03:00  0.94984  0.95002  0.94971  0.94981
2018.03.12  04:00  0.94982  0.94991  0.94921  0.94929
2018.03.12  05:00  0.94930  0.95011  0.94928  0.94999
2018.03.12  06:00  0.94997  0.95025  0.94969  0.94980
2018.03.12  07:00  0.94981  0.95018  0.94859  0.94943
2018.03.12  08:00  0.94944  0.94983  0.94845  0.94846
2018.03.12  09:00  0.94849  0.94971  0.94846  0.94969
2018.03.12  10:00  0.94970  0.95000  0.94916  0.94973
2018.03.12  11:00  0.94975  0.95078  0.94962  0.95046
2018.03.12  12:00  0.95043  0.95051  0.94962  0.94977
2018.03.12  13:00  0.94978  0.95014  0.94862  0.94868
2018.03.12  14:00  0.94872  0.94986  0.94782  0.94788
2018.03.12  15:00  0.94787  0.94891  0.94735  0.94883
2018.03.12  16:00  0.94887  0.94920  0.94778  0.94843
2018.03.12  17:00  0.94842  0.94873  0.94716  0.94754
2018.03.12  18:00  0.94756  0.94763  0.94599  0.94615

[2081 rows x 5 columns]

In [3]:
T2100UsdChf_pd = H1_UsdChf_Reshaped01_pd [(H1_UsdChf_Reshaped01_pd['Time'] == '21:00')]
T2100UsdChf_pd

T0400UsdChf_pd = H1_UsdChf_Reshaped01_pd [(H1_UsdChf_Reshaped01_pd['Time'] == '04:00')]
# T0400UsdChf_pd

In [4]:
T0400UsdChf_Reshaped01_pd = H1_UsdChf_Reshaped01_pd [(H1_UsdChf_Reshaped01_pd['Time'] == '04:00')]
T0400UsdChf_Reshaped01_pd.columns = ['T04', 'OO4','H04','L04','C04']

# T0400UsdChf_Reshaped01_pd

T2100UsdChf_Reshaped01_pd = H1_UsdChf_Reshaped01_pd [(H1_UsdChf_Reshaped01_pd['Time'] == '21:00')]
T2100UsdChf_Reshaped01_pd.columns = ['T21', 'O21','H21','L21','C21']

# T2100UsdChf_Reshaped01_pd

In [5]:
T2100x0400_pd = pd.concat([T2100UsdChf_Reshaped01_pd, T0400UsdChf_Reshaped01_pd], axis=1)
T2100x0400_pd

# Reset Index
T2100x0400_pd = T2100x0400_pd.reset_index()
T2100x0400_pd
## WARNING: LOOKS LIKE THERE'S A PROBLEM WITH THE DATA!

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  """Entry point for launching an IPython kernel.

,index,T21,O21,H21,L21,C21,T04,OO4,H04,L04,C04
0,2017.11.08,21:00,0.99990,1.00031,0.99945,0.99996,04:00,0.99877,0.99881,0.99839,0.99854
1,2017.11.09,21:00,0.99416,0.99434,0.99359,0.99359,04:00,0.99993,0.99998,0.99898,0.99907
2,2017.11.10,21:00,0.99571,0.99605,0.99519,0.99572,04:00,0.99447,0.99495,0.99432,0.99488
3,2017.11.12,21:00,0.99637,0.99644,0.99547,0.99575,NaN,NaN,NaN,NaN,NaN
4,2017.11.13,21:00,0.99592,0.99620,0.99589,0.99611,04:00,0.99639,0.99699,0.99634,0.99694
5,2017.11.14,21:00,0.98946,0.98977,0.98908,0.98924,04:00,0.99647,0.99655,0.99619,0.99640
6,2017.11.15,21:00,0.98806,0.98853,0.98779,0.98822,04:00,0.98866,0.98890,0.98853,0.98889
7,2017.11.16,21:00,0.99391,0.99423,0.99338,0.99388,04:00,0.98896,0.98971,0.98895,0.98949
8,2017.11.17,21:00,0.98847,0.98929,0.98823,0.98825,04:00,0.99163,0.99236,0.99139,0.99235
9,2017.11.19,21:00,0.98842,0.98881,0.98842,0.98872,NaN,NaN,NaN,NaN,NaN
10,2017.11.20,21:00,0.99359,0.99360,0.99294,0.99330,04:00,0.98849,0.98902,0.98839,0.98901
11,2017.11.21,21:00,0.99123,0.99160,0.99098,0.99131,04:00,0.99269,0.99311,0.99266,0.99294
12,2017.11.22,21:00,0.98187,0.98200,0.98139,0.98144,04:00,0.99068,0.99073,0.99030,0.99057
13,2017.11.23,21:00,0.98105,0.98190,0.98074,0.98166,04:00,0.98146,0.98169,0.98133,0.98137
14,2017.11.24,21:00,0.97931,0.97972,0.97852,0.97929,04:00,0.98193,0.98205,0.98143,0.98174
15,2017.11.26,21:00,0.97849,0.97976,0.97813,0.97917,NaN,NaN,NaN,NaN,NaN
16,2017.11.27,21:00,0.98156,0.98188,0.98107,0.98135,04:00,0.98070,0.98079,0.98020,0.98037
17,2017.11.28,21:00,0.98436,0.98436,0.98317,0.98381,04:00,0.98132,0.98162,0.98109,0.98140
18,2017.11.29,21:00,0.98414,0.98450,0.98380,0.98439,04:00,0.98402,0.98485,0.98395,0.98485
19,2017.11.30,21:00,0.98361,0.98364,0.98282,0.98338,04:00,0.98401,0.98452,0.98394,0.98452
20,2017.12.01,21:00,0.97647,0.97663,0.97534,0.97561,04:00,0.98374,0.98400,0.98341,0.98397
21,2017.12.03,21:00,0.98150,0.98152,0.98085,0.98134,NaN,NaN,NaN,NaN,NaN
22,2017.12.04,21:00,0.98539,0.98552,0.98467,0.98476,04:00,0.98249,0.98253,0.98210,0.98233
23,2017.12.05,21:00,0.98736,0.98759,0.98693,0.98719,04:00,0.98439,0.98460,0.98411,0.98458
24,2017.12.06,21:00,0.98980,0.98999,0.98953,0.98972,04:00,0.98658,0.98696,0.98579,0.98602
25,2017.12.07,21:00,0.99421,0.99457,0.99414,0.99421,04:00,0.98934,0.98987,0.98921,0.98986
26,2017.12.08,21:00,0.99284,0.99291,0.99224,0.99254,04:00,0.99462,0.99536,0.99443,0.99524
27,2017.12.10,21:00,0.99375,0.99403,0.99368,0.99376,NaN,NaN,NaN,NaN,NaN
28,2017.12.11,21:00,0.99174,0.99203,0.99161,0.99170,04:00,0.99176,0.99201,0.99175,0.99197
29,2017.12.12,21:00,0.99115,0.99142,0.99085,0.99137,04:00,0.99173,0.99193,0.99158,0.99179
...,...,...,...,...,...,...,...,...,...,...,...
72,2018.02.06,21:00,0.93705,0.93743,0.93539,0.93584,04:00,0.93123,0.93241,0.93067,0.93217
73,2018.02.07,21:00,0.94368,0.94412,0.94241,0.94370,04:00,0.93531,0.93547,0.93444,0.93489
74,2018.02.08,21:00,0.93599,0.93635,0.93571,0.93591,04:00,0.94396,0.94514,0.94384,0.94457
75,2018.02.09,21:00,0.93998,0.93998,0.93913,0.93934,04:00,0.93761,0.93831,0.93749,0.93822
76,2018.02.11,21:00,0.93955,0.93968,0.93955,0.93956,NaN,NaN,NaN,NaN,NaN
77,2018.02.12,21:00,0.93903,0.93951,0.93887,0.93899,04:00,0.93791,0.93813,0.93762,0.93807
78,2018.02.13,21:00,0.93506,0.93514,0.93467,0.93467,04:00,0.93906,0.93917,0.93793,0.93831
79,2018.02.14,21:00,0.92898,0.92958,0.92889,0.92928,04:00,0.93073,0.93278,0.93068,0.93273
80,2018.02.15,21:00,0.92149,0.92222,0.92145,0.92188,04:00,0.92750,0.92815,0.92624,0.92810
81,2018.02.16,21:00,0.92763,0.92763,0.92685,0.92732,04:00,0.92065,0.92089,0.91895,0.91945
82,2018.02.18,21:00,0.92724,0.92735,0.92724,0.92735,NaN,NaN,NaN,NaN,NaN
83,2018.02.19,21:00,0.92878,0.92905,0.92839,0.92899,04:00,0.92745,0.92819,0.92732,0.92793
84,2018.02.20,21:00,0.93576,0.93630,0.93576,0.93602,04:00,0.93066,0.93098,0.93017,0.93060
85,2018.02.21,21:00,0.93828,0.93894,0.93765,0.93863,04:00,0.93716,0.93794,0.93666,0.93777
86,2018.02.22,21:00,0.93292,0.93317,0.93265,0.93273,04:00,0.93881,0.93943,0.93873,0.93937
87,2018.02.23,21:00,0.93667,0.93702,0.93585,0.93595,04:00,0.93439,0.93534,0.93424,0.93508
88,2018.02.25,21:00,0.93620,0.93698,0.93548,0.93698,NaN,NaN,NaN,NaN,NaN
89,2018.02.26,21:00,0.93806,0.93833,0.93759,0.93777,04:00,0.93443,0.93478,0.93424,0.93451
90,2018.02.27,21:00,0.93902,0.93930,0.93880,0.93884,04:00,0.93762,0.93801,0.93737,0.93774
91,2018.02.28,21:00,0.94432,0.94457,0.94394,0.94442,04:00,0.93987,0.94018,0.93965,0.93996
92,2018.03.01,21:00,0.94225,0.94225,0.94151,0.94161,04:00,0.94499,0.94544,0.94478,0.94515
93,2018.03.02,21:00,0.93714,0.93782,0.93700,0.93708,04:00,0.94015,0.94017,0.93967,0.94012
94,2018.03.04,21:00,0.93463,0.93693,0.93455,0.93624,NaN,NaN,NaN,NaN,NaN
95,2018.03.05,21:00,0.94010,0.94028,0.93969,0.93972,04:00,0.93600,0.93635,0.93599,0.93627
96,2018.03.06,21:00,0.94083,0.94088,0.93997,0.94055,04:00,0.93909,0.93963,0.93899,0.93959
97,2018.03.07,21:00,0.94304,0.94345,0.94271,0.94335,04:00,0.93719,0.93757,0.93681,0.93753
98,2018.03.08,21:00,0.95093,0.95116,0.95056,0.95091,04:00,0.94293,0.94339,0.94281,0.94326
99,2018.03.09,21:00,0.95104,0.95143,0.95103,0.95116,04:00,0.95195,0.95247,0.95173,0.95212
100,2018.03.11,21:00,0.95033,0.95120,0.94968,0.95102,NaN,NaN,NaN,NaN,NaN
101,2018.03.12,NaN,NaN,NaN,NaN,NaN,04:00,0.94982,0.94991,0.94921,0.94929

In [6]:
mDataBullBear = T2100x0400_pd['C21'] - T2100x0400_pd['C04']
mDataBullBear

mDataBullBear_pd = pd.DataFrame (mDataBullBear, columns = ['Calc'])
mDataBullBear_pd

concat0421BlBrTable_pd = pd.concat([T2100x0400_pd, mDataBullBear_pd], axis=1)
concat0421BlBrTable_pd

T2100x0400_pd

BullOrBearResult = np.where (concat0421BlBrTable_pd ['Calc'] > 0, 'bull', 'bear')
# BullOrBearResult
BullOrBearResult_pd = pd.DataFrame (BullOrBearResult, columns = ['Bull / Bear'])
BullOrBearResult_pd 

summaryTable01 = T2100x0400_pd
summaryTable01
# summaryTable01 = pd.concat([T2100x0400_pd, BullOrBearResult_pd], axis=1)
# summaryTable01

,index,T21,O21,H21,L21,C21,T04,OO4,H04,L04,C04
0,2017.11.08,21:00,0.99990,1.00031,0.99945,0.99996,04:00,0.99877,0.99881,0.99839,0.99854
1,2017.11.09,21:00,0.99416,0.99434,0.99359,0.99359,04:00,0.99993,0.99998,0.99898,0.99907
2,2017.11.10,21:00,0.99571,0.99605,0.99519,0.99572,04:00,0.99447,0.99495,0.99432,0.99488
3,2017.11.12,21:00,0.99637,0.99644,0.99547,0.99575,NaN,NaN,NaN,NaN,NaN
4,2017.11.13,21:00,0.99592,0.99620,0.99589,0.99611,04:00,0.99639,0.99699,0.99634,0.99694
5,2017.11.14,21:00,0.98946,0.98977,0.98908,0.98924,04:00,0.99647,0.99655,0.99619,0.99640
6,2017.11.15,21:00,0.98806,0.98853,0.98779,0.98822,04:00,0.98866,0.98890,0.98853,0.98889
7,2017.11.16,21:00,0.99391,0.99423,0.99338,0.99388,04:00,0.98896,0.98971,0.98895,0.98949
8,2017.11.17,21:00,0.98847,0.98929,0.98823,0.98825,04:00,0.99163,0.99236,0.99139,0.99235
9,2017.11.19,21:00,0.98842,0.98881,0.98842,0.98872,NaN,NaN,NaN,NaN,NaN
10,2017.11.20,21:00,0.99359,0.99360,0.99294,0.99330,04:00,0.98849,0.98902,0.98839,0.98901
11,2017.11.21,21:00,0.99123,0.99160,0.99098,0.99131,04:00,0.99269,0.99311,0.99266,0.99294
12,2017.11.22,21:00,0.98187,0.98200,0.98139,0.98144,04:00,0.99068,0.99073,0.99030,0.99057
13,2017.11.23,21:00,0.98105,0.98190,0.98074,0.98166,04:00,0.98146,0.98169,0.98133,0.98137
14,2017.11.24,21:00,0.97931,0.97972,0.97852,0.97929,04:00,0.98193,0.98205,0.98143,0.98174
15,2017.11.26,21:00,0.97849,0.97976,0.97813,0.97917,NaN,NaN,NaN,NaN,NaN
16,2017.11.27,21:00,0.98156,0.98188,0.98107,0.98135,04:00,0.98070,0.98079,0.98020,0.98037
17,2017.11.28,21:00,0.98436,0.98436,0.98317,0.98381,04:00,0.98132,0.98162,0.98109,0.98140
18,2017.11.29,21:00,0.98414,0.98450,0.98380,0.98439,04:00,0.98402,0.98485,0.98395,0.98485
19,2017.11.30,21:00,0.98361,0.98364,0.98282,0.98338,04:00,0.98401,0.98452,0.98394,0.98452
20,2017.12.01,21:00,0.97647,0.97663,0.97534,0.97561,04:00,0.98374,0.98400,0.98341,0.98397
21,2017.12.03,21:00,0.98150,0.98152,0.98085,0.98134,NaN,NaN,NaN,NaN,NaN
22,2017.12.04,21:00,0.98539,0.98552,0.98467,0.98476,04:00,0.98249,0.98253,0.98210,0.98233
23,2017.12.05,21:00,0.98736,0.98759,0.98693,0.98719,04:00,0.98439,0.98460,0.98411,0.98458
24,2017.12.06,21:00,0.98980,0.98999,0.98953,0.98972,04:00,0.98658,0.98696,0.98579,0.98602
25,2017.12.07,21:00,0.99421,0.99457,0.99414,0.99421,04:00,0.98934,0.98987,0.98921,0.98986
26,2017.12.08,21:00,0.99284,0.99291,0.99224,0.99254,04:00,0.99462,0.99536,0.99443,0.99524
27,2017.12.10,21:00,0.99375,0.99403,0.99368,0.99376,NaN,NaN,NaN,NaN,NaN
28,2017.12.11,21:00,0.99174,0.99203,0.99161,0.99170,04:00,0.99176,0.99201,0.99175,0.99197
29,2017.12.12,21:00,0.99115,0.99142,0.99085,0.99137,04:00,0.99173,0.99193,0.99158,0.99179
...,...,...,...,...,...,...,...,...,...,...,...
72,2018.02.06,21:00,0.93705,0.93743,0.93539,0.93584,04:00,0.93123,0.93241,0.93067,0.93217
73,2018.02.07,21:00,0.94368,0.94412,0.94241,0.94370,04:00,0.93531,0.93547,0.93444,0.93489
74,2018.02.08,21:00,0.93599,0.93635,0.93571,0.93591,04:00,0.94396,0.94514,0.94384,0.94457
75,2018.02.09,21:00,0.93998,0.93998,0.93913,0.93934,04:00,0.93761,0.93831,0.93749,0.93822
76,2018.02.11,21:00,0.93955,0.93968,0.93955,0.93956,NaN,NaN,NaN,NaN,NaN
77,2018.02.12,21:00,0.93903,0.93951,0.93887,0.93899,04:00,0.93791,0.93813,0.93762,0.93807
78,2018.02.13,21:00,0.93506,0.93514,0.93467,0.93467,04:00,0.93906,0.93917,0.93793,0.93831
79,2018.02.14,21:00,0.92898,0.92958,0.92889,0.92928,04:00,0.93073,0.93278,0.93068,0.93273
80,2018.02.15,21:00,0.92149,0.92222,0.92145,0.92188,04:00,0.92750,0.92815,0.92624,0.92810
81,2018.02.16,21:00,0.92763,0.92763,0.92685,0.92732,04:00,0.92065,0.92089,0.91895,0.91945
82,2018.02.18,21:00,0.92724,0.92735,0.92724,0.92735,NaN,NaN,NaN,NaN,NaN
83,2018.02.19,21:00,0.92878,0.92905,0.92839,0.92899,04:00,0.92745,0.92819,0.92732,0.92793
84,2018.02.20,21:00,0.93576,0.93630,0.93576,0.93602,04:00,0.93066,0.93098,0.93017,0.93060
85,2018.02.21,21:00,0.93828,0.93894,0.93765,0.93863,04:00,0.93716,0.93794,0.93666,0.93777
86,2018.02.22,21:00,0.93292,0.93317,0.93265,0.93273,04:00,0.93881,0.93943,0.93873,0.93937
87,2018.02.23,21:00,0.93667,0.93702,0.93585,0.93595,04:00,0.93439,0.93534,0.93424,0.93508
88,2018.02.25,21:00,0.93620,0.93698,0.93548,0.93698,NaN,NaN,NaN,NaN,NaN
89,2018.02.26,21:00,0.93806,0.93833,0.93759,0.93777,04:00,0.93443,0.93478,0.93424,0.93451
90,2018.02.27,21:00,0.93902,0.93930,0.93880,0.93884,04:00,0.93762,0.93801,0.93737,0.93774
91,2018.02.28,21:00,0.94432,0.94457,0.94394,0.94442,04:00,0.93987,0.94018,0.93965,0.93996
92,2018.03.01,21:00,0.94225,0.94225,0.94151,0.94161,04:00,0.94499,0.94544,0.94478,0.94515
93,2018.03.02,21:00,0.93714,0.93782,0.93700,0.93708,04:00,0.94015,0.94017,0.93967,0.94012
94,2018.03.04,21:00,0.93463,0.93693,0.93455,0.93624,NaN,NaN,NaN,NaN,NaN
95,2018.03.05,21:00,0.94010,0.94028,0.93969,0.93972,04:00,0.93600,0.93635,0.93599,0.93627
96,2018.03.06,21:00,0.94083,0.94088,0.93997,0.94055,04:00,0.93909,0.93963,0.93899,0.93959
97,2018.03.07,21:00,0.94304,0.94345,0.94271,0.94335,04:00,0.93719,0.93757,0.93681,0.93753
98,2018.03.08,21:00,0.95093,0.95116,0.95056,0.95091,04:00,0.94293,0.94339,0.94281,0.94326
99,2018.03.09,21:00,0.95104,0.95143,0.95103,0.95116,04:00,0.95195,0.95247,0.95173,0.95212
100,2018.03.11,21:00,0.95033,0.95120,0.94968,0.95102,NaN,NaN,NaN,NaN,NaN
101,2018.03.12,NaN,NaN,NaN,NaN,NaN,04:00,0.94982,0.94991,0.94921,0.94929

In [7]:
dailyFullUsdChfD1_pd = pd.read_csv('datasets/2018-05-02-UsdChfD1.csv')
# dailyFullUsdChfD1_pd = dailyFullUsdChfD1_pd.drop(dailyFullUsdChfD1_pd.columns[[-3, -1]], axis=1)
dailyFullUsdChfD1_pd

# Reset index
dailyFullUsdChfD1_pd = dailyFullUsdChfD1_pd.reset_index()
dailyFullUsdChfD1_pd

# Drop columns
dailyFullUsdChfD1_pd = dailyFullUsdChfD1_pd.drop(['na', 'Close', 'Open', 'Volume'], axis=1)
dailyFullUsdChfD1_pd

          index     High      Low
0    2017.11.08  1.00056  0.99803
1    2017.11.09  1.00168  0.99209
2    2017.11.10  0.99676  0.99246
3    2017.11.12  0.99660  0.99520
4    2017.11.13  0.99861  0.99359
5    2017.11.14  0.99698  0.98811
6    2017.11.15  0.99102  0.98456
7    2017.11.16  0.99446  0.98819
8    2017.11.17  0.99350  0.98753
9    2017.11.19  0.98999  0.98796
10   2017.11.20  0.99364  0.98781
11   2017.11.21  0.99460  0.98984
12   2017.11.22  0.99101  0.98081
13   2017.11.23  0.98272  0.97944
14   2017.11.24  0.98264  0.97849
15   2017.11.26  0.98044  0.97813
16   2017.11.27  0.98188  0.97779
17   2017.11.28  0.98519  0.98017
18   2017.11.29  0.98690  0.98180
19   2017.11.30  0.98813  0.98152
20   2017.12.01  0.98697  0.97343
21   2017.12.03  0.98236  0.97928
22   2017.12.04  0.98661  0.98106
23   2017.12.05  0.98867  0.98365
24   2017.12.06  0.99087  0.98543
25   2017.12.07  0.99467  0.98909
26   2017.12.08  0.99769  0.99224
27   2017.12.10  0.99403  0.99230
28   2017.12.11  0.99297  0.98965
29   2017.12.12  0.99350  0.98896
..          ...      ...      ...
72   2018.01.31  0.93583  0.92887
73   2018.02.01  0.93410  0.92554
74   2018.02.02  0.93357  0.92575
75   2018.02.04  0.93268  0.93075
76   2018.02.05  0.93756  0.92866
77   2018.02.06  0.93971  0.93059
78   2018.02.07  0.94536  0.93393
79   2018.02.08  0.94691  0.93476
80   2018.02.09  0.94080  0.93507
81   2018.02.11  0.94033  0.93910
82   2018.02.12  0.94008  0.93629
83   2018.02.13  0.93978  0.93218
84   2018.02.14  0.93734  0.92720
85   2018.02.15  0.92905  0.92095
86   2018.02.16  0.92868  0.91870
87   2018.02.18  0.92784  0.92633
88   2018.02.19  0.93191  0.92622
89   2018.02.20  0.93685  0.92889
90   2018.02.21  0.93959  0.93423
91   2018.02.22  0.94083  0.93215
92   2018.02.23  0.93733  0.93271
93   2018.02.25  0.93732  0.93548
94   2018.02.26  0.93904  0.93249
95   2018.02.27  0.94165  0.93576
96   2018.02.28  0.94576  0.93870
97   2018.03.01  0.94897  0.94095
98   2018.03.02  0.94238  0.93378
99   2018.03.04  0.93787  0.93452
100  2018.03.05  0.94075  0.93525
101  2018.03.06  0.94182  0.93591

[102 rows x 3 columns]

In [8]:
# If Buy or If Sell 
mDataPositionBuy = dailyFullUsdChfD1_pd ['High'] - T2100x0400_pd ['C04']
mDataPositionBuy_pd = pd.DataFrame (mDataPositionBuy, columns = ['If Buy'])

mDataPositionSell = T2100x0400_pd ['C04'] - dailyFullUsdChfD1_pd ['Low']
mDataPositionSell_pd = pd.DataFrame (mDataPositionSell, columns = ['If Sell'])
# Print 
# mDataPositionSell_pd 
# mDataPositionBuy_pd

IfBuyIfSell_pd = pd.concat([mDataPositionBuy_pd, mDataPositionSell_pd], axis=1)

# Drop NaN
IfBuyIfSell_pd = IfBuyIfSell_pd.dropna()
IfBuyIfSell_pd

# Convert to Numpy
# concatIfBuySell_np = concatIfBuySell_pd.values
# Print
# concatIfBuySell_pd

# mDataBullBearResult_np = mDataBullBearResult_pd.values
# Print
# mDataBullBearResult_pd

# concatIfBuySell_pd = concatIfBuySell_pd.reset_index(drop=True)
# concatIfBuySell_pd

summaryTable02 = pd.concat([dailyFullUsdChfD1_pd, IfBuyIfSell_pd, BullOrBearResult_pd], axis=1)
summaryTable02
# concatIfBuySellBlBrRes_pd

# Assign rename to more readable variable
# summaryIfBuySellBullBearResult_pd = concatIfBuySellBlBrRes_pd.dropna()

# Print
# summaryIfBuySellBullBearResult_pd

          index     High      Low   If Buy  If Sell Bull / Bear
0    2017.11.08  1.00056  0.99803  0.00202  0.00051        bull
1    2017.11.09  1.00168  0.99209  0.00261  0.00698        bear
2    2017.11.10  0.99676  0.99246  0.00188  0.00242        bull
3    2017.11.12  0.99660  0.99520      NaN      NaN        bear
4    2017.11.13  0.99861  0.99359  0.00167  0.00335        bear
5    2017.11.14  0.99698  0.98811  0.00058  0.00829        bear
6    2017.11.15  0.99102  0.98456  0.00213  0.00433        bear
7    2017.11.16  0.99446  0.98819  0.00497  0.00130        bull
8    2017.11.17  0.99350  0.98753  0.00115  0.00482        bear
9    2017.11.19  0.98999  0.98796      NaN      NaN        bear
10   2017.11.20  0.99364  0.98781  0.00463  0.00120        bull
11   2017.11.21  0.99460  0.98984  0.00166  0.00310        bear
12   2017.11.22  0.99101  0.98081  0.00044  0.00976        bear
13   2017.11.23  0.98272  0.97944  0.00135  0.00193        bull
14   2017.11.24  0.98264  0.97849  0.00090  0.00325        bear
15   2017.11.26  0.98044  0.97813      NaN      NaN        bear
16   2017.11.27  0.98188  0.97779  0.00151  0.00258        bull
17   2017.11.28  0.98519  0.98017  0.00379  0.00123        bull
18   2017.11.29  0.98690  0.98180  0.00205  0.00305        bear
19   2017.11.30  0.98813  0.98152  0.00361  0.00300        bear
20   2017.12.01  0.98697  0.97343  0.00300  0.01054        bear
21   2017.12.03  0.98236  0.97928      NaN      NaN        bear
22   2017.12.04  0.98661  0.98106  0.00428  0.00127        bull
23   2017.12.05  0.98867  0.98365  0.00409  0.00093        bull
24   2017.12.06  0.99087  0.98543  0.00485  0.00059        bull
25   2017.12.07  0.99467  0.98909  0.00481  0.00077        bull
26   2017.12.08  0.99769  0.99224  0.00245  0.00300        bear
27   2017.12.10  0.99403  0.99230      NaN      NaN        bear
28   2017.12.11  0.99297  0.98965  0.00100  0.00232        bear
29   2017.12.12  0.99350  0.98896  0.00171  0.00283        bear
..          ...      ...      ...      ...      ...         ...
72   2018.01.31  0.93583  0.92887  0.00366  0.00330        bull
73   2018.02.01  0.93410  0.92554 -0.00079  0.00935        bull
74   2018.02.02  0.93357  0.92575 -0.01100  0.01882        bear
75   2018.02.04  0.93268  0.93075 -0.00554  0.00747        bull
76   2018.02.05  0.93756  0.92866      NaN      NaN        bear
77   2018.02.06  0.93971  0.93059  0.00164  0.00748        bull
78   2018.02.07  0.94536  0.93393  0.00705  0.00438        bear
79   2018.02.08  0.94691  0.93476  0.01418 -0.00203        bear
80   2018.02.09  0.94080  0.93507  0.01270 -0.00697        bear
81   2018.02.11  0.94033  0.93910  0.02088 -0.01965        bull
82   2018.02.12  0.94008  0.93629      NaN      NaN        bear
83   2018.02.13  0.93978  0.93218  0.01185 -0.00425        bull
84   2018.02.14  0.93734  0.92720  0.00674  0.00340        bull
85   2018.02.15  0.92905  0.92095 -0.00872  0.01682        bull
86   2018.02.16  0.92868  0.91870 -0.01069  0.02067        bear
87   2018.02.18  0.92784  0.92633 -0.00724  0.00875        bull
88   2018.02.19  0.93191  0.92622      NaN      NaN        bear
89   2018.02.20  0.93685  0.92889  0.00234  0.00562        bull
90   2018.02.21  0.93959  0.93423  0.00185  0.00351        bull
91   2018.02.22  0.94083  0.93215  0.00087  0.00781        bull
92   2018.02.23  0.93733  0.93271 -0.00782  0.01244        bear
93   2018.02.25  0.93732  0.93548 -0.00280  0.00464        bear
94   2018.02.26  0.93904  0.93249      NaN      NaN        bear
95   2018.02.27  0.94165  0.93576  0.00538  0.00051        bull
96   2018.02.28  0.94576  0.93870  0.00617  0.00089        bull
97   2018.03.01  0.94897  0.94095  0.01144 -0.00342        bull
98   2018.03.02  0.94238  0.93378 -0.00088  0.00948        bull
99   2018.03.04  0.93787  0.93452 -0.01425  0.01760        bear
100  2018.03.05  0.94075  0.93525      NaN      NaN        bear
101  2018.03.06  0.94182  0.93591 -0.00747  0.01338        bear

[102 rows x 6 columns]

In [59]:
# ** Capture all bull and capture all bear

tableForBuyEntry_pd = summaryTable02[(summaryTable02['Bull / Bear'] == 'bull')]
tableForSellEntry_pd = summaryTable02[(summaryTable02['Bull / Bear'] == 'bear')]

# Print
tableForBuyEntry_pd
# tableForSellEntry_pd

         index     High      Low   If Buy  If Sell Bull / Bear
0   2017.11.08  1.00056  0.99803  0.00202  0.00051        bull
2   2017.11.10  0.99676  0.99246  0.00188  0.00242        bull
7   2017.11.16  0.99446  0.98819  0.00497  0.00130        bull
10  2017.11.20  0.99364  0.98781  0.00463  0.00120        bull
13  2017.11.23  0.98272  0.97944  0.00135  0.00193        bull
16  2017.11.27  0.98188  0.97779  0.00151  0.00258        bull
17  2017.11.28  0.98519  0.98017  0.00379  0.00123        bull
22  2017.12.04  0.98661  0.98106  0.00428  0.00127        bull
23  2017.12.05  0.98867  0.98365  0.00409  0.00093        bull
24  2017.12.06  0.99087  0.98543  0.00485  0.00059        bull
25  2017.12.07  0.99467  0.98909  0.00481  0.00077        bull
31  2017.12.14  0.99035  0.98393  0.00573  0.00069        bull
32  2017.12.15  0.99336  0.98728  0.00475  0.00133        bull
36  2017.12.20  0.98846  0.98278  0.00327  0.00241        bull
37  2017.12.21  0.99089  0.98544  0.00487  0.00058        bull
44  2017.12.29  0.97885  0.97334  0.00691 -0.00140        bull
46  2018.01.01  0.97389  0.96988 -0.00034  0.00435        bull
48  2018.01.03  0.97967  0.97139  0.00400  0.00428        bull
49  2018.01.04  0.97798  0.97346  0.00075  0.00377        bull
56  2018.01.12  0.97700  0.96647  0.01467 -0.00414        bull
58  2018.01.15  0.96843  0.96024  0.01159 -0.00340        bull
65  2018.01.23  0.96328  0.95643  0.02735 -0.02050        bull
69  2018.01.28  0.93481  0.93303  0.00777 -0.00599        bull
71  2018.01.30  0.93927  0.93095  0.00870 -0.00038        bull
72  2018.01.31  0.93583  0.92887  0.00366  0.00330        bull
73  2018.02.01  0.93410  0.92554 -0.00079  0.00935        bull
75  2018.02.04  0.93268  0.93075 -0.00554  0.00747        bull
77  2018.02.06  0.93971  0.93059  0.00164  0.00748        bull
81  2018.02.11  0.94033  0.93910  0.02088 -0.01965        bull
83  2018.02.13  0.93978  0.93218  0.01185 -0.00425        bull
84  2018.02.14  0.93734  0.92720  0.00674  0.00340        bull
85  2018.02.15  0.92905  0.92095 -0.00872  0.01682        bull
87  2018.02.18  0.92784  0.92633 -0.00724  0.00875        bull
89  2018.02.20  0.93685  0.92889  0.00234  0.00562        bull
90  2018.02.21  0.93959  0.93423  0.00185  0.00351        bull
91  2018.02.22  0.94083  0.93215  0.00087  0.00781        bull
95  2018.02.27  0.94165  0.93576  0.00538  0.00051        bull
96  2018.02.28  0.94576  0.93870  0.00617  0.00089        bull
97  2018.03.01  0.94897  0.94095  0.01144 -0.00342        bull
98  2018.03.02  0.94238  0.93378 -0.00088  0.00948        bull

In [69]:
# For buy position result
BuyPosSubResult = np.where (tableForBuyEntry_pd ['If Buy'] > 0.0008, 'Success', 'Fail')
BuyPosSubResult_pd = pd.DataFrame (BuyPosSubResult, columns = ['Buy Result'])
BuyPosSubResult_pd  

# Convert To Numpy 
BuyPosSubResult_np = BuyPosSubResult_pd.values

# Test count success 
(BuyPosSubResult_np == 'Success').sum() 

# Count Contents
countTotalResultForBuy = len(BuyPosSubResult_np)
countSuccessResultBuy = (BuyPosSubResult_np == 'Success').sum() 

WinRateForBuyPos = countSuccessResultBuy / countTotalResultForBuy
WinRateForBuyPos

# Print
# countTotalResultForBuy

0.825

In [70]:
SellPosSubResult = np.where (tableForSellEntry_pd ['If Sell'] > 0.0008, 'Success', 'Fail')
SellPosSubResult_pd = pd.DataFrame (SellPosSubResult, columns = ['Sell Result'])
SellPosSubResult_pd  

# Convert To Numpy
SellPosSubResult_np = SellPosSubResult_pd.values
(SellPosSubResult_np == 'Success').sum()

# Count Contents
countResultForSell = len(SellPosSubResult_np)
countSuccessResultSell = (SellPosSubResult_np == 'Success').sum() 

WinRateForSell = countSuccessResultSell / countResultForSell
WinRateForSell

0.5483870967741935