In [1]:
# Nostradamus One: NTS Framework for all pairs.
import pandas as pd
import numpy as np

In [5]:
H1FullUsdChf_pd = pd.read_csv('datasets/2018-06-12-UsdChfH1_raw.csv')
H1FullUsdChf_pd

# Rename Columns to: Time, Open, High, Low, Close, Volume
H1FullUsdChf_pd.columns = ['Date', 'Time', 'Open','High','Low','Close', 'Volume']
H1FullUsdChf_pd

             Date   Time     Open     High      Low    Close  Volume
0      2015.05.19  11:00  0.93110  0.93270  0.93010  0.93170    4886
1      2015.05.19  12:00  0.93160  0.93200  0.93000  0.93040    2751
2      2015.05.19  13:00  0.93040  0.93110  0.92960  0.92990    1860
3      2015.05.19  14:00  0.92990  0.93190  0.92970  0.92970    2262
4      2015.05.19  15:00  0.92970  0.93760  0.92960  0.93710    5567
5      2015.05.19  16:00  0.93710  0.93720  0.93360  0.93480    4700
6      2015.05.19  17:00  0.93470  0.93790  0.93430  0.93770    4805
7      2015.05.19  18:00  0.93780  0.93810  0.93590  0.93660    3418
8      2015.05.19  19:00  0.93650  0.93720  0.93580  0.93590    1476
9      2015.05.19  20:00  0.93590  0.93800  0.93580  0.93720    1202
10     2015.05.19  21:00  0.93720  0.93740  0.93640  0.93700    1125
11     2015.05.19  22:00  0.93700  0.93740  0.93600  0.93740     738
12     2015.05.19  23:00  0.93740  0.93750  0.93600  0.93600     913
13     2015.05.20  00:00  0.93670  0.93690  0.93640  0.93660     340
14     2015.05.20  01:00  0.93670  0.93710  0.93650  0.93690    1409
15     2015.05.20  02:00  0.93680  0.93710  0.93660  0.93690     426
16     2015.05.20  03:00  0.93700  0.93820  0.93680  0.93710    1512
17     2015.05.20  04:00  0.93700  0.93750  0.93640  0.93680    1245
18     2015.05.20  05:00  0.93680  0.93690  0.93560  0.93610     686
19     2015.05.20  06:00  0.93610  0.93640  0.93580  0.93620     425
20     2015.05.20  07:00  0.93620  0.93680  0.93580  0.93680     619
21     2015.05.20  08:00  0.93680  0.93780  0.93530  0.93780     944
22     2015.05.20  09:00  0.93780  0.93960  0.93710  0.93890    3912
23     2015.05.20  10:00  0.93890  0.94030  0.93770  0.93870    3697
24     2015.05.20  11:00  0.93870  0.93870  0.93570  0.93750    4117
25     2015.05.20  12:00  0.93750  0.93830  0.93630  0.93740    2995
26     2015.05.20  13:00  0.93740  0.94020  0.93690  0.93970    2849
27     2015.05.20  14:00  0.93980  0.93990  0.93760  0.93800    3120
28     2015.05.20  15:00  0.93800  0.93840  0.93490  0.93500    5018
29     2015.05.20  16:00  0.93490  0.93820  0.93490  0.93710    4991
...           ...    ...      ...      ...      ...      ...     ...
19042  2018.06.08  12:00  0.98213  0.98338  0.98203  0.98274    4801
19043  2018.06.08  13:00  0.98273  0.98408  0.98235  0.98406    5551
19044  2018.06.08  14:00  0.98405  0.98492  0.98395  0.98410    6338
19045  2018.06.08  15:00  0.98411  0.98871  0.98408  0.98867    6420
19046  2018.06.08  16:00  0.98868  0.98871  0.98607  0.98734    7270
19047  2018.06.08  17:00  0.98733  0.98737  0.98500  0.98535    7969
19048  2018.06.08  18:00  0.98534  0.98652  0.98503  0.98594    4979
19049  2018.06.08  19:00  0.98595  0.98683  0.98550  0.98570    3207
19050  2018.06.08  20:00  0.98569  0.98609  0.98505  0.98509    2814
19051  2018.06.08  21:00  0.98510  0.98523  0.98461  0.98503    2904
19052  2018.06.08  22:00  0.98505  0.98583  0.98504  0.98521    2344
19053  2018.06.08  23:00  0.98519  0.98528  0.98425  0.98429    1356
19054  2018.06.11  00:00  0.98433  0.98477  0.98419  0.98442     257
19055  2018.06.11  01:00  0.98440  0.98497  0.98439  0.98479     787
19056  2018.06.11  02:00  0.98479  0.98501  0.98458  0.98481     989
19057  2018.06.11  03:00  0.98481  0.98543  0.98450  0.98461    4303
19058  2018.06.11  04:00  0.98462  0.98475  0.98387  0.98427    4257
19059  2018.06.11  05:00  0.98428  0.98606  0.98421  0.98566    2355
19060  2018.06.11  06:00  0.98566  0.98580  0.98527  0.98535    1264
19061  2018.06.11  07:00  0.98536  0.98557  0.98512  0.98525    1512
19062  2018.06.11  08:00  0.98524  0.98581  0.98512  0.98569    1812
19063  2018.06.11  09:00  0.98570  0.98716  0.98543  0.98627    6042
19064  2018.06.11  10:00  0.98628  0.98649  0.98422  0.98598    5320
19065  2018.06.11  11:00  0.98600  0.98647  0.98444  0.98614    5260
19066  2018.06.11  12:00  0.98615  0.98668  0.98578  0.98635    3905
19067  2018.06.11  13:00  0.98637  0.98734  0.98594  0.98697    4216
19068  2018.06.11  14:00  0.98696  0.98729  0.98623  0.98667    3548
19069  2018.06.11  15:00  0.98665  0.98672  0.98480  0.98503    5389
19070  2018.06.11  16:00  0.98500  0.98544  0.98457  0.98493    4385
19071  2018.06.11  17:00  0.98495  0.98531  0.98407  0.98432    4351

[19072 rows x 7 columns]

In [3]:
T2100UsdChf_pd = H1_UsdChf_Reshaped01_pd [(H1_UsdChf_Reshaped01_pd['Time'] == '21:00')]
T2100UsdChf_pd

T0400UsdChf_pd = H1_UsdChf_Reshaped01_pd [(H1_UsdChf_Reshaped01_pd['Time'] == '04:00')]
# T0400UsdChf_pd

In [4]:
T0400UsdChf_Reshaped01_pd = H1_UsdChf_Reshaped01_pd [(H1_UsdChf_Reshaped01_pd['Time'] == '04:00')]
T0400UsdChf_Reshaped01_pd.columns = ['T04', 'OO4','H04','L04','C04']

# T0400UsdChf_Reshaped01_pd

T2100UsdChf_Reshaped01_pd = H1_UsdChf_Reshaped01_pd [(H1_UsdChf_Reshaped01_pd['Time'] == '21:00')]
T2100UsdChf_Reshaped01_pd.columns = ['T21', 'O21','H21','L21','C21']

# T2100UsdChf_Reshaped01_pd

ValueError: Length mismatch: Expected axis has 7 elements, new values have 5 elements

In [ ]:
T2100x0400_pd = pd.concat([T2100UsdChf_Reshaped01_pd, T0400UsdChf_Reshaped01_pd], axis=1)
T2100x0400_pd

# Reset Index
T2100x0400_pd = T2100x0400_pd.reset_index()
T2100x0400_pd
## WARNING: LOOKS LIKE THERE'S A PROBLEM WITH THE DATA!

In [ ]:
mDataBullBear = T2100x0400_pd['C21'] - T2100x0400_pd['C04']
mDataBullBear

mDataBullBear_pd = pd.DataFrame (mDataBullBear, columns = ['Calc'])
mDataBullBear_pd

concat0421BlBrTable_pd = pd.concat([T2100x0400_pd, mDataBullBear_pd], axis=1)
concat0421BlBrTable_pd

T2100x0400_pd

BullOrBearResult = np.where (concat0421BlBrTable_pd ['Calc'] > 0, 'bull', 'bear')

# BullOrBearResult
BullOrBearResult_pd = pd.DataFrame (BullOrBearResult, columns = ['Bull / Bear'])
BullOrBearResult_pd 

summaryTable01 = T2100x0400_pd
summaryTable01

In [ ]:
dailyFullUsdChfD1_pd = pd.read_csv('datasets/2018-05-02-UsdChfD1.csv')
# dailyFullUsdChfD1_pd = dailyFullUsdChfD1_pd.drop(dailyFullUsdChfD1_pd.columns[[-3, -1]], axis=1)
dailyFullUsdChfD1_pd

# Reset index
dailyFullUsdChfD1_pd = dailyFullUsdChfD1_pd.reset_index()
dailyFullUsdChfD1_pd

# Drop columns
dailyFullUsdChfD1_pd = dailyFullUsdChfD1_pd.drop(['na', 'Close', 'Open', 'Volume'], axis=1)
dailyFullUsdChfD1_pd

In [ ]:
# If Buy or If Sell 
mDataPositionBuy = dailyFullUsdChfD1_pd ['High'] - T2100x0400_pd ['C04']
mDataPositionBuy_pd = pd.DataFrame (mDataPositionBuy, columns = ['If Buy'])

mDataPositionSell = T2100x0400_pd ['C04'] - dailyFullUsdChfD1_pd ['Low']
mDataPositionSell_pd = pd.DataFrame (mDataPositionSell, columns = ['If Sell'])
# Print 
# mDataPositionSell_pd 
# mDataPositionBuy_pd

IfBuyIfSell_pd = pd.concat([mDataPositionBuy_pd, mDataPositionSell_pd], axis=1)

# Drop NaN
IfBuyIfSell_pd = IfBuyIfSell_pd.dropna()
IfBuyIfSell_pd

summaryTable02 = pd.concat([dailyFullUsdChfD1_pd, IfBuyIfSell_pd, BullOrBearResult_pd], axis=1)
summaryTable02

In [ ]:
# ** Capture all bull and capture all bear

tableForBuyEntry_pd = summaryTable02[(summaryTable02['Bull / Bear'] == 'bull')]
tableForSellEntry_pd = summaryTable02[(summaryTable02['Bull / Bear'] == 'bear')]

# Print
tableForBuyEntry_pd
# tableForSellEntry_pd

In [ ]:
# For buy position result
BuyPosSubResult = np.where (tableForBuyEntry_pd ['If Buy'] > 0.0008, 'Success', 'Fail')
BuyPosSubResult_pd = pd.DataFrame (BuyPosSubResult, columns = ['Buy Result'])
BuyPosSubResult_pd  

# Convert To Numpy 
BuyPosSubResult_np = BuyPosSubResult_pd.values

# Test count success 
(BuyPosSubResult_np == 'Success').sum() 

# Count Contents
countTotalResultForBuy = len(BuyPosSubResult_np)
countSuccessResultBuy = (BuyPosSubResult_np == 'Success').sum() 

WinRateForBuyPos = countSuccessResultBuy / countTotalResultForBuy
WinRateForBuyPos

In [ ]:
SellPosSubResult = np.where (tableForSellEntry_pd ['If Sell'] > 0.0008, 'Success', 'Fail')
SellPosSubResult_pd = pd.DataFrame (SellPosSubResult, columns = ['Sell Result'])
SellPosSubResult_pd  

# Convert To Numpy
SellPosSubResult_np = SellPosSubResult_pd.values
(SellPosSubResult_np == 'Success').sum()

# Count Contents
countResultForSell = len(SellPosSubResult_np)
countSuccessResultSell = (SellPosSubResult_np == 'Success').sum() 

WinRateForSell = countSuccessResultSell / countResultForSell
WinRateForSell