In [1]:
# Nostradamus One: NTS Framework for all pairs.
import pandas as pd
import numpy as np

In [4]:
hourlyFullUsdChf_pd = pd.read_csv('datasets/2018-05-02-UsdChfH1.csv')

In [ ]:
mDataTime2100_pd = hourlyFullUsdChf_pd [(hourlyFullUsdChf_pd['Time'] == '21:00')]

In [ ]:
mDataTime0400_pd = hourlyFullUsdChf_pd [(hourlyFullUsdChf_pd['Time'] == '04:00')]
mDataTime0400_pd.columns = ['T04', 'OO4','H04','L04','C04', 'V04']


mDataTime2100_pd = hourlyFullUsdChf_pd [(hourlyFullUsdChf_pd['Time'] == '21:00')]
mDataTime2100_pd.columns = ['T21', 'O21','H21','L21','C21', 'V21']

In [ ]:
concat0421Table = pd.concat([mDataTime0400_pd, mDataTime2100_pd], axis=1)
concat0421Table

In [ ]:
mDataBullBear = concat0421Table ['C21'] - concat0421Table ['C04']
# mDataBullBear

mDataBullBear_pd = pd.DataFrame (mDataBullBear, columns = ['BlBr Calc'])
# mDataBullBear_pd

concat0421BlBrTable_pd = pd.concat([concat0421Table, mDataBullBear_pd], axis=1)
# concat0421BlBrTable_pd

mDataBullBearResult = np.where (concat0421BlBrTable_pd ['BlBr Calc'] > 0, 'bull', 'bear')
mDataBullBearResult_pd = pd.DataFrame (mDataBullBearResult, columns = ['Bull or Bear'])

# mDataBullBearResult_pd 
concat0421BlBrResTable_pd = pd.concat([concat0421BlBrTable_pd, mDataBullBearResult_pd], axis=1)
concat0421BlBrResTable_pd

In [ ]:
mDataBullBearResult_pd

In [6]:
dailyFullUsdChfD1_pd = pd.read_csv('datasets/2018-05-02-UsdChfD1.csv')
dailyFullUsdChfD1_pd
dailyFullUsdChfD1_pd.columns = ['0', '0','DHigh','DLow','0', '0']
dailyFullUsdChfD1_pd

                0        0    DHigh     DLow        0      0
2017.11.08  00:00  0.99826  1.00056  0.99803  0.99978  40766
2017.11.09  00:00  0.99978  1.00168  0.99209  0.99388  53577
2017.11.10  00:00  0.99385  0.99676  0.99246  0.99572  39826
2017.11.12  00:00  0.99637  0.99660  0.99520  0.99655   2831
2017.11.13  00:00  0.99655  0.99861  0.99359  0.99639  35152
2017.11.14  00:00  0.99640  0.99698  0.98811  0.98965  33654
2017.11.15  00:00  0.98965  0.99102  0.98456  0.98842  53039
2017.11.16  00:00  0.98843  0.99446  0.98819  0.99342  47095
2017.11.17  00:00  0.99343  0.99350  0.98753  0.98825  49287
2017.11.19  00:00  0.98842  0.98999  0.98796  0.98945   4577
2017.11.20  00:00  0.98945  0.99364  0.98781  0.99321  51506
2017.11.21  00:00  0.99321  0.99460  0.98984  0.99048  36945
2017.11.22  00:00  0.99048  0.99101  0.98081  0.98208  50342
2017.11.23  00:00  0.98207  0.98272  0.97944  0.98158  41805
2017.11.24  00:00  0.98158  0.98264  0.97849  0.97929  38931
2017.11.26  00:00  0.97849  0.98044  0.97813  0.98029   3054
2017.11.27  00:00  0.98028  0.98188  0.97779  0.98124  45906
2017.11.28  00:00  0.98124  0.98519  0.98017  0.98402  54226
2017.11.29  00:00  0.98402  0.98690  0.98180  0.98443  53029
2017.11.30  00:00  0.98444  0.98813  0.98152  0.98393  55224
2017.12.01  00:00  0.98392  0.98697  0.97343  0.97561  61930
2017.12.03  00:00  0.98150  0.98236  0.97928  0.98227   3130
2017.12.04  00:00  0.98228  0.98661  0.98106  0.98459  53051
2017.12.05  00:00  0.98460  0.98867  0.98365  0.98745  50014
2017.12.06  00:00  0.98745  0.99087  0.98543  0.98924  49450
2017.12.07  00:00  0.98925  0.99467  0.98909  0.99464  45282
2017.12.08  00:00  0.99465  0.99769  0.99224  0.99254  43455
2017.12.10  00:00  0.99375  0.99403  0.99230  0.99288   1730
2017.12.11  00:00  0.99287  0.99297  0.98965  0.99133  41092
2017.12.12  00:00  0.99134  0.99350  0.98896  0.99141  40526
...           ...      ...      ...      ...      ...    ...
2018.01.31  00:00  0.93459  0.93583  0.92887  0.93126  53039
2018.02.01  00:00  0.93125  0.93410  0.92554  0.92596  50556
2018.02.02  00:00  0.92597  0.93357  0.92575  0.93087  51698
2018.02.04  00:00  0.93201  0.93268  0.93075  0.93120   3470
2018.02.05  00:00  0.93121  0.93756  0.92866  0.93130  53018
2018.02.06  00:00  0.93129  0.93971  0.93059  0.93611  69602
2018.02.07  00:00  0.93611  0.94536  0.93393  0.94247  51687
2018.02.08  00:00  0.94247  0.94691  0.93476  0.93507  59909
2018.02.09  00:00  0.93507  0.94080  0.93507  0.93934  55884
2018.02.11  00:00  0.93955  0.94033  0.93910  0.93963   2122
2018.02.12  00:00  0.93963  0.94008  0.93629  0.93873  37930
2018.02.13  00:00  0.93874  0.93978  0.93218  0.93524  38584
2018.02.14  00:00  0.93524  0.93734  0.92720  0.92747  48461
2018.02.15  00:00  0.92748  0.92905  0.92095  0.92220  45563
2018.02.16  00:00  0.92219  0.92868  0.91870  0.92732  42314
2018.02.18  00:00  0.92724  0.92784  0.92633  0.92721   1462
2018.02.19  00:00  0.92720  0.93191  0.92622  0.92930  32211
2018.02.20  00:00  0.92931  0.93685  0.92889  0.93621  37329
2018.02.21  00:00  0.93624  0.93959  0.93423  0.93866  42810
2018.02.22  00:00  0.93868  0.94083  0.93215  0.93313  38470
2018.02.23  00:00  0.93312  0.93733  0.93271  0.93595  33139
2018.02.25  00:00  0.93620  0.93732  0.93548  0.93712   2199
2018.02.26  00:00  0.93713  0.93904  0.93249  0.93861  34404
2018.02.27  00:00  0.93862  0.94165  0.93576  0.93943  40839
2018.02.28  00:00  0.93944  0.94576  0.93870  0.94443  40254
2018.03.01  00:00  0.94444  0.94897  0.94095  0.94144  60266
2018.03.02  00:00  0.94142  0.94238  0.93378  0.93708  69123
2018.03.04  00:00  0.93463  0.93787  0.93452  0.93706   4385
2018.03.05  00:00  0.93706  0.94075  0.93525  0.93975  67828
2018.03.06  00:00  0.93976  0.94182  0.93591  0.93796  44379

[102 rows x 6 columns]

In [ ]:
# If Buy of If Sell 
mDataPositionBuy = dailyFullUsdChfD1_pd ['DHigh'] - concat0421Table ['C04']
mDataPositionBuy_pd = pd.DataFrame (mDataPositionBuy, columns = ['If Buy'])
# Print
# DataPositionBuy_pd

mDataPositionSell = concat0421Table ['C04'] - dailyFullUsdChfD1_pd ['DLow']
mDataPositionSell_pd = pd.DataFrame (mDataPositionSell, columns = ['If Sell'])
# Print 
# mDataPositionSell_pd 

concatIfBuySell_pd = pd.concat([mDataPositionBuy_pd, mDataPositionSell_pd], axis=1)
# concatIfBuySell_pd

# concatIfBuySellBlBr_pd = pd.concat((DataBullBearResult_pd, concatIfBuySell_pd), ignore_index=True, axis=1)
# concatIfBuySellBlBr_pd

# concatIfBuySell_pd
# mDataBullBearResult_pd

# Convert to Numpy
concatIfBuySell_np = concatIfBuySell_pd.values
# concatIfBuySell_pd

mDataBullBearResult_np = mDataBullBearResult_pd.values
# ** Print
# mDataBullBearResult_pd

concatIfBuySell_pd = concatIfBuySell_pd.reset_index(drop=True)
concatIfBuySell_pd

concatIfBuySellBlBrRes_pd = pd.concat([concatIfBuySell_pd, mDataBullBearResult_pd], axis=1)
concatIfBuySellBlBrRes_pd

In [ ]:
BuyPosSubResult = np.where (concatIfBuySellBlBrRes_pd ['If Buy'] > 0.000125, 'Success', 'Fail')
BuyPosSubResult_pd = pd.DataFrame (BuyPosSubResult, columns = ['Buy Result'])
BuyPosSubResult_pd

# concatIfBuySellBlBrRes_pd

In [ ]:
# Convert To Numpy
BuyPosSubResult_np = BuyPosSubResult_pd.values
(BuyPosSubResult_np == 'Success').sum()

In [ ]:
# Conditional statement for 2 Arguments
# rShapeData1_pd[(rShapeData1_pd['Day'] == 5) & (rShapeData1_pd['UpOrDown'] > 0)]
resultBull = concatIfBuySellBlBrRes_pd['If Bull'] > = 0.000125 & (concatIfBuySellBlBrRes_pd['Bull or Bear'] == Bull)