In [5]:
import pandas as pd
import numpy as np

H1_UsdChf_pd = pd.read_csv('datasets/2018-05-02-UsdChfH1.csv')
D1_UsdChf_pd = pd.read_csv('datasets/2018-05-02-UsdChfD1.csv')

In [9]:
# hourlyFullUsdChf_pd.drop(['Volume'], axis=1)

# df.drop(['B', 'C'], axis=1)
# df.drop(columns=['B', 'C'])

# H1_UsdChf_pd.drop(columns='Volume')
# H1_UsdChf_pd.drop('Close', axis=1)

# H1_UsdChf_pd.drop(['Volume'], axis = 1, inplace = True)

# H1_UsdChf_pd.loc[:, :'1573']


H1_UsdChf_Reshaped01_pd = H1_UsdChf_pd.drop(H1_UsdChf_pd.columns[[1, 4]], axis=1, inplace=False)
H1_UsdChf_Reshaped01_pd

             Time     High      Low   Volume
2017.11.08  01:00  0.99928  0.99862     1573
2017.11.08  02:00  0.99903  0.99849     1496
2017.11.08  03:00  0.99892  0.99855     1158
2017.11.08  04:00  0.99881  0.99839      707
2017.11.08  05:00  0.99878  0.99839      913
2017.11.08  06:00  0.99965  0.99869     1504
2017.11.08  07:00  0.99941  0.99835     1756
2017.11.08  08:00  0.99931  0.99829     2269
2017.11.08  09:00  0.99918  0.99835     1672
2017.11.08  10:00  0.99910  0.99830     1744
2017.11.08  11:00  0.99889  0.99814     1661
2017.11.08  12:00  0.99952  0.99854     2000
2017.11.08  13:00  1.00019  0.99866     2283
2017.11.08  14:00  1.00035  0.99937     2366
2017.11.08  15:00  1.00017  0.99909     2729
2017.11.08  16:00  1.00056  0.99875     2348
2017.11.08  17:00  1.00025  0.99929     1432
2017.11.08  18:00  1.00039  0.99955     1432
2017.11.08  19:00  1.00050  0.99979     1410
2017.11.08  20:00  1.00015  0.99980     1918
2017.11.08  21:00  1.00031  0.99945     1544
2017.11.08  22:00  1.00005  0.99937     1454
2017.11.08  23:00  1.00003  0.99950     1714
2017.11.09  00:00  1.00047  0.99967     1491
2017.11.09  01:00  1.00050  0.99947     1571
2017.11.09  02:00  0.99987  0.99930     1522
2017.11.09  03:00  0.99997  0.99933     1836
2017.11.09  04:00  0.99998  0.99898     1429
2017.11.09  05:00  0.99908  0.99803     2410
2017.11.09  06:00  0.99870  0.99735     1669
...           ...      ...      ...      ...
2018.03.09  14:00  0.95101  0.94945     5066
2018.03.09  15:00  0.95104  0.94907     4747
2018.03.09  16:00  0.95033  0.94871     3837
2018.03.09  17:00  0.95016  0.94884     3357
2018.03.09  18:00  0.95094  0.94964     2489
2018.03.09  19:00  0.95115  0.95056     2321
2018.03.09  20:00  0.95143  0.95060     2957
2018.03.09  21:00  0.95143  0.95103     1295
2018.03.11  21:00  0.95120  0.94968      375
2018.03.11  22:00  0.95133  0.95088      630
2018.03.11  23:00  0.95121  0.95073     1111
2018.03.12  00:00  0.95107  0.95026     1600
2018.03.12  01:00  0.95102  0.94987     2075
2018.03.12  02:00  0.95024  0.94976     1766
2018.03.12  03:00  0.95002  0.94971     1387
2018.03.12  04:00  0.94991  0.94921     1724
2018.03.12  05:00  0.95011  0.94928     1661
2018.03.12  06:00  0.95025  0.94969     1526
2018.03.12  07:00  0.95018  0.94859     3015
2018.03.12  08:00  0.94983  0.94845     3082
2018.03.12  09:00  0.94971  0.94846     2527
2018.03.12  10:00  0.95000  0.94916     2282
2018.03.12  11:00  0.95078  0.94962     2887
2018.03.12  12:00  0.95051  0.94962     3190
2018.03.12  13:00  0.95014  0.94862     3508
2018.03.12  14:00  0.94986  0.94782     3965
2018.03.12  15:00  0.94891  0.94735     3648
2018.03.12  16:00  0.94920  0.94778     3236
2018.03.12  17:00  0.94873  0.94716     2267
2018.03.12  18:00  0.94763  0.94599     1763

[2081 rows x 4 columns]