In [50]:
import pandas as pd
import numpy as np

 
D1_UsdChf_pd = pd.read_csv('datasets/2018-05-02-UsdChfD1.csv')

In [53]:
# Drop "Volume" column

H1_UsdChf_Reshaped01_pd = H1_UsdChf_pd.drop(H1_UsdChf_pd.columns[[-1, -1]], axis=1)
# H1_UsdChf_Reshaped01_pd

D1_UsdChf_Reshaped01_pd = D1_UsdChf_pd.drop(D1_UsdChf_pd.columns[[0, -1]], axis=1)
# D1_UsdChf_Reshaped01_pd

In [54]:
H1_UsdChf_Reshaped01_pd

             Time     Open     High      Low    Close
2017.11.08  01:00  0.99917  0.99928  0.99862  0.99876
2017.11.08  02:00  0.99876  0.99903  0.99849  0.99885
2017.11.08  03:00  0.99883  0.99892  0.99855  0.99877
2017.11.08  04:00  0.99877  0.99881  0.99839  0.99854
2017.11.08  05:00  0.99854  0.99878  0.99839  0.99875
2017.11.08  06:00  0.99875  0.99965  0.99869  0.99910
2017.11.08  07:00  0.99911  0.99941  0.99835  0.99905
2017.11.08  08:00  0.99900  0.99931  0.99829  0.99867
2017.11.08  09:00  0.99867  0.99918  0.99835  0.99907
2017.11.08  10:00  0.99909  0.99910  0.99830  0.99850
2017.11.08  11:00  0.99851  0.99889  0.99814  0.99866
2017.11.08  12:00  0.99867  0.99952  0.99854  0.99914
2017.11.08  13:00  0.99912  1.00019  0.99866  1.00008
2017.11.08  14:00  1.00010  1.00035  0.99937  0.99972
2017.11.08  15:00  0.99972  1.00017  0.99909  0.99998
2017.11.08  16:00  0.99998  1.00056  0.99875  0.99964
2017.11.08  17:00  0.99965  1.00025  0.99929  0.99994
2017.11.08  18:00  0.99994  1.00039  0.99955  1.00010
2017.11.08  19:00  1.00010  1.00050  0.99979  1.00014
2017.11.08  20:00  1.00012  1.00015  0.99980  0.99989
2017.11.08  21:00  0.99990  1.00031  0.99945  0.99996
2017.11.08  22:00  0.99993  1.00005  0.99937  0.99986
2017.11.08  23:00  0.99986  1.00003  0.99950  0.99978
2017.11.09  00:00  0.99978  1.00047  0.99967  1.00019
2017.11.09  01:00  1.00020  1.00050  0.99947  0.99955
2017.11.09  02:00  0.99958  0.99987  0.99930  0.99980
2017.11.09  03:00  0.99977  0.99997  0.99933  0.99993
2017.11.09  04:00  0.99993  0.99998  0.99898  0.99907
2017.11.09  05:00  0.99906  0.99908  0.99803  0.99851
2017.11.09  06:00  0.99853  0.99870  0.99735  0.99774
...           ...      ...      ...      ...      ...
2018.03.09  14:00  0.95030  0.95101  0.94945  0.95051
2018.03.09  15:00  0.95053  0.95104  0.94907  0.94997
2018.03.09  16:00  0.95000  0.95033  0.94871  0.94920
2018.03.09  17:00  0.94920  0.95016  0.94884  0.94992
2018.03.09  18:00  0.94991  0.95094  0.94964  0.95088
2018.03.09  19:00  0.95088  0.95115  0.95056  0.95076
2018.03.09  20:00  0.95077  0.95143  0.95060  0.95104
2018.03.09  21:00  0.95104  0.95143  0.95103  0.95116
2018.03.11  21:00  0.95033  0.95120  0.94968  0.95102
2018.03.11  22:00  0.95101  0.95133  0.95088  0.95108
2018.03.11  23:00  0.95107  0.95121  0.95073  0.95084
2018.03.12  00:00  0.95085  0.95107  0.95026  0.95055
2018.03.12  01:00  0.95055  0.95102  0.94987  0.95004
2018.03.12  02:00  0.95007  0.95024  0.94976  0.94983
2018.03.12  03:00  0.94984  0.95002  0.94971  0.94981
2018.03.12  04:00  0.94982  0.94991  0.94921  0.94929
2018.03.12  05:00  0.94930  0.95011  0.94928  0.94999
2018.03.12  06:00  0.94997  0.95025  0.94969  0.94980
2018.03.12  07:00  0.94981  0.95018  0.94859  0.94943
2018.03.12  08:00  0.94944  0.94983  0.94845  0.94846
2018.03.12  09:00  0.94849  0.94971  0.94846  0.94969
2018.03.12  10:00  0.94970  0.95000  0.94916  0.94973
2018.03.12  11:00  0.94975  0.95078  0.94962  0.95046
2018.03.12  12:00  0.95043  0.95051  0.94962  0.94977
2018.03.12  13:00  0.94978  0.95014  0.94862  0.94868
2018.03.12  14:00  0.94872  0.94986  0.94782  0.94788
2018.03.12  15:00  0.94787  0.94891  0.94735  0.94883
2018.03.12  16:00  0.94887  0.94920  0.94778  0.94843
2018.03.12  17:00  0.94842  0.94873  0.94716  0.94754
2018.03.12  18:00  0.94756  0.94763  0.94599  0.94615

[2081 rows x 5 columns]