In [3]:
import pandas as pd

In [4]:
import numpy as nm

In [5]:
mDataFullUsdChfD1 = pd.read_csv ('UsdChfD1.csv')

In [6]:
mDataFullUsdChfD1

      2014.11.06  00:00  0.96445  0.97374  0.96025  0.97287  57161
0     2014.11.07  00:00  0.97286  0.97398  0.96508  0.96612  56569
1     2014.11.09  00:00  0.96369  0.96545  0.96333  0.96528   2550
2     2014.11.10  00:00  0.96529  0.96838  0.96158  0.96790  52460
3     2014.11.11  00:00  0.96789  0.97000  0.96240  0.96444  45381
4     2014.11.12  00:00  0.96445  0.96795  0.96219  0.96703  67538
5     2014.11.13  00:00  0.96703  0.96721  0.96217  0.96366  55798
6     2014.11.14  00:00  0.96365  0.96880  0.95730  0.95866  63666
7     2014.11.16  00:00  0.95859  0.95991  0.95788  0.95923   2152
8     2014.11.17  00:00  0.95924  0.96539  0.95517  0.96481  47761
9     2014.11.18  00:00  0.96475  0.96489  0.95740  0.95850  29295
10    2014.11.19  00:00  0.95849  0.96003  0.95295  0.95790  46385
11    2014.11.20  00:00  0.95789  0.96053  0.95524  0.95838  66955
12    2014.11.21  00:00  0.95841  0.97085  0.95624  0.96952  66246
13    2014.11.23  00:00  0.97218  0.97295  0.97139  0.97164   2892
14    2014.11.24  00:00  0.97159  0.97201  0.96621  0.96705  50602
15    2014.11.25  00:00  0.96704  0.96971  0.96341  0.96353  30614
16    2014.11.26  00:00  0.96349  0.96652  0.95942  0.96122  35890
17    2014.11.27  00:00  0.96122  0.96488  0.95980  0.96460  42169
18    2014.11.28  00:00  0.96459  0.96699  0.96208  0.96463  46873
19    2014.11.30  00:00  0.96501  0.96815  0.96479  0.96774   3097
20    2014.12.01  00:00  0.96774  0.96871  0.96145  0.96456  59811
21    2014.12.02  00:00  0.96457  0.97292  0.96409  0.97188  47414
22    2014.12.03  00:00  0.97189  0.97824  0.97140  0.97721  53788
23    2014.12.04  00:00  0.97721  0.97939  0.96485  0.97070  66228
24    2014.12.05  00:00  0.97069  0.97991  0.97015  0.97863  54722
25    2014.12.07  00:00  0.97883  0.97927  0.97747  0.97837   2208
26    2014.12.08  00:00  0.97840  0.98172  0.97375  0.97624  52422
27    2014.12.09  00:00  0.97624  0.97772  0.96531  0.97043  68448
28    2014.12.10  00:00  0.97044  0.97217  0.96375  0.96398  64670
29    2014.12.11  00:00  0.96397  0.97101  0.96269  0.96918  68541
...          ...    ...      ...      ...      ...      ...    ...
995   2018.01.23  00:00  0.96204  0.96328  0.95643  0.95671  39242
996   2018.01.24  00:00  0.95672  0.95755  0.94262  0.94637  48192
997   2018.01.25  00:00  0.94636  0.94657  0.92885  0.94173  66593
998   2018.01.26  00:00  0.94173  0.94243  0.93230  0.93329  54976
999   2018.01.28  00:00  0.93303  0.93481  0.93303  0.93340   2592
1000  2018.01.29  00:00  0.93342  0.93861  0.93342  0.93737  48835
1001  2018.01.30  00:00  0.93738  0.93927  0.93095  0.93460  51530
1002  2018.01.31  00:00  0.93459  0.93583  0.92887  0.93126  53039
1003  2018.02.01  00:00  0.93125  0.93410  0.92554  0.92596  50556
1004  2018.02.02  00:00  0.92597  0.93357  0.92575  0.93087  51698
1005  2018.02.04  00:00  0.93201  0.93268  0.93075  0.93120   3470
1006  2018.02.05  00:00  0.93121  0.93756  0.92866  0.93130  53018
1007  2018.02.06  00:00  0.93129  0.93971  0.93059  0.93611  69602
1008  2018.02.07  00:00  0.93611  0.94536  0.93393  0.94247  51687
1009  2018.02.08  00:00  0.94247  0.94691  0.93476  0.93507  59909
1010  2018.02.09  00:00  0.93507  0.94080  0.93507  0.93934  55884
1011  2018.02.11  00:00  0.93955  0.94033  0.93910  0.93963   2122
1012  2018.02.12  00:00  0.93963  0.94008  0.93629  0.93873  37930
1013  2018.02.13  00:00  0.93874  0.93978  0.93218  0.93524  38584
1014  2018.02.14  00:00  0.93524  0.93734  0.92720  0.92747  48461
1015  2018.02.15  00:00  0.92748  0.92905  0.92095  0.92220  45563
1016  2018.02.16  00:00  0.92219  0.92868  0.91870  0.92732  42314
1017  2018.02.18  00:00  0.92724  0.92784  0.92633  0.92721   1462
1018  2018.02.19  00:00  0.92720  0.93191  0.92622  0.92930  32211
1019  2018.02.20  00:00  0.92931  0.93685  0.92889  0.93621  37329
1020  2018.02.21  00:00  0.93624  0.93959  0.93423  0.93866  42810
1021  2018.02.22  00:00  0.93868  0.94083  0.93215  0.93313  38470
1022  2018.02.23  00:00  0.93312  0.93733  0.93271  0.93595  33139
1023  2018.02.25  00:00  0.93620  0.93732  0.93548  0.93712   2199
1024  2018.02.26  00:00  0.93713  0.93715  0.93249  0.93327  14951

[1025 rows x 7 columns]