In [1]:
# Nostradamus One: Noon Time Show System
import pandas as pd
import numpy as np

In [49]:
mDataFullUsdChfH1_pd = pd.read_csv('USDCHFH1.csv')
mDataFullUsdChfD1_pd = pd.read_csv('UsdChfD1Clean101.csv')

In [23]:
mDataFullUsdChfH1_pd

             Time     Open     High      Low    Close   Volume
2017.11.08  01:00  0.99917  0.99928  0.99862  0.99876     1573
2017.11.08  02:00  0.99876  0.99903  0.99849  0.99885     1496
2017.11.08  03:00  0.99883  0.99892  0.99855  0.99877     1158
2017.11.08  04:00  0.99877  0.99881  0.99839  0.99854      707
2017.11.08  05:00  0.99854  0.99878  0.99839  0.99875      913
2017.11.08  06:00  0.99875  0.99965  0.99869  0.99910     1504
2017.11.08  07:00  0.99911  0.99941  0.99835  0.99905     1756
2017.11.08  08:00  0.99900  0.99931  0.99829  0.99867     2269
2017.11.08  09:00  0.99867  0.99918  0.99835  0.99907     1672
2017.11.08  10:00  0.99909  0.99910  0.99830  0.99850     1744
2017.11.08  11:00  0.99851  0.99889  0.99814  0.99866     1661
2017.11.08  12:00  0.99867  0.99952  0.99854  0.99914     2000
2017.11.08  13:00  0.99912  1.00019  0.99866  1.00008     2283
2017.11.08  14:00  1.00010  1.00035  0.99937  0.99972     2366
2017.11.08  15:00  0.99972  1.00017  0.99909  0.99998     2729
2017.11.08  16:00  0.99998  1.00056  0.99875  0.99964     2348
2017.11.08  17:00  0.99965  1.00025  0.99929  0.99994     1432
2017.11.08  18:00  0.99994  1.00039  0.99955  1.00010     1432
2017.11.08  19:00  1.00010  1.00050  0.99979  1.00014     1410
2017.11.08  20:00  1.00012  1.00015  0.99980  0.99989     1918
2017.11.08  21:00  0.99990  1.00031  0.99945  0.99996     1544
2017.11.08  22:00  0.99993  1.00005  0.99937  0.99986     1454
2017.11.08  23:00  0.99986  1.00003  0.99950  0.99978     1714
2017.11.09  00:00  0.99978  1.00047  0.99967  1.00019     1491
2017.11.09  01:00  1.00020  1.00050  0.99947  0.99955     1571
2017.11.09  02:00  0.99958  0.99987  0.99930  0.99980     1522
2017.11.09  03:00  0.99977  0.99997  0.99933  0.99993     1836
2017.11.09  04:00  0.99993  0.99998  0.99898  0.99907     1429
2017.11.09  05:00  0.99906  0.99908  0.99803  0.99851     2410
2017.11.09  06:00  0.99853  0.99870  0.99735  0.99774     1669
...           ...      ...      ...      ...      ...      ...
2018.03.09  14:00  0.95030  0.95101  0.94945  0.95051     5066
2018.03.09  15:00  0.95053  0.95104  0.94907  0.94997     4747
2018.03.09  16:00  0.95000  0.95033  0.94871  0.94920     3837
2018.03.09  17:00  0.94920  0.95016  0.94884  0.94992     3357
2018.03.09  18:00  0.94991  0.95094  0.94964  0.95088     2489
2018.03.09  19:00  0.95088  0.95115  0.95056  0.95076     2321
2018.03.09  20:00  0.95077  0.95143  0.95060  0.95104     2957
2018.03.09  21:00  0.95104  0.95143  0.95103  0.95116     1295
2018.03.11  21:00  0.95033  0.95120  0.94968  0.95102      375
2018.03.11  22:00  0.95101  0.95133  0.95088  0.95108      630
2018.03.11  23:00  0.95107  0.95121  0.95073  0.95084     1111
2018.03.12  00:00  0.95085  0.95107  0.95026  0.95055     1600
2018.03.12  01:00  0.95055  0.95102  0.94987  0.95004     2075
2018.03.12  02:00  0.95007  0.95024  0.94976  0.94983     1766
2018.03.12  03:00  0.94984  0.95002  0.94971  0.94981     1387
2018.03.12  04:00  0.94982  0.94991  0.94921  0.94929     1724
2018.03.12  05:00  0.94930  0.95011  0.94928  0.94999     1661
2018.03.12  06:00  0.94997  0.95025  0.94969  0.94980     1526
2018.03.12  07:00  0.94981  0.95018  0.94859  0.94943     3015
2018.03.12  08:00  0.94944  0.94983  0.94845  0.94846     3082
2018.03.12  09:00  0.94849  0.94971  0.94846  0.94969     2527
2018.03.12  10:00  0.94970  0.95000  0.94916  0.94973     2282
2018.03.12  11:00  0.94975  0.95078  0.94962  0.95046     2887
2018.03.12  12:00  0.95043  0.95051  0.94962  0.94977     3190
2018.03.12  13:00  0.94978  0.95014  0.94862  0.94868     3508
2018.03.12  14:00  0.94872  0.94986  0.94782  0.94788     3965
2018.03.12  15:00  0.94787  0.94891  0.94735  0.94883     3648
2018.03.12  16:00  0.94887  0.94920  0.94778  0.94843     3236
2018.03.12  17:00  0.94842  0.94873  0.94716  0.94754     2267
2018.03.12  18:00  0.94756  0.94763  0.94599  0.94615     1763

[2081 rows x 6 columns]

In [37]:
# Noon Time Range is 21:00 to 04:00 (6am to 1pm Philippine Time)
mDataTime2100_pd = mDataFullUsdChfH1_pd [(mDataFullUsdChfH1_pd['Time'] == '21:00')]
mDataTime2100_pd

             Time     Open     High      Low    Close   Volume
2017.11.08  21:00  0.99990  1.00031  0.99945  0.99996     1544
2017.11.09  21:00  0.99416  0.99434  0.99359  0.99359     1479
2017.11.10  21:00  0.99571  0.99605  0.99519  0.99572     1286
2017.11.12  21:00  0.99637  0.99644  0.99547  0.99575      111
2017.11.13  21:00  0.99592  0.99620  0.99589  0.99611      971
2017.11.14  21:00  0.98946  0.98977  0.98908  0.98924      906
2017.11.15  21:00  0.98806  0.98853  0.98779  0.98822     1766
2017.11.16  21:00  0.99391  0.99423  0.99338  0.99388     1911
2017.11.17  21:00  0.98847  0.98929  0.98823  0.98825     1365
2017.11.19  21:00  0.98842  0.98881  0.98842  0.98872       37
2017.11.20  21:00  0.99359  0.99360  0.99294  0.99330     1514
2017.11.21  21:00  0.99123  0.99160  0.99098  0.99131     1050
2017.11.22  21:00  0.98187  0.98200  0.98139  0.98144     1705
2017.11.23  21:00  0.98105  0.98190  0.98074  0.98166     2220
2017.11.24  21:00  0.97931  0.97972  0.97852  0.97929     3764
2017.11.26  21:00  0.97849  0.97976  0.97813  0.97917      240
2017.11.27  21:00  0.98156  0.98188  0.98107  0.98135     1060
2017.11.28  21:00  0.98436  0.98436  0.98317  0.98381     1556
2017.11.29  21:00  0.98414  0.98450  0.98380  0.98439     1379
2017.11.30  21:00  0.98361  0.98364  0.98282  0.98338     1787
2017.12.01  21:00  0.97647  0.97663  0.97534  0.97561     1217
2017.12.03  21:00  0.98150  0.98152  0.98085  0.98134      122
2017.12.04  21:00  0.98539  0.98552  0.98467  0.98476     2010
2017.12.05  21:00  0.98736  0.98759  0.98693  0.98719     1074
2017.12.06  21:00  0.98980  0.98999  0.98953  0.98972     1230
2017.12.07  21:00  0.99421  0.99457  0.99414  0.99421     1268
2017.12.08  21:00  0.99284  0.99291  0.99224  0.99254     1363
2017.12.10  21:00  0.99375  0.99403  0.99368  0.99376       30
2017.12.11  21:00  0.99174  0.99203  0.99161  0.99170     1460
2017.12.12  21:00  0.99115  0.99142  0.99085  0.99137     1124
...           ...      ...      ...      ...      ...      ...
2018.02.05  21:00  0.93436  0.93467  0.92944  0.93104     3235
2018.02.06  21:00  0.93705  0.93743  0.93539  0.93584     1275
2018.02.07  21:00  0.94368  0.94412  0.94241  0.94370     1381
2018.02.08  21:00  0.93599  0.93635  0.93571  0.93591     1087
2018.02.09  21:00  0.93998  0.93998  0.93913  0.93934     1403
2018.02.11  21:00  0.93955  0.93968  0.93955  0.93956        6
2018.02.12  21:00  0.93903  0.93951  0.93887  0.93899     1197
2018.02.13  21:00  0.93506  0.93514  0.93467  0.93467      794
2018.02.14  21:00  0.92898  0.92958  0.92889  0.92928     1288
2018.02.15  21:00  0.92149  0.92222  0.92145  0.92188      896
2018.02.16  21:00  0.92763  0.92763  0.92685  0.92732     1091
2018.02.18  21:00  0.92724  0.92735  0.92724  0.92735        2
2018.02.19  21:00  0.92878  0.92905  0.92839  0.92899     2069
2018.02.20  21:00  0.93576  0.93630  0.93576  0.93602      928
2018.02.21  21:00  0.93828  0.93894  0.93765  0.93863     1503
2018.02.22  21:00  0.93292  0.93317  0.93265  0.93273      913
2018.02.23  21:00  0.93667  0.93702  0.93585  0.93595     1361
2018.02.25  21:00  0.93620  0.93698  0.93548  0.93698       17
2018.02.26  21:00  0.93806  0.93833  0.93759  0.93777      790
2018.02.27  21:00  0.93902  0.93930  0.93880  0.93884      749
2018.02.28  21:00  0.94432  0.94457  0.94394  0.94442      724
2018.03.01  21:00  0.94225  0.94225  0.94151  0.94161     1790
2018.03.02  21:00  0.93714  0.93782  0.93700  0.93708     1603
2018.03.04  21:00  0.93463  0.93693  0.93455  0.93624      234
2018.03.05  21:00  0.94010  0.94028  0.93969  0.93972     1347
2018.03.06  21:00  0.94083  0.94088  0.93997  0.94055     1395
2018.03.07  21:00  0.94304  0.94345  0.94271  0.94335     1718
2018.03.08  21:00  0.95093  0.95116  0.95056  0.95091     1765
2018.03.09  21:00  0.95104  0.95143  0.95103  0.95116     1295
2018.03.11  21:00  0.95033  0.95120  0.94968  0.95102      375

[101 rows x 6 columns]

In [33]:
mDataTime0400_pd = mDataFullUsdChfH1_pd [(mDataFullUsdChfH1_pd['Time'] == '04:00')]

In [34]:
mDataTime0400_pd

             Time     Open     High      Low    Close   Volume
2017.11.08  04:00  0.99877  0.99881  0.99839  0.99854      707
2017.11.09  04:00  0.99993  0.99998  0.99898  0.99907     1429
2017.11.10  04:00  0.99447  0.99495  0.99432  0.99488      969
2017.11.13  04:00  0.99639  0.99699  0.99634  0.99694      672
2017.11.14  04:00  0.99647  0.99655  0.99619  0.99640      520
2017.11.15  04:00  0.98866  0.98890  0.98853  0.98889      902
2017.11.16  04:00  0.98896  0.98971  0.98895  0.98949     1249
2017.11.17  04:00  0.99163  0.99236  0.99139  0.99235     1872
2017.11.20  04:00  0.98849  0.98902  0.98839  0.98901     1332
2017.11.21  04:00  0.99269  0.99311  0.99266  0.99294      466
2017.11.22  04:00  0.99068  0.99073  0.99030  0.99057     1001
2017.11.23  04:00  0.98146  0.98169  0.98133  0.98137     1097
2017.11.24  04:00  0.98193  0.98205  0.98143  0.98174      719
2017.11.27  04:00  0.98070  0.98079  0.98020  0.98037     1065
2017.11.28  04:00  0.98132  0.98162  0.98109  0.98140     1294
2017.11.29  04:00  0.98402  0.98485  0.98395  0.98485     1233
2017.11.30  04:00  0.98401  0.98452  0.98394  0.98452      994
2017.12.01  04:00  0.98374  0.98400  0.98341  0.98397     1381
2017.12.04  04:00  0.98249  0.98253  0.98210  0.98233     1027
2017.12.05  04:00  0.98439  0.98460  0.98411  0.98458     1160
2017.12.06  04:00  0.98658  0.98696  0.98579  0.98602     1899
2017.12.07  04:00  0.98934  0.98987  0.98921  0.98986      983
2017.12.08  04:00  0.99462  0.99536  0.99443  0.99524      957
2017.12.11  04:00  0.99176  0.99201  0.99175  0.99197      868
2017.12.12  04:00  0.99173  0.99193  0.99158  0.99179      800
2017.12.13  04:00  0.99000  0.99042  0.98995  0.99027      945
2017.12.14  04:00  0.98428  0.98473  0.98393  0.98462     1227
2017.12.15  04:00  0.98836  0.98885  0.98826  0.98861     1274
2017.12.18  04:00  0.99017  0.99037  0.98982  0.99036     1159
2017.12.19  04:00  0.98574  0.98578  0.98551  0.98552      662
...           ...      ...      ...      ...      ...      ...
2018.01.30  04:00  0.93727  0.93787  0.93661  0.93752     2451
2018.01.31  04:00  0.93356  0.93410  0.93315  0.93382     1573
2018.02.01  04:00  0.93134  0.93163  0.93103  0.93123     1046
2018.02.02  04:00  0.92632  0.92706  0.92630  0.92704     1119
2018.02.05  04:00  0.93076  0.93090  0.93020  0.93057     1352
2018.02.06  04:00  0.93123  0.93241  0.93067  0.93217     2509
2018.02.07  04:00  0.93531  0.93547  0.93444  0.93489     1198
2018.02.08  04:00  0.94396  0.94514  0.94384  0.94457     2119
2018.02.09  04:00  0.93761  0.93831  0.93749  0.93822     1302
2018.02.12  04:00  0.93791  0.93813  0.93762  0.93807     1192
2018.02.13  04:00  0.93906  0.93917  0.93793  0.93831     1309
2018.02.14  04:00  0.93073  0.93278  0.93068  0.93273     1791
2018.02.15  04:00  0.92750  0.92815  0.92624  0.92810     1526
2018.02.16  04:00  0.92065  0.92089  0.91895  0.91945     2693
2018.02.19  04:00  0.92745  0.92819  0.92732  0.92793     1080
2018.02.20  04:00  0.93066  0.93098  0.93017  0.93060     1028
2018.02.21  04:00  0.93716  0.93794  0.93666  0.93777     1379
2018.02.22  04:00  0.93881  0.93943  0.93873  0.93937     1052
2018.02.23  04:00  0.93439  0.93534  0.93424  0.93508     1153
2018.02.26  04:00  0.93443  0.93478  0.93424  0.93451     1034
2018.02.27  04:00  0.93762  0.93801  0.93737  0.93774      914
2018.02.28  04:00  0.93987  0.94018  0.93965  0.93996      860
2018.03.01  04:00  0.94499  0.94544  0.94478  0.94515     1073
2018.03.02  04:00  0.94015  0.94017  0.93967  0.94012     1536
2018.03.05  04:00  0.93600  0.93635  0.93599  0.93627     1510
2018.03.06  04:00  0.93909  0.93963  0.93899  0.93959     1976
2018.03.07  04:00  0.93719  0.93757  0.93681  0.93753     1651
2018.03.08  04:00  0.94293  0.94339  0.94281  0.94326     1380
2018.03.09  04:00  0.95195  0.95247  0.95173  0.95212     1964
2018.03.12  04:00  0.94982  0.94991  0.94921  0.94929     1724

[85 rows x 6 columns]

In [46]:
#Change Column Names
mDataTime0400_pd.columns = ['Time 04', 'Open 04','High 04','Low 04','Close 04','Volume 04']
mDataTime2100_pd.columns = ['Time 21', 'Open 21','High 21','Low 21','Close 21','Volume 21']

In [47]:
# Concatenate dataframes at vertical axis
result = pd.concat([mDataTime2100_pd, mDataTime0400_pd], axis=1)
result

,Time 21,Open 21,High 21,Low 21,Close 21,Volume 21,Time 04,Open 04,High 04,Low 04,Close 04,Volume 04
2017.11.08,21:00,0.99990,1.00031,0.99945,0.99996,1544.0,04:00,0.99877,0.99881,0.99839,0.99854,707.0
2017.11.09,21:00,0.99416,0.99434,0.99359,0.99359,1479.0,04:00,0.99993,0.99998,0.99898,0.99907,1429.0
2017.11.10,21:00,0.99571,0.99605,0.99519,0.99572,1286.0,04:00,0.99447,0.99495,0.99432,0.99488,969.0
2017.11.12,21:00,0.99637,0.99644,0.99547,0.99575,111.0,NaN,NaN,NaN,NaN,NaN,NaN
2017.11.13,21:00,0.99592,0.99620,0.99589,0.99611,971.0,04:00,0.99639,0.99699,0.99634,0.99694,672.0
2017.11.14,21:00,0.98946,0.98977,0.98908,0.98924,906.0,04:00,0.99647,0.99655,0.99619,0.99640,520.0
2017.11.15,21:00,0.98806,0.98853,0.98779,0.98822,1766.0,04:00,0.98866,0.98890,0.98853,0.98889,902.0
2017.11.16,21:00,0.99391,0.99423,0.99338,0.99388,1911.0,04:00,0.98896,0.98971,0.98895,0.98949,1249.0
2017.11.17,21:00,0.98847,0.98929,0.98823,0.98825,1365.0,04:00,0.99163,0.99236,0.99139,0.99235,1872.0
2017.11.19,21:00,0.98842,0.98881,0.98842,0.98872,37.0,NaN,NaN,NaN,NaN,NaN,NaN
2017.11.20,21:00,0.99359,0.99360,0.99294,0.99330,1514.0,04:00,0.98849,0.98902,0.98839,0.98901,1332.0
2017.11.21,21:00,0.99123,0.99160,0.99098,0.99131,1050.0,04:00,0.99269,0.99311,0.99266,0.99294,466.0
2017.11.22,21:00,0.98187,0.98200,0.98139,0.98144,1705.0,04:00,0.99068,0.99073,0.99030,0.99057,1001.0
2017.11.23,21:00,0.98105,0.98190,0.98074,0.98166,2220.0,04:00,0.98146,0.98169,0.98133,0.98137,1097.0
2017.11.24,21:00,0.97931,0.97972,0.97852,0.97929,3764.0,04:00,0.98193,0.98205,0.98143,0.98174,719.0
2017.11.26,21:00,0.97849,0.97976,0.97813,0.97917,240.0,NaN,NaN,NaN,NaN,NaN,NaN
2017.11.27,21:00,0.98156,0.98188,0.98107,0.98135,1060.0,04:00,0.98070,0.98079,0.98020,0.98037,1065.0
2017.11.28,21:00,0.98436,0.98436,0.98317,0.98381,1556.0,04:00,0.98132,0.98162,0.98109,0.98140,1294.0
2017.11.29,21:00,0.98414,0.98450,0.98380,0.98439,1379.0,04:00,0.98402,0.98485,0.98395,0.98485,1233.0
2017.11.30,21:00,0.98361,0.98364,0.98282,0.98338,1787.0,04:00,0.98401,0.98452,0.98394,0.98452,994.0
2017.12.01,21:00,0.97647,0.97663,0.97534,0.97561,1217.0,04:00,0.98374,0.98400,0.98341,0.98397,1381.0
2017.12.03,21:00,0.98150,0.98152,0.98085,0.98134,122.0,NaN,NaN,NaN,NaN,NaN,NaN
2017.12.04,21:00,0.98539,0.98552,0.98467,0.98476,2010.0,04:00,0.98249,0.98253,0.98210,0.98233,1027.0
2017.12.05,21:00,0.98736,0.98759,0.98693,0.98719,1074.0,04:00,0.98439,0.98460,0.98411,0.98458,1160.0
2017.12.06,21:00,0.98980,0.98999,0.98953,0.98972,1230.0,04:00,0.98658,0.98696,0.98579,0.98602,1899.0
2017.12.07,21:00,0.99421,0.99457,0.99414,0.99421,1268.0,04:00,0.98934,0.98987,0.98921,0.98986,983.0
2017.12.08,21:00,0.99284,0.99291,0.99224,0.99254,1363.0,04:00,0.99462,0.99536,0.99443,0.99524,957.0
2017.12.10,21:00,0.99375,0.99403,0.99368,0.99376,30.0,NaN,NaN,NaN,NaN,NaN,NaN
2017.12.11,21:00,0.99174,0.99203,0.99161,0.99170,1460.0,04:00,0.99176,0.99201,0.99175,0.99197,868.0
2017.12.12,21:00,0.99115,0.99142,0.99085,0.99137,1124.0,04:00,0.99173,0.99193,0.99158,0.99179,800.0
...,...,...,...,...,...,...,...,...,...,...,...,...
2018.02.06,21:00,0.93705,0.93743,0.93539,0.93584,1275.0,04:00,0.93123,0.93241,0.93067,0.93217,2509.0
2018.02.07,21:00,0.94368,0.94412,0.94241,0.94370,1381.0,04:00,0.93531,0.93547,0.93444,0.93489,1198.0
2018.02.08,21:00,0.93599,0.93635,0.93571,0.93591,1087.0,04:00,0.94396,0.94514,0.94384,0.94457,2119.0
2018.02.09,21:00,0.93998,0.93998,0.93913,0.93934,1403.0,04:00,0.93761,0.93831,0.93749,0.93822,1302.0
2018.02.11,21:00,0.93955,0.93968,0.93955,0.93956,6.0,NaN,NaN,NaN,NaN,NaN,NaN
2018.02.12,21:00,0.93903,0.93951,0.93887,0.93899,1197.0,04:00,0.93791,0.93813,0.93762,0.93807,1192.0
2018.02.13,21:00,0.93506,0.93514,0.93467,0.93467,794.0,04:00,0.93906,0.93917,0.93793,0.93831,1309.0
2018.02.14,21:00,0.92898,0.92958,0.92889,0.92928,1288.0,04:00,0.93073,0.93278,0.93068,0.93273,1791.0
2018.02.15,21:00,0.92149,0.92222,0.92145,0.92188,896.0,04:00,0.92750,0.92815,0.92624,0.92810,1526.0
2018.02.16,21:00,0.92763,0.92763,0.92685,0.92732,1091.0,04:00,0.92065,0.92089,0.91895,0.91945,2693.0
2018.02.18,21:00,0.92724,0.92735,0.92724,0.92735,2.0,NaN,NaN,NaN,NaN,NaN,NaN
2018.02.19,21:00,0.92878,0.92905,0.92839,0.92899,2069.0,04:00,0.92745,0.92819,0.92732,0.92793,1080.0
2018.02.20,21:00,0.93576,0.93630,0.93576,0.93602,928.0,04:00,0.93066,0.93098,0.93017,0.93060,1028.0
2018.02.21,21:00,0.93828,0.93894,0.93765,0.93863,1503.0,04:00,0.93716,0.93794,0.93666,0.93777,1379.0
2018.02.22,21:00,0.93292,0.93317,0.93265,0.93273,913.0,04:00,0.93881,0.93943,0.93873,0.93937,1052.0
2018.02.23,21:00,0.93667,0.93702,0.93585,0.93595,1361.0,04:00,0.93439,0.93534,0.93424,0.93508,1153.0
2018.02.25,21:00,0.93620,0.93698,0.93548,0.93698,17.0,NaN,NaN,NaN,NaN,NaN,NaN
2018.02.26,21:00,0.93806,0.93833,0.93759,0.93777,790.0,04:00,0.93443,0.93478,0.93424,0.93451,1034.0
2018.02.27,21:00,0.93902,0.93930,0.93880,0.93884,749.0,04:00,0.93762,0.93801,0.93737,0.93774,914.0
2018.02.28,21:00,0.94432,0.94457,0.94394,0.94442,724.0,04:00,0.93987,0.94018,0.93965,0.93996,860.0
2018.03.01,21:00,0.94225,0.94225,0.94151,0.94161,1790.0,04:00,0.94499,0.94544,0.94478,0.94515,1073.0
2018.03.02,21:00,0.93714,0.93782,0.93700,0.93708,1603.0,04:00,0.94015,0.94017,0.93967,0.94012,1536.0
2018.03.04,21:00,0.93463,0.93693,0.93455,0.93624,234.0,NaN,NaN,NaN,NaN,NaN,NaN
2018.03.05,21:00,0.94010,0.94028,0.93969,0.93972,1347.0,04:00,0.93600,0.93635,0.93599,0.93627,1510.0
2018.03.06,21:00,0.94083,0.94088,0.93997,0.94055,1395.0,04:00,0.93909,0.93963,0.93899,0.93959,1976.0
2018.03.07,21:00,0.94304,0.94345,0.94271,0.94335,1718.0,04:00,0.93719,0.93757,0.93681,0.93753,1651.0
2018.03.08,21:00,0.95093,0.95116,0.95056,0.95091,1765.0,04:00,0.94293,0.94339,0.94281,0.94326,1380.0
2018.03.09,21:00,0.95104,0.95143,0.95103,0.95116,1295.0,04:00,0.95195,0.95247,0.95173,0.95212,1964.0
2018.03.11,21:00,0.95033,0.95120,0.94968,0.95102,375.0,NaN,NaN,NaN,NaN,NaN,NaN
2018.03.12,NaN,NaN,NaN,NaN,NaN,NaN,04:00,0.94982,0.94991,0.94921,0.94929,1724.0

In [48]:
# Count bull candle generated from 21:00 t0 4:00
#rShapeData1_pd ['UpOrDown'] = rShapeData1_pd ['Close'] - rShapeData1_pd ['Open']

In [50]:
# Create Daily High dataframe 
mDataFullUsdChfD1_pd

            Date     na     Open     High      Low    Close  Volume
0     2014.11.16  00:00  0.95859  0.95991  0.95788  0.95923    2152
1     2014.11.17  00:00  0.95924  0.96539  0.95517  0.96481   47761
2     2014.11.18  00:00  0.96475  0.96489  0.95740  0.95850   29295
3     2014.11.19  00:00  0.95849  0.96003  0.95295  0.95790   46385
4     2014.11.20  00:00  0.95789  0.96053  0.95524  0.95838   66955
5     2014.11.21  00:00  0.95841  0.97085  0.95624  0.96952   66246
6     2014.11.23  00:00  0.97218  0.97295  0.97139  0.97164    2892
7     2014.11.24  00:00  0.97159  0.97201  0.96621  0.96705   50602
8     2014.11.25  00:00  0.96704  0.96971  0.96341  0.96353   30614
9     2014.11.26  00:00  0.96349  0.96652  0.95942  0.96122   35890
10    2014.11.27  00:00  0.96122  0.96488  0.95980  0.96460   42169
11    2014.11.28  00:00  0.96459  0.96699  0.96208  0.96463   46873
12    2014.11.30  00:00  0.96501  0.96815  0.96479  0.96774    3097
13    2014.12.01  00:00  0.96774  0.96871  0.96145  0.96456   59811
14    2014.12.02  00:00  0.96457  0.97292  0.96409  0.97188   47414
15    2014.12.03  00:00  0.97189  0.97824  0.97140  0.97721   53788
16    2014.12.04  00:00  0.97721  0.97939  0.96485  0.97070   66228
17    2014.12.05  00:00  0.97069  0.97991  0.97015  0.97863   54722
18    2014.12.07  00:00  0.97883  0.97927  0.97747  0.97837    2208
19    2014.12.08  00:00  0.97840  0.98172  0.97375  0.97624   52422
20    2014.12.09  00:00  0.97624  0.97772  0.96531  0.97043   68448
21    2014.12.10  00:00  0.97044  0.97217  0.96375  0.96398   64670
22    2014.12.11  00:00  0.96397  0.97101  0.96269  0.96918   68541
23    2014.12.12  00:00  0.96919  0.96987  0.96181  0.96371   64298
24    2014.12.14  00:00  0.96304  0.96414  0.96175  0.96373    3817
25    2014.12.15  00:00  0.96374  0.96734  0.96236  0.96540   65906
26    2014.12.16  00:00  0.96541  0.96562  0.95527  0.95979   81888
27    2014.12.17  00:00  0.95979  0.97443  0.95940  0.97334   79252
28    2014.12.18  00:00  0.97335  0.98471  0.97211  0.97983   74550
29    2014.12.19  00:00  0.97984  0.98455  0.97838  0.98348   51902
...          ...    ...      ...      ...      ...      ...     ...
1005  2018.01.31  00:00  0.93459  0.93583  0.92887  0.93126   53039
1006  2018.02.01  00:00  0.93125  0.93410  0.92554  0.92596   50556
1007  2018.02.02  00:00  0.92597  0.93357  0.92575  0.93087   51698
1008  2018.02.04  00:00  0.93201  0.93268  0.93075  0.93120    3470
1009  2018.02.05  00:00  0.93121  0.93756  0.92866  0.93130   53018
1010  2018.02.06  00:00  0.93129  0.93971  0.93059  0.93611   69602
1011  2018.02.07  00:00  0.93611  0.94536  0.93393  0.94247   51687
1012  2018.02.08  00:00  0.94247  0.94691  0.93476  0.93507   59909
1013  2018.02.09  00:00  0.93507  0.94080  0.93507  0.93934   55884
1014  2018.02.11  00:00  0.93955  0.94033  0.93910  0.93963    2122
1015  2018.02.12  00:00  0.93963  0.94008  0.93629  0.93873   37930
1016  2018.02.13  00:00  0.93874  0.93978  0.93218  0.93524   38584
1017  2018.02.14  00:00  0.93524  0.93734  0.92720  0.92747   48461
1018  2018.02.15  00:00  0.92748  0.92905  0.92095  0.92220   45563
1019  2018.02.16  00:00  0.92219  0.92868  0.91870  0.92732   42314
1020  2018.02.18  00:00  0.92724  0.92784  0.92633  0.92721    1462
1021  2018.02.19  00:00  0.92720  0.93191  0.92622  0.92930   32211
1022  2018.02.20  00:00  0.92931  0.93685  0.92889  0.93621   37329
1023  2018.02.21  00:00  0.93624  0.93959  0.93423  0.93866   42810
1024  2018.02.22  00:00  0.93868  0.94083  0.93215  0.93313   38470
1025  2018.02.23  00:00  0.93312  0.93733  0.93271  0.93595   33139
1026  2018.02.25  00:00  0.93620  0.93732  0.93548  0.93712    2199
1027  2018.02.26  00:00  0.93713  0.93904  0.93249  0.93861   34404
1028  2018.02.27  00:00  0.93862  0.94165  0.93576  0.93943   40839
1029  2018.02.28  00:00  0.93944  0.94576  0.93870  0.94443   40254
1030  2018.03.01  00:00  0.94444  0.94897  0.94095  0.94144   60266
1031  2018.03.02  00:00  0.94142  0.94238  0.93378  0.93708   69123
1032  2018.03.04  00:00  0.93463  0.93787  0.93452  0.93706    4385
1033  2018.03.05  00:00  0.93706  0.94075  0.93525  0.93975   67828
1034  2018.03.06  00:00  0.93976  0.94182  0.93591  0.93796   44379

[1035 rows x 7 columns]

In [77]:
#Slicing Daily dataframe

mDataHighDailyColumnSelect_pd = mDataFullUsdChfD1_pd.loc[:, ['Date', 'High']]
mDataHighDailySelect_pd = mDataHighDailyColumnSelect_pd.loc[933: , :]
mDataHighDailySelect_pd

            Date     High
933   2017.11.08  1.00056
934   2017.11.09  1.00168
935   2017.11.10  0.99676
936   2017.11.12  0.99660
937   2017.11.13  0.99861
938   2017.11.14  0.99698
939   2017.11.15  0.99102
940   2017.11.16  0.99446
941   2017.11.17  0.99350
942   2017.11.19  0.98999
943   2017.11.20  0.99364
944   2017.11.21  0.99460
945   2017.11.22  0.99101
946   2017.11.23  0.98272
947   2017.11.24  0.98264
948   2017.11.26  0.98044
949   2017.11.27  0.98188
950   2017.11.28  0.98519
951   2017.11.29  0.98690
952   2017.11.30  0.98813
953   2017.12.01  0.98697
954   2017.12.03  0.98236
955   2017.12.04  0.98661
956   2017.12.05  0.98867
957   2017.12.06  0.99087
958   2017.12.07  0.99467
959   2017.12.08  0.99769
960   2017.12.10  0.99403
961   2017.12.11  0.99297
962   2017.12.12  0.99350
...          ...      ...
1005  2018.01.31  0.93583
1006  2018.02.01  0.93410
1007  2018.02.02  0.93357
1008  2018.02.04  0.93268
1009  2018.02.05  0.93756
1010  2018.02.06  0.93971
1011  2018.02.07  0.94536
1012  2018.02.08  0.94691
1013  2018.02.09  0.94080
1014  2018.02.11  0.94033
1015  2018.02.12  0.94008
1016  2018.02.13  0.93978
1017  2018.02.14  0.93734
1018  2018.02.15  0.92905
1019  2018.02.16  0.92868
1020  2018.02.18  0.92784
1021  2018.02.19  0.93191
1022  2018.02.20  0.93685
1023  2018.02.21  0.93959
1024  2018.02.22  0.94083
1025  2018.02.23  0.93733
1026  2018.02.25  0.93732
1027  2018.02.26  0.93904
1028  2018.02.27  0.94165
1029  2018.02.28  0.94576
1030  2018.03.01  0.94897
1031  2018.03.02  0.94238
1032  2018.03.04  0.93787
1033  2018.03.05  0.94075
1034  2018.03.06  0.94182

[102 rows x 2 columns]