In [1]:
# Nostradamus One: NTS Framework for all pairs.
import pandas as pd
import numpy as np

In [7]:
H1_UsdChf_pd = pd.read_csv('datasets/2018-05-02-UsdChfH1.csv')
H1_UsdChf_Reshaped01_pd = H1_UsdChf_pd.drop(H1_UsdChf_pd.columns[[-1, -1]], axis=1)

H1_UsdChf_Reshaped01_pd

             Time     Open     High      Low    Close
2017.11.08  01:00  0.99917  0.99928  0.99862  0.99876
2017.11.08  02:00  0.99876  0.99903  0.99849  0.99885
2017.11.08  03:00  0.99883  0.99892  0.99855  0.99877
2017.11.08  04:00  0.99877  0.99881  0.99839  0.99854
2017.11.08  05:00  0.99854  0.99878  0.99839  0.99875
2017.11.08  06:00  0.99875  0.99965  0.99869  0.99910
2017.11.08  07:00  0.99911  0.99941  0.99835  0.99905
2017.11.08  08:00  0.99900  0.99931  0.99829  0.99867
2017.11.08  09:00  0.99867  0.99918  0.99835  0.99907
2017.11.08  10:00  0.99909  0.99910  0.99830  0.99850
2017.11.08  11:00  0.99851  0.99889  0.99814  0.99866
2017.11.08  12:00  0.99867  0.99952  0.99854  0.99914
2017.11.08  13:00  0.99912  1.00019  0.99866  1.00008
2017.11.08  14:00  1.00010  1.00035  0.99937  0.99972
2017.11.08  15:00  0.99972  1.00017  0.99909  0.99998
2017.11.08  16:00  0.99998  1.00056  0.99875  0.99964
2017.11.08  17:00  0.99965  1.00025  0.99929  0.99994
2017.11.08  18:00  0.99994  1.00039  0.99955  1.00010
2017.11.08  19:00  1.00010  1.00050  0.99979  1.00014
2017.11.08  20:00  1.00012  1.00015  0.99980  0.99989
2017.11.08  21:00  0.99990  1.00031  0.99945  0.99996
2017.11.08  22:00  0.99993  1.00005  0.99937  0.99986
2017.11.08  23:00  0.99986  1.00003  0.99950  0.99978
2017.11.09  00:00  0.99978  1.00047  0.99967  1.00019
2017.11.09  01:00  1.00020  1.00050  0.99947  0.99955
2017.11.09  02:00  0.99958  0.99987  0.99930  0.99980
2017.11.09  03:00  0.99977  0.99997  0.99933  0.99993
2017.11.09  04:00  0.99993  0.99998  0.99898  0.99907
2017.11.09  05:00  0.99906  0.99908  0.99803  0.99851
2017.11.09  06:00  0.99853  0.99870  0.99735  0.99774
...           ...      ...      ...      ...      ...
2018.03.09  14:00  0.95030  0.95101  0.94945  0.95051
2018.03.09  15:00  0.95053  0.95104  0.94907  0.94997
2018.03.09  16:00  0.95000  0.95033  0.94871  0.94920
2018.03.09  17:00  0.94920  0.95016  0.94884  0.94992
2018.03.09  18:00  0.94991  0.95094  0.94964  0.95088
2018.03.09  19:00  0.95088  0.95115  0.95056  0.95076
2018.03.09  20:00  0.95077  0.95143  0.95060  0.95104
2018.03.09  21:00  0.95104  0.95143  0.95103  0.95116
2018.03.11  21:00  0.95033  0.95120  0.94968  0.95102
2018.03.11  22:00  0.95101  0.95133  0.95088  0.95108
2018.03.11  23:00  0.95107  0.95121  0.95073  0.95084
2018.03.12  00:00  0.95085  0.95107  0.95026  0.95055
2018.03.12  01:00  0.95055  0.95102  0.94987  0.95004
2018.03.12  02:00  0.95007  0.95024  0.94976  0.94983
2018.03.12  03:00  0.94984  0.95002  0.94971  0.94981
2018.03.12  04:00  0.94982  0.94991  0.94921  0.94929
2018.03.12  05:00  0.94930  0.95011  0.94928  0.94999
2018.03.12  06:00  0.94997  0.95025  0.94969  0.94980
2018.03.12  07:00  0.94981  0.95018  0.94859  0.94943
2018.03.12  08:00  0.94944  0.94983  0.94845  0.94846
2018.03.12  09:00  0.94849  0.94971  0.94846  0.94969
2018.03.12  10:00  0.94970  0.95000  0.94916  0.94973
2018.03.12  11:00  0.94975  0.95078  0.94962  0.95046
2018.03.12  12:00  0.95043  0.95051  0.94962  0.94977
2018.03.12  13:00  0.94978  0.95014  0.94862  0.94868
2018.03.12  14:00  0.94872  0.94986  0.94782  0.94788
2018.03.12  15:00  0.94787  0.94891  0.94735  0.94883
2018.03.12  16:00  0.94887  0.94920  0.94778  0.94843
2018.03.12  17:00  0.94842  0.94873  0.94716  0.94754
2018.03.12  18:00  0.94756  0.94763  0.94599  0.94615

[2081 rows x 5 columns]

In [3]:
T2100UsdChf_pd = H1_UsdChf_Reshaped01_pd [(H1_UsdChf_Reshaped01_pd['Time'] == '21:00')]
# T2100UsdChf_pd

T0400UsdChf_pd = H1_UsdChf_Reshaped01_pd [(H1_UsdChf_Reshaped01_pd['Time'] == '04:00')]
# T0400UsdChf_pd

In [4]:
T0400UsdChf_Reshaped01_pd = H1_UsdChf_Reshaped01_pd [(H1_UsdChf_Reshaped01_pd['Time'] == '04:00')]
T0400UsdChf_Reshaped01_pd.columns = ['T04', 'OO4','H04','L04','C04']

# T0400UsdChf_Reshaped01_pd

T2100UsdChf_Reshaped01_pd = H1_UsdChf_Reshaped01_pd [(H1_UsdChf_Reshaped01_pd['Time'] == '21:00')]
T2100UsdChf_Reshaped01_pd.columns = ['T21', 'O21','H21','L21','C21']

# T2100UsdChf_Reshaped01_pd

In [5]:
T2100x0400_pd = pd.concat([T2100UsdChf_Reshaped01_pd, T0400UsdChf_Reshaped01_pd], axis=1)
T2100x0400_pd

## WARNING: LOOKS LIKE THERE'S A PROBLEM WITH THE DATA!

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  """Entry point for launching an IPython kernel.

,T21,O21,H21,L21,C21,T04,OO4,H04,L04,C04
2017.11.08,21:00,0.99990,1.00031,0.99945,0.99996,04:00,0.99877,0.99881,0.99839,0.99854
2017.11.09,21:00,0.99416,0.99434,0.99359,0.99359,04:00,0.99993,0.99998,0.99898,0.99907
2017.11.10,21:00,0.99571,0.99605,0.99519,0.99572,04:00,0.99447,0.99495,0.99432,0.99488
2017.11.12,21:00,0.99637,0.99644,0.99547,0.99575,NaN,NaN,NaN,NaN,NaN
2017.11.13,21:00,0.99592,0.99620,0.99589,0.99611,04:00,0.99639,0.99699,0.99634,0.99694
2017.11.14,21:00,0.98946,0.98977,0.98908,0.98924,04:00,0.99647,0.99655,0.99619,0.99640
2017.11.15,21:00,0.98806,0.98853,0.98779,0.98822,04:00,0.98866,0.98890,0.98853,0.98889
2017.11.16,21:00,0.99391,0.99423,0.99338,0.99388,04:00,0.98896,0.98971,0.98895,0.98949
2017.11.17,21:00,0.98847,0.98929,0.98823,0.98825,04:00,0.99163,0.99236,0.99139,0.99235
2017.11.19,21:00,0.98842,0.98881,0.98842,0.98872,NaN,NaN,NaN,NaN,NaN
2017.11.20,21:00,0.99359,0.99360,0.99294,0.99330,04:00,0.98849,0.98902,0.98839,0.98901
2017.11.21,21:00,0.99123,0.99160,0.99098,0.99131,04:00,0.99269,0.99311,0.99266,0.99294
2017.11.22,21:00,0.98187,0.98200,0.98139,0.98144,04:00,0.99068,0.99073,0.99030,0.99057
2017.11.23,21:00,0.98105,0.98190,0.98074,0.98166,04:00,0.98146,0.98169,0.98133,0.98137
2017.11.24,21:00,0.97931,0.97972,0.97852,0.97929,04:00,0.98193,0.98205,0.98143,0.98174
2017.11.26,21:00,0.97849,0.97976,0.97813,0.97917,NaN,NaN,NaN,NaN,NaN
2017.11.27,21:00,0.98156,0.98188,0.98107,0.98135,04:00,0.98070,0.98079,0.98020,0.98037
2017.11.28,21:00,0.98436,0.98436,0.98317,0.98381,04:00,0.98132,0.98162,0.98109,0.98140
2017.11.29,21:00,0.98414,0.98450,0.98380,0.98439,04:00,0.98402,0.98485,0.98395,0.98485
2017.11.30,21:00,0.98361,0.98364,0.98282,0.98338,04:00,0.98401,0.98452,0.98394,0.98452
2017.12.01,21:00,0.97647,0.97663,0.97534,0.97561,04:00,0.98374,0.98400,0.98341,0.98397
2017.12.03,21:00,0.98150,0.98152,0.98085,0.98134,NaN,NaN,NaN,NaN,NaN
2017.12.04,21:00,0.98539,0.98552,0.98467,0.98476,04:00,0.98249,0.98253,0.98210,0.98233
2017.12.05,21:00,0.98736,0.98759,0.98693,0.98719,04:00,0.98439,0.98460,0.98411,0.98458
2017.12.06,21:00,0.98980,0.98999,0.98953,0.98972,04:00,0.98658,0.98696,0.98579,0.98602
2017.12.07,21:00,0.99421,0.99457,0.99414,0.99421,04:00,0.98934,0.98987,0.98921,0.98986
2017.12.08,21:00,0.99284,0.99291,0.99224,0.99254,04:00,0.99462,0.99536,0.99443,0.99524
2017.12.10,21:00,0.99375,0.99403,0.99368,0.99376,NaN,NaN,NaN,NaN,NaN
2017.12.11,21:00,0.99174,0.99203,0.99161,0.99170,04:00,0.99176,0.99201,0.99175,0.99197
2017.12.12,21:00,0.99115,0.99142,0.99085,0.99137,04:00,0.99173,0.99193,0.99158,0.99179
...,...,...,...,...,...,...,...,...,...,...
2018.02.06,21:00,0.93705,0.93743,0.93539,0.93584,04:00,0.93123,0.93241,0.93067,0.93217
2018.02.07,21:00,0.94368,0.94412,0.94241,0.94370,04:00,0.93531,0.93547,0.93444,0.93489
2018.02.08,21:00,0.93599,0.93635,0.93571,0.93591,04:00,0.94396,0.94514,0.94384,0.94457
2018.02.09,21:00,0.93998,0.93998,0.93913,0.93934,04:00,0.93761,0.93831,0.93749,0.93822
2018.02.11,21:00,0.93955,0.93968,0.93955,0.93956,NaN,NaN,NaN,NaN,NaN
2018.02.12,21:00,0.93903,0.93951,0.93887,0.93899,04:00,0.93791,0.93813,0.93762,0.93807
2018.02.13,21:00,0.93506,0.93514,0.93467,0.93467,04:00,0.93906,0.93917,0.93793,0.93831
2018.02.14,21:00,0.92898,0.92958,0.92889,0.92928,04:00,0.93073,0.93278,0.93068,0.93273
2018.02.15,21:00,0.92149,0.92222,0.92145,0.92188,04:00,0.92750,0.92815,0.92624,0.92810
2018.02.16,21:00,0.92763,0.92763,0.92685,0.92732,04:00,0.92065,0.92089,0.91895,0.91945
2018.02.18,21:00,0.92724,0.92735,0.92724,0.92735,NaN,NaN,NaN,NaN,NaN
2018.02.19,21:00,0.92878,0.92905,0.92839,0.92899,04:00,0.92745,0.92819,0.92732,0.92793
2018.02.20,21:00,0.93576,0.93630,0.93576,0.93602,04:00,0.93066,0.93098,0.93017,0.93060
2018.02.21,21:00,0.93828,0.93894,0.93765,0.93863,04:00,0.93716,0.93794,0.93666,0.93777
2018.02.22,21:00,0.93292,0.93317,0.93265,0.93273,04:00,0.93881,0.93943,0.93873,0.93937
2018.02.23,21:00,0.93667,0.93702,0.93585,0.93595,04:00,0.93439,0.93534,0.93424,0.93508
2018.02.25,21:00,0.93620,0.93698,0.93548,0.93698,NaN,NaN,NaN,NaN,NaN
2018.02.26,21:00,0.93806,0.93833,0.93759,0.93777,04:00,0.93443,0.93478,0.93424,0.93451
2018.02.27,21:00,0.93902,0.93930,0.93880,0.93884,04:00,0.93762,0.93801,0.93737,0.93774
2018.02.28,21:00,0.94432,0.94457,0.94394,0.94442,04:00,0.93987,0.94018,0.93965,0.93996
2018.03.01,21:00,0.94225,0.94225,0.94151,0.94161,04:00,0.94499,0.94544,0.94478,0.94515
2018.03.02,21:00,0.93714,0.93782,0.93700,0.93708,04:00,0.94015,0.94017,0.93967,0.94012
2018.03.04,21:00,0.93463,0.93693,0.93455,0.93624,NaN,NaN,NaN,NaN,NaN
2018.03.05,21:00,0.94010,0.94028,0.93969,0.93972,04:00,0.93600,0.93635,0.93599,0.93627
2018.03.06,21:00,0.94083,0.94088,0.93997,0.94055,04:00,0.93909,0.93963,0.93899,0.93959
2018.03.07,21:00,0.94304,0.94345,0.94271,0.94335,04:00,0.93719,0.93757,0.93681,0.93753
2018.03.08,21:00,0.95093,0.95116,0.95056,0.95091,04:00,0.94293,0.94339,0.94281,0.94326
2018.03.09,21:00,0.95104,0.95143,0.95103,0.95116,04:00,0.95195,0.95247,0.95173,0.95212
2018.03.11,21:00,0.95033,0.95120,0.94968,0.95102,NaN,NaN,NaN,NaN,NaN
2018.03.12,NaN,NaN,NaN,NaN,NaN,04:00,0.94982,0.94991,0.94921,0.94929

In [6]:
mDataBullBear = concat0421Table ['C21'] - concat0421Table ['C04']
# mDataBullBear

mDataBullBear_pd = pd.DataFrame (mDataBullBear, columns = ['BlBr Calc'])
# mDataBullBear_pd

concat0421BlBrTable_pd = pd.concat([concat0421Table, mDataBullBear_pd], axis=1)
# concat0421BlBrTable_pd

mDataBullBearResult = np.where (concat0421BlBrTable_pd ['BlBr Calc'] > 0, 'bull', 'bear')
mDataBullBearResult_pd = pd.DataFrame (mDataBullBearResult, columns = ['Bull or Bear'])

# mDataBullBearResult_pd 
concat0421BlBrResTable_pd = pd.concat([concat0421BlBrTable_pd, mDataBullBearResult_pd], axis=1)
concat0421BlBrResTable_pd

NameError: name 'concat0421Table' is not defined

In [ ]:
mDataBullBearResult_pd

In [ ]:
dailyFullUsdChfD1_pd = pd.read_csv('datasets/2018-05-02-UsdChfD1.csv')
dailyFullUsdChfD1_pd
dailyFullUsdChfD1_pd.columns = ['0', '0','DHigh','DLow','0', '0']
dailyFullUsdChfD1_pd

In [ ]:
# If Buy of If Sell 
mDataPositionBuy = dailyFullUsdChfD1_pd ['DHigh'] - concat0421Table ['C04']
mDataPositionBuy_pd = pd.DataFrame (mDataPositionBuy, columns = ['If Buy'])
# Print
# DataPositionBuy_pd

mDataPositionSell = concat0421Table ['C04'] - dailyFullUsdChfD1_pd ['DLow']
mDataPositionSell_pd = pd.DataFrame (mDataPositionSell, columns = ['If Sell'])
# Print 
# mDataPositionSell_pd 

concatIfBuySell_pd = pd.concat([mDataPositionBuy_pd, mDataPositionSell_pd], axis=1)
# Print
# concatIfBuySell_pd

# Convert to Numpy
concatIfBuySell_np = concatIfBuySell_pd.values
# concatIfBuySell_pd

mDataBullBearResult_np = mDataBullBearResult_pd.values
# Print
# mDataBullBearResult_pd

concatIfBuySell_pd = concatIfBuySell_pd.reset_index(drop=True)
concatIfBuySell_pd

concatIfBuySellBlBrRes_pd = pd.concat([concatIfBuySell_pd, mDataBullBearResult_pd], axis=1)
# Print
# concatIfBuySellBlBrRes_pd

# Assign rename to more readable variable
summaryIfBuySellBullBearResult_pd = concatIfBuySellBlBrRes_pd.dropna()

# Print
summaryIfBuySellBullBearResult_pd

In [ ]:
# ** Capture all bull and capture all bear

# Bull
summaryBuyEntry_pd = summaryIfBuySellBullBearResult_pd[(summaryIfBuySellBullBearResult_pd['Bull or Bear'] == 'bull')]

# Print
# summaryBuyEntry_pd

# Bear
summarySellEntry_pd = summaryIfBuySellBullBearResult_pd[(summaryIfBuySellBullBearResult_pd['Bull or Bear'] == 'bear')]

# Print

In [ ]:
BuyPosSubResult = np.where (summaryBuyEntry_pd ['If Buy'] > 0.000500, 'Success', 'Fail')
BuyPosSubResult_pd = pd.DataFrame (BuyPosSubResult, columns = ['Buy Result'])
BuyPosSubResult_pd  

# concatIfBuySellBlBrRes_pd

In [ ]:
# Convert To Numpy 
BuyPosSubResult_np = BuyPosSubResult_pd.values

# Test count success 
(BuyPosSubResult_np == 'Success').sum() 

# Count Contents
countResultForBuy = len(BuyPosSubResult_np)
countSuccessResultBuy = (BuyPosSubResult_np == 'Success').sum() 

WinRateForBuy = countSuccessResultBuy / countResultForBuy
WinRateForBuy
# countSuccessResultBuy

In [ ]:
SellPosSubResult = np.where (summarySellEntry_pd ['If Sell'] > 0.000500, 'Success', 'Fail')
SellPosSubResult_pd = pd.DataFrame (SellPosSubResult, columns = ['Sell Result'])
SellPosSubResult_pd  

# Convert To Numpy
SellPosSubResult_np = SellPosSubResult_pd.values
(SellPosSubResult_np == 'Success').sum()

# Count Contents
countResultForSell = len(SellPosSubResult_np)
countSuccessResultSell = (SellPosSubResult_np == 'Success').sum() 

WinRateForSell = countSuccessResultSell / countResultForSell
WinRateForSell

# Note: Needs to drop the NaN within the column.

In [ ]:
SellPosSubResult_pd